### ISSUE TITLE
Scanner rules grammar needs compliance-related metadata

### ISSUE THREAD

**Issue by binamov** [forseti-security/forseti-security#1001]
Having worked with [InSpec](https://github.com/chef/inspec), a compliance-as-code framework, in the past, some of the things the InSpec team did well was design the grammar with the Compliance officer in mind. In particular, forseti scanner rules grammar should have additional meta-data points to provide audit-grade value to the scans:

- **$rule_description** because a reviewer needs to understand what the rule is. $rule_name is not enough.
- **$rule_reference** to point to the originating reason for the rule, eg FDA Paragraph 6, section 13; or PCI control 2.325, etc. We've all seen organizations adhering to rules like frequent password rotation that have no security justifications when using 2FA and no one can pinpoint the reason WHY the rule was implemented in the first place.
- **$rule_impact** to indicate how critical the rule is. Some rules, eg. desktop background image, are not really critical and should be noted, but not acted upon; while others, eg making sure the Spectre patch is installed, are critical and should trigger an alert.

**Comment by jjawad-google** [comment]
@joecheuk to provide an update.

**Comment by blueandgold** [comment]
This will be added for the Config Validator Policy Library.
