### ISSUE TITLE
Code lab 1: for querying root_id and import it to model

### ISSUE THREAD

**Issue by jiyunyao** [forseti-security/forseti-security#1032]
Starting from the branch [codelab-root_id-question](https://github.com/GoogleCloudPlatform/forseti-security/tree/codelab-root_id-question), one can practice reimplementing:
1. Add a function in inventory storage to query the root_id of an inventory snapshot.
2. Import the root_id to the data model description.

My solution is at branch [codelab-root_id-sol](https://github.com/GoogleCloudPlatform/forseti-security/tree/codelab-root_id-sol).

How to see the solution:
Compare branches codelab-root_id-sol and codelab-root_id-question, the diff will provide an idea what has been changed.

**Comment by mirons-google** [comment]
Thanks @jiyunyao we'll leave this here for now and revisit getting a codelab for the website 2.0-docs. Consider this done for now.
