### ISSUE TITLE
Code lab 2: Get if gsuites is enabled in this inventory and import this info to model

### ISSUE THREAD

**Issue by jiyunyao** [forseti-security/forseti-security#1037]
Starting from the branch [codelab-gsuite_enabled-question](https://github.com/GoogleCloudPlatform/forseti-security/tree/codelab-gsuite_enabled-question), one can practice reimplementing:

1. Find out how to determine if GSuite collection is enabled when the inventory snapshot is created.
2. Add a function in inventory storage to query whether the GSuite is enabled of an inventory snapshot.
3. Import the GSuite_enabled to the data model description.
My solution is at branch [codelab-gsuite_enabled-sol](https://github.com/GoogleCloudPlatform/forseti-security/tree/codelab-gsuite_enabled-sol)

How to see the solution:
Compare branches codelab-gsuite_enabled-sol and codelab-gsuite_enabled-question, the diff will provide an idea what has been changed.

**Comment by mirons-google** [comment]
Thanks @jiyunyao we'll leave this here for now and revisit getting a codelab for the website 2.0-docs. Consider this done for now.
