### ISSUE TITLE
Add Basic Health Monitoring with Stackdriver

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#108]
## Story
Monitor for anything that someone should respond when the basic health of the service changes.  Such as if the VM host goes down, an alert should be sent. Customers need to know if Forseti is running/healthy which is difficult to determine today.

## Possible Solution(s)
Few more things to consider:
- Is Forseti healthy (is the Forseti process running, is Forseti meeting its SLO?). This can be done with [Stackdriver process health](https://cloud.google.com/monitoring/alerts/ui-conditions-ga); I'm not sure if this is configurable via Terraform. [Terraform supports an uptime check with http calls](https://www.terraform.io/docs/providers/google/r/monitoring_uptime_check_config.html).
- Is the Forseti VM healthy (is the VM running, is the CPU, memory, disk used up?). This can be done with Stackdriver metrics monitoring; I'm not sure if this is configurable via Terraform.
- Is the CloudSQL DB VM healthy (ditto as above).
- Notify on Forseti errors in the logs, which is [available via Terraform](https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html). Is this the same as turning on notifications for new errors?
<img width="1680" alt="Screen Shot 2019-11-11 at 9 17 50 AM" src="https://user-images.githubusercontent.com/10247435/68606833-2871aa80-0464-11ea-9ce0-87fc48089d59.png">

Consider adding an uptime check and alerting when errors occur.

**Comment by Red-Five** [comment]
Would creating an FAQ be first step?

If automating this, Terraform setup of Stackdriver is being developed though its in its early days
https://github.com/terraform-providers/terraform-provider-google/issues/1044

Automatically creating alert policy via terraform is possible https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html

**Comment by gkowalski-google** [comment]
This needs some more specific requirements on what should be automatically configured for monitoring.

**Comment by kevensen** [comment]
@gkowalski-google Agreed.

1. We need to be very specific about our SLO's and SLI's.  e.g.
  a. During inventory, 99% of resource transactions (read from API then write to DB) should take less 
      than X seconds
2. The definition of healthy
3. Consider instrumenting the generation of custom metrics
4. Do not include this in the main Terraform module, but rather as an example that the user can apply separately.

**Comment by gkowalski-google** [comment]
Two main concerns:
- Is forseti running?
- How well is it running?
- Errors?

**Comment by gkowalski-google** [comment]
This is still a nice to have addition.
