### ISSUE TITLE
Make full_name to be an default arg of None in gcp_types

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1095]
In PR #1071, some gcp_type objects have full_name as a required arg.  This is forcing the setting of ```full_name=''``` when casting to the gcp_type object from the rule definition attributes.  This is applied inconsistently across the gcp_types, so it's better to make the full_name as an optional arg with default value of None.

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
