### ISSUE TITLE
Find a way to pretty print last_warning and last_error like strings in the inventory crawl

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1100]
`last_warning: "ApiExecutionError(\'GCP API Error: unable to get project-name from GCP:\\n<HttpError 429 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/project-name:getIamPolicy?alt=json returned \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\">\\n{\\n  \"error\": {\\n    \"code\": 429,\\n    \"message\": \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\",\\n    \"errors\": [\\n      {\\n        \"message\": \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\",\\n        \"domain\": \"global\",\\n        \"reason\": \"rateLimitExceeded\"\\n      }\\n    ],\\n    \"status\": \"RESOURCE_EXHAUSTED\"\\n  }\\n}\\n\',)"`

`last_error: "ApiExecutionError(\'GCP API Error: unable to get project-name from GCP:\\n<HttpError 429 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/project-name:getIamPolicy?alt=json returned \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\">\\n{\\n  \"error\": {\\n    \"code\": 429,\\n    \"message\": \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\",\\n    \"errors\": [\\n      {\\n        \"message\": \"Insufficient tokens for quota \\\'ReadGroup\\\' and limit \\\'CLIENT_PROJECT-100s\\\' of service \\\'cloudresourcemanager.googleapis.com\\\' for consumer \\\'project_number:12345\\\'.\",\\n        \"domain\": \"global\",\\n        \"reason\": \"rateLimitExceeded\"\\n      }\\n    ],\\n    \"status\": \"RESOURCE_EXHAUSTED\"\\n  }\\n}\\n\',)"`

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
