### ISSUE TITLE
Missing permission in FS2.0

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1104]
In a installation of 2.0 I'm seeing this error in the GCE VM instance logs.

`"[forseti-security] WARNING google.cloud.forseti.services.dao(set_done): warnings = Role missing permissions: roles/containeranalysis.notes.attacher"  `

**Comment by jiyunyao** [comment]
This is because some roles contains permissions in testing stage, GCP API won't show their permissions. This is a warning when building data model for the info of users.
