### ISSUE TITLE
Create a pre-push githook

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1109]
This should essentially run the same checks Travis does, but locally before pushing to ensure the push succeeds.

**Comment by blueandgold** [comment]
This is an example of passing locally, but not passing on travis.
https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/367462725

**Comment by mirons-google** [comment]
It's recommended to do this on a per-repository basis to create a directory and update our developer documentation to include using the hooks directory.

https://stackoverflow.com/a/37861972
