### ISSUE TITLE
Forseti 2.0rc1 installer: default admin?

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#1218]
Suggest defaulting the gsuite admin mail to the detected "you are" mail - I think they're often the same and it's a better-than-nothing guess?

e.g.:

+-------------------------------------------------------------------------------
|  Pre-installation checks
+-------------------------------------------------------------------------------
Dry run: False
Advanced mode: False
Forseti branch/tag: 2.0-rc1
Read gcloud info: Success
Current gcloud version: 191.0.0
Gcloud alpha components: True
You are: **my@admin.mail.net**
Project id: forseti2-196701
Organization id: 685768172959
Billing: Enabled
+-------------------------------------------------------------------------------
|  Configuring GSuite Admin Information
+-------------------------------------------------------------------------------
To read G Suite Groups and Users data, please provide a G Suite super admin email address. This step is NOT optional.
Email **[my@admin.mail.net]**:

**Comment by blueandgold** [comment]
@MartenvanWezel , can you please find out how many customers this would affect?  We are also concerned that a default might be more error-prone, vs users to think about this, and find the right super admin email to put in.
