### ISSUE TITLE
Add support for deployment-triggered scanning

### ISSUE THREAD

**Issue by imtheoperator** [forseti-security/forseti-security#1229]
It would be useful to support scanning triggered by a deployment, rather than a schedule. e.g. when deploying via a CD pipeline with Cloud Deployment Manager, Terraform, Maven, etc.

Benefits:
- By using event-driven scans, the violation/threat window can be reduced.
- Some environments change rarely and may only provide 'edit' roles to service accounts. Scanning only needs to happen the environment is modified.

**Comment by blueandgold** [comment]
@joecheuk to reach out and discuss ways to programmatically do this in 2.0.
