### ISSUE TITLE
Implement or Research AuthN/AuthZ for cli / server

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1264]
This is help to remove the use of a client VM, and also allows server API to be usable by other clients.

**Comment by blueandgold** [comment]
Per andrew: Istios may be the right way to do this, to protect gRPC for access control.  Need to see how production-ready it is.  Kubernetes may also need to be a pre-requiste for this this work.

Per Marten: a lot of feedback from customers to just call the server directly, without the client VM.

**Comment by blueandgold** [comment]
Would count as a win, if we can do the initial research and have a design in place.

**Comment by jjawad-google** [comment]
We are planning to incorporate this as part of the FS 3.0 Requirement.
