### ISSUE TITLE
Mute Violations, Especially on Initial Setup

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#1382]
When installing Forseti for the first time in a running organization, it's almost a given that Forseti will be very unhappy about all types of historical choices the user made. 

Rather than nag the user incessantly, perhaps we should consider implementing an easy way to 'mute' a rule or violation, where the user acknowledges it is 'a fair point' but they will work on it and at some point need to be re-reminded?

The alternative - notification numbness or someone removing the rule by force are less desirable.

**Comment by blueandgold** [comment]
This issue has been re-raised by @MartenvanWezel as a product priority, that would be useful for multiple users.

**Comment by ryanismert** [comment]
This should align with any work that we do roundtripping status from CSCC. I'm going to close this issue (esp since we haven't worked on it since it was opened), and we'll add this to future work if/when we do the CSCC stuff.
