### ISSUE TITLE
Feature Request: add a GCE Scanner

### ISSUE THREAD

**Issue by bdesbiolles** [forseti-security/forseti-security#1394]
The firewall rule scanner allows us to control and restrict firewall rules. But, for those targeting a tag, there is no way to whitelist/blacklist instances from using a tag or combining tags. 

I would like to be able to check if a user create an instance with the http-server tag for instance. Or prevent services marked as "internal" to be associated with a firewall rule exposing them externally.

Thanks

**Comment by bdesbiolles** [comment]
Ok thanks, I have no timeframe either but I'd be happy to work on it with you !

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
