### ISSUE TITLE
Feature request: Container Registry Vulnerability Scanning

### ISSUE THREAD

**Issue by Glennvd** [forseti-security/forseti-security#1410]
Google Container Registry Vulnerability Scanner (https://cloud.google.com/container-registry/docs/vulnerability-scanning) scans all docker images hosted in container registry for known vulnerabilities. It would be nice if we can add those vulnerabilities to the inventory and scanning modules. Mainly for things like new CVS's that we're detected, CVS score, limits on the age of the docker image or last X uploaded, etc..

I know the feature is currently still in the alpha phase, but it would be nice to know if it's on the roadmap. And if so, what kind of policy rules that could be useful.

**Comment by mirons-google** [comment]
Thanks @Glennvd we currently have no plans to work on this, but think it would be a good idea once the API is out of the `Alpha` phase. Let us know if you'd be willing to work on this and our team can help support.

**Issue Review**: Revisit once the API is GA'd

**Comment by rllin-fathom** [comment]
I heavily second this request!

thoughts on stepping stones towards a full scanner:

1. checks that vuln scan is enabled
2. checks for nonzero fixes available per image
3. checks for nonzero critical CVEs
4. full CVEs stats

Even just having the first would be great!
