### ISSUE TITLE
Check Installer's Initialization Completed Successfully

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1418]
A couple of users reports that Forseti installation failed.

* https://github.com/GoogleCloudPlatform/forseti-security/issues/1415
* https://groups.google.com/a/forsetisecurity.org/d/msg/discuss/4MF05Mt9HYM/AVE8frvaCgAJ

After some troubleshooting by @joecheuk , the problem might be related to the pip unable to install the needed packages.
https://github.com/pypa/warehouse/issues/3705

There are a couple of issues here:
* More immediately, we should handle this better in case it happens again in the future.
* More generally, we need to add some checks to make sure the initialization process actually completed successfully, and that forseti is really ready to be used.  This will really help to improve the user experience.

**Comment by blueandgold** [comment]
This can also happen:
https://github.com/GoogleCloudPlatform/forseti-security/pull/1419

**Comment by mirons-google** [comment]
One way to do this might be to do the same thing that the docker image uses:

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/setup/scripts/docker_install_forseti.sh#L43

**Comment by blueandgold** [comment]
Per Joe: This could be a simple check to run a forseti command at the end of installation on the server to verify everything is really successful.
