### ISSUE TITLE
Switch Forseti Security to using python3

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1437]
https://docs.python.org/3/howto/pyporting.html

**Comment by umairidris** [comment]
FWIW the hard deadline for this is EO2019: https://pythonclock.org/

**Comment by hshin-g** [comment]
@gpshead We are planning on migrating over to Py3 sometime in Q1 2019. We will keep you updated once our timeframe is finalized. @jjawad-google

**Comment by jjawad-google** [comment]
We are committed to completing this by EOQ Q1'19.

**Comment by umairidris** [comment]
A good place to start this migration could be from the installer. It is a separate piece not dependent on any other code of Forseti. We would immediately benefit as we can just call python instead of explicitly forcing python2 in our forseti install calls.

**Comment by dekuhn** [comment]
Update https://forsetisecurity.org/docs/latest/develop/dev/setup.html#creating-service-accounts docs to account for python3 installation.

**Comment by Red-Five** [comment]
Any new advice here? 

I am in the process of attempting to upgrade to python3 as it is a requirement for Stackdriver Profiler on GKE

I am assuming (at least) 
modify apt_packages.txt to include python3 equivalents
modify any references to pip in the dockerfile to use python3 -m pip install format instead

**Comment by Red-Five** [comment]
Next '19 Video on Python 2 to 3: Migration Patterns

https://www.youtube.com/watch?v=Bye7Rms0Vgw

**Comment by blueandgold** [comment]
@hshin-g is actively working on this. @hshin-g, can you share your progress here?

**Comment by hshin-g** [comment]
@Red-Five That looks correct, and making sure that any Python references are for Py3, and not Py2. Have been running `futurize` on the Forseti source code as well to make sure that everything is Python 3 compliant.

**Comment by Red-Five** [comment]
( After watching the Next 19 video I see the migration may not be fully automatic. )

I see a number of specific library versions listed and that stumped me as I have no idea as to what versions are to be used for Python 3 or if all these libraries even have Python3 versions:
Ref. https://github.com/forseti-security/forseti-security/blob/17261898a33fb8e052ff528125450415a04c9b9c/setup.py#L35

How close are we to being able to try Python 3?

**Comment by hshin-g** [comment]
We are looking to have the Py3 migration be complete by v2.16.0.

**Comment by hshin-g** [comment]
@Red-Five Here is our plan to migrate to Python 3: https://docs.google.com/document/d/1VkYN2JtUdb0b4peqAMcDgQolA4SEjVdcYhbGwLVpVpQ/edit?usp=sharing

Your comments and suggestions are welcome!

**Comment by dekuhn** [comment]
Related Python 3 migration concerns / timelines for Google: #2787

**Comment by Red-Five** [comment]
@hshin-g Is there a branch for the migration work? If not, would you be willing to create one
for community learning, change reviews, participation if you get stuck?

**Comment by hshin-g** [comment]
@Red-Five The migration branch is called `fs-future`.

**Comment by dekuhn** [comment]
Python 3 migration completed with release [v2.16](https://github.com/forseti-security/forseti-security/releases/tag/v2.16.0)
