### ISSUE TITLE
Integration test - run the importer unit tests in MySQL environment instead of SQLite

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#1441]
Even though SQLite is very similar to MySQL, some of the underlying structures are different. We are currently using SQLite to run the importer unit tests and we want to make sure our unit tests also pass in MySQL environment.

Example:
varchar field in MySQL is case insensitive and the same field in SQLite is case sensitive so we can have our unit tests to test about casing and pass locally with SQLite but breaks in the production environment with MySQL.

SQLite:
![image](https://user-images.githubusercontent.com/5330393/39011696-0f35eefa-43c7-11e8-8d8b-b0243fb72267.png)

MySQL:
![image](https://user-images.githubusercontent.com/5330393/39011706-16546eb4-43c7-11e8-9beb-8c780c806e9f.png)

**Comment by blueandgold** [comment]
We should add the various casing of data to our test environment, which will surface any differences during our dev/release testing

**Comment by blueandgold** [comment]
Unblocking this from 2.0 launch, since more work will be required and the immediate bug that raised this issue is resolved.

**Comment by jjawad-google** [comment]
This task needs to be part of the integration testing framework.
