### ISSUE TITLE
Feature request: audit kubernetes resources

### ISSUE THREAD

**Issue by haf** [forseti-security/forseti-security#1522]
First, help us help you by providing the following information when opening an issue.

 - [x] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation): v2-rc2
 - [x] Note how you deployed (via Deployment Manager, local system, etc.): quickstart w/ params & changes in deployment manager.

I think it would be great if the three pieces (inv, scn, enf) and in particular the inventory + scanner would support primarily-kubernetes deployments. For example; RBAC in kube and how that synchronises to the organisation groups; or  permissions lacking for a particular user.

Further, support for Calico inter-pod/networking policies to enforce e.g. a classically tiered approach with frontend, backend and database communicating between each other in that order. Or e.g. enforcing that pods/services tagged "db" have egress to non-RFC1918 addresses denied would be great.

I'm currently reading [Zero Trust Networks](https://www.safaribooksonline.com/library/view/zero-trust-networks/9781491962183/) containing a lot of sage advice. Some things that could be asserted to exist and be active are; each ingress-enabled services has a policy-enforcement side-car container running. Or that the [network policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) are as expected (similar to tags/firewalls in the current version of Forseti).

**Comment by blueandgold** [comment]
Yes, we do not have this existing functionality in place.  But if you like to contribute, we would definitely be happy to help you get started.

**Comment by jjawad-google** [comment]
@blueandgold is this covered in #1991?

**Comment by dekuhn** [comment]
Do the following resources in our inventory cover your use case? I think the rbac.authorization.k8s.io/Role inventory has the data you would be looking for?

There are a number of Config Validator scanners for GKE data here: https://github.com/forseti-security/policy-library/tree/master/samples

Google Kubernetes Engine

API reference
• container.googleapis.com/Cluster

API reference
• k8s.io/Node
• k8s.io/Pod
• k8s.io/Namespace
• rbac.authorization.k8s.io/Role
• rbac.authorization.k8s.io/RoleBinding
• rbac.authorization.k8s.io/ClusterRole
• rbac.authorization.k8s.io/ClusterRoleBinding

**Comment by dekuhn** [comment]
As CAI adds support for resources we will add these to Forseti Inventory. Closing.
