### ISSUE TITLE
Improve the style of the output from command `forseti server configuration get`

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#1525]
The current output is a json dump and is a bit hard to read, maybe we can format the json dump and make it looks like what we have in the yaml file.

![image](https://user-images.githubusercontent.com/5330393/39945974-3f2df38a-5521-11e8-9c74-ff3254df354e.png)

**Comment by blueandgold** [comment]
This should be something that customers can paste back into the config file and should just work (i.e. in yaml format).
