### ISSUE TITLE
Quota limit warnings

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#1599]
Many GCP products have quotas either imposed, or that make sense for policy (usually financial) reasons. We should build scanners to check for these *before* they run out.  

Stackdriver does some of this of course, but e.g. you can only have [10 VPN tunnels per project](https://cloud.google.com/vpn/quotas) - we should alert if VPNtunnelcount > 8

Further thought: We could create a global setting of "resource limit warning %" where if you set it to 10, you will get a ping once you hit 90% for anything. 

Obviously if we start alerting on this stuff it will become more and more important to have a smooth 'acknowledge and disable/mute violation' procedure.

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
