### ISSUE TITLE
Allow notifier to run on individual categories

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#1601]
The only option we have now is 

`forseti notifier run`

and this will run all the notifiers within, we should allow user to choose what notifier they want to run
e.g.
`forseti notifier run inventory_summary`
`forseti notifier run cscc_violations`
`forseti notifier run resource_violations`

**Comment by blueandgold** [comment]
There is no immediate plan to work on this. Please re-open if there's interest.
