### ISSUE TITLE
Codeblocks on the website expand outside their box

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1678]
![image](https://user-images.githubusercontent.com/22750334/41417593-6d2e99ea-6fb3-11e8-86b2-14f253426a98.png)

**Comment by EricBeach** [comment]
I am looking at https://forsetisecurity.org/docs/latest/use/cli/inventory.html and even if I adjust the resolution, things look fine. Could you clarify?

**Comment by mirons-google** [comment]
Thanks for following up @EricBeach . I just visited the same URL you linked to in Chrome on Mac OS and got the same screenshot as posted in the original issue comment.

**Comment by EricBeach** [comment]
Page renders fine on Linux. It looks like an even cleaner fix is removing the "background-color" property to the ".highlighter-rouge" class which encloses the <code> element

**Comment by EricBeach** [comment]
The underlying issue seems to be the mix of overflow:auto to the enclosing pre and the margin in the <code>. Seems like a bug with  https://github.com/jekyll/jekyll library.

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
