### ISSUE TITLE
Tab headings should be left aligned not centered

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1679]
![image](https://user-images.githubusercontent.com/22750334/41417410-e5943652-6fb2-11e8-9a42-21661eb5f896.png)

**Comment by EricBeach** [comment]
can you clarify with a specific URL and class that is miss-aligned and I can take a look? examining https://forsetisecurity.org/docs/latest/concepts/ everything except docs-nav class is left-aligned.

**Comment by mirons-google** [comment]
@EricBeach the screenshot should cover it still. Visiting the URL you linked to, I still see the tabs center aligned. Is that not the case for you?

**Comment by EricBeach** [comment]
@mirons-google - so this bug is basically to move the class dovs-nav class from center align to left align?

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
