### ISSUE TITLE
Update architecture diagram for Cloud SCC

### ISSUE THREAD

**Issue by mcapts** [forseti-security/forseti-security#1783]
Please update the architecture diagram at https://forsetisecurity.org/docs/latest/concepts/architecture.html to include the Notifier -> Cloud Security Command Center feature (as per discussion with @blueandgold).

**Comment by mirons-google** [comment]
@jjawad-google can you handle this? Reach out to me offline and I'll show you the steps, thanks!

**Comment by mirons-google** [comment]
*Grooming note*: Try to combine this with other imagery changes.

**Comment by red2k18** [comment]
- Review if there are additional components that needs to be added to the architecture diagram besides what we have in the request (let's target this for v2.15).
- Once complete, file a bug to update the diagram.

**Comment by red2k18** [comment]
Is this ready to go out in 2.17?

**Comment by dekuhn** [comment]
This was already completed: https://forsetisecurity.org/docs/latest/concepts/architecture.html
