### ISSUE TITLE
Add benchmark to the Forseti processes with OpenCencus

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1845]
This came out of #1844, where we need to know more info on where exactly the slowness is coming from: whether it's the actual inventory, or building the data model, etc.

It would also be nice to benchmark the the individual steps, like the inventory of different resources (gsuite users, groups, etc), and the running of the scanners & notifiers.

**Comment by mirons-google** [comment]
A follow-up here. This can actually be done a couple ways, AFAIK.

1. A deep integration with Stackdriver
2. Use opencensus.io (which allows other exporters besides Stackdriver).

**Comment by mirons-google** [comment]
Questions we need answers for.

1. Where in each of the core modules (inventory, scanning, model building, etc.) are we spending the most time and should be optimized?
1. Where can I tell a user to go in Stackdriver to gather the appropriate profiling information to debug an issue they opened?
1. What are the performance expectations for various sizes of organizations (buckets, projects, etc.) and G Suite domains (groups, users) a person can expect and what implications does the machine type of the Forseti Server play in that?

**Comment by red2k18** [comment]
Planning to use OpenCensus to collect metrics and traces and Stackdriver exporter to export the metrics to Google Cloud.

**Comment by red2k18** [comment]
Forseti is a security suite composed of gRPC services written in Python. As part of discussions about the instrumentation for Forseti, it was decided to use OpenCensus to collect Forseti metrics, logs, traces and events to add monitoring, tracing and profiling to Forseti services. 

The integration with OpenCensus is out-of-the box and only requires to set up a trace interceptor that will intercept each gRPC call and add code to calculate latency of each request (gRPC calls), and build traces automatically. 

The OpenCensus Stackdriver Stats Exporter exports data to Stackdriver Monitoring which provides visibility into performance, uptime and overall health of cloud-powered applications. Stackdriver ingests that data and generates insights via dashboard, charts, alerts etc.

**Comment by red2k18** [comment]
OpenCensus provides support for following exporters. We plan to give users the ability to choose the exporter. 
-[x] Stackdriver (Python supported for traces)
-[x] Zipkin (Python supported for traces)
-[x] Jaeger (Python supported for traces)
-[x] Instana
-[x] Datadog
-[x] Prometheus
-[x] SignalFX

**Comment by red2k18** [comment]
Implementation plan:

- [ ] Core tracing for gRPC server/client
- [ ] Tracing integration libraries (requests, sqlalchemy, httplib, httplib2)
- [ ] Add spans for one method
- [ ] Add spans for all the methods
- [ ] Add core Monitoring interceptors and core metrics
- [ ] Choose and implement metrics for Monitoring interceptors

**Comment by Red-Five** [comment]
What capabilities will the planned python support for https://cloud.google.com/profiler/ offer?

Will opencensus drill into the grpc calls and give low level visibility or just give the high level times.
Will it need code changes to add spans at various levels for low level visibility?

Yappi is an interim approach that doesn't need any code changes and gives low level visibility.
Example
![forseti-security-yappi](https://user-images.githubusercontent.com/25078066/49048615-64572580-f1a9-11e8-9c13-8cfa14c67b76.png)

**Comment by red2k18** [comment]
#2317 implements instrumentation on Forseti using OpenCensus.

**Comment by blueandgold** [comment]
@Red-Five, thanks for showing us yappi, it looks really interesting.

@red2k18 , can you please follow-up on @Red-Five's questions?

```
What capabilities will the planned python support for https://cloud.google.com/profiler/ offer?

Will opencensus drill into the grpc calls and give low level visibility or just give the high level times.
Will it need code changes to add spans at various levels for low level visibility?

Yappi is an interim approach that doesn't need any code changes and gives low level visibility.
```

![image](https://user-images.githubusercontent.com/6977544/49259488-6cec6d80-f3ee-11e8-9ee9-2224f170af3d.png)

**Comment by ahoying** [comment]
Based on the image, it looks like yappi is only looking at one thread, can it be extended to see all the threads running in the process?

**Comment by blueandgold** [comment]
@ahoying Looks like yappi is recommended for multithreaded apps.
https://stackoverflow.com/questions/653419/how-can-i-profile-a-multithread-program-in-python

**Comment by dekuhn** [comment]
@red2k18 Do we need to add to the plan here updates to enable this through our Terra-form installer? If so can you please add those.

**Comment by red2k18** [comment]
@dekuhn Support to enable/disable tracing using Terraform has been added.

**Comment by gkowalski-google** [comment]
We are not moving forward with OpenCensus, using cloud profiler instead.
