### ISSUE TITLE
Reduce cross dependencies between different modules

### ISSUE THREAD

**Issue by ahoying** [forseti-security/forseti-security#1853]
Several Forseti Security python modules include common classes and functions that are imported by other unrelated modules across the code base. The creates unnecessary complexity in the code base and makes it harder to isolate different modules into distinct micro-services, which is a design goal for future Forseti releases.

**Comment by ahoying** [comment]
Reopening, there is more refactoring that I want to complete.

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
