### ISSUE TITLE
Break up the inventory and model step in cron job.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1882]
User reports that the cron job is slow.  But it's hard to tell what is slow, because the inventory and data model is run as one step.  So, we should break this up into separate steps to get a better idea of what is slow.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/gcp/scripts/run_forseti.sh#L49

#1880 
#1884

**Comment by dekuhn** [comment]
We have addressed the inventory performance challenges this issue is not longer applicable.
