### ISSUE TITLE
Update groups scanner whitelist logic

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#1915]
Mode supported: whitelist

group_email: my_customer will whitelist everyone in the organization.

If there is another rule defined for a subgroup, that rule should override the rule defined from the parent (e.g. my_customer).

Example:
- name: Allow only gmail users to be in my company groups.
  group_email: my_customer
  mode: whitelist
  conditions:
    - member_email: "@gmail.com"

- name: Allow only hotmail users to be in group ABC.
  group_email: abc@my_domain.com
  mode: whitelist
  conditions:
    - member_email: "@hotmail.com"

Currently, the rules are additive and if any of the rules evaluated to true, no violation will be produced. 
i.e. There is no way to restrict group ABC to ONLY allow hotmail users, in this case, we will allow any gmail users OR hotmail users to be in the group.

The updated version of groups scanner should only allow hotmail users be in the group ABC, if the user also wants to include gmail users, he will need to add another conditions to the rule, i.e.

- name: Allow only hotmail AND gmail users to be in group ABC.
  group_email: abc@my_domain.com
  mode: whitelist
  conditions:
    - member_email: "@hotmail.com"
    - member_email: "@gmail.com"

And the first rule "Allow only gmail users to be in my company groups." will produce violations for the hotmail users in the group ABC.

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
