### ISSUE TITLE
Sending notifications via MS Exchange?

### ISSUE THREAD

**Issue by bkudzia** [forseti-security/forseti-security#1920]
Just a general question around using Exchange to send email notifications.  Is there a way to do that?  I have a customer who is curious, for send/receive log purposes.

 - [ ] 2.0 and 2.1
 - [ ] Notifier
 - [ ] No errors being reported
 - [ ] Used the deployer from Git

Thanks!

**Comment by joecheuk** [comment]
Hi @bkudzia ,

We currently only support sending email notifications through the sendgrid API, we don't plan to support MS Exchange in the near future but if this is something you would like to tackle, we are more than happy to help you understand the codebase!

Thanks,
Joe
