### ISSUE TITLE
Uninstall/reinstall script

### ISSUE THREAD

**Issue by rllin-fathom** [forseti-security/forseti-security#1945]
Is there a recommended approach to uninstall or reinstalling?  The install script seems to insist on a new identifier each time, and I can't find if we can set the identifier.

Would manual clean up entail getting rid of all service accounts, VMs, buckets, cloudsql instance, and deployments [1] tied to that unique name, e.g. forseti-server-HASH, be enough?  Is there more to do?

[1] https://github.com/GoogleCloudPlatform/forseti-security/issues/1188#issuecomment-370197875

**Comment by jjawad-google** [comment]
The best approach here should be to move more resources into the Deployment Manager template which will make the uninstall process easier to manage.
