### ISSUE TITLE
cron script needs to catch nonexistent model and err out, or else violations would be out of date

### ISSUE THREAD

**Issue by rllin-fathom** [forseti-security/forseti-security#1971]
v2.2.0

While running `run_forseti.sh` manually on the server,  I saw at the end of inventory creation there was an error about the server being not in communication.  This led to

```
forseti model get MODEL_NAME
```
returning `{}`

The check here https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/gcp/scripts/run_forseti.sh#L60 passes.  This leads to using the last model and thus the violations would be out of date.

1. The script should at least fail if model get returns `{}`
2. or at least exit during https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/gcp/scripts/run_forseti.sh#L68 rather than continuing and using a old model.  i.e. lack of violations being produced is better than out of date violations?

Everything worked again upon retry.  Possibly actual issue is some grpc transiency?

**Comment by hshin-g** [comment]
If it turns out that error handling needs to be implemented, it may also have to be implemented in the Orchestrator container so please notify @kevensen.

**Comment by hshin-g** [comment]
Need to replicate issue here and follow up.

**Comment by blueandgold** [comment]
Another possible output is this:
```
{
  "handle": "",
  "name": "",
  "status": "",
  "description": "",
  "message": "",
  "warnings": "",
  "createdAt": ""
}
```

**Comment by blueandgold** [comment]
We should also reset the CLI config when the `run_forseti.sh` is done.
