### ISSUE TITLE
New home for Docker tests scripts

### ISSUE THREAD

**Issue by ocervell** [forseti-security/forseti-security#1980]
Test scripts (using Docker) are currently located under `install/scripts`. 
Maybe we can move them to a better place like `tests/`.

**Comment by ocervell** [comment]
All the `docker_*.sh` scripts in `install/scripts/` used to run our tests.

**Comment by blueandgold** [comment]
The `forseti-security/tests` is meant for actual tests only.  What is in `forseti-security/install/scripts` are the test runners, so `/install` does not seem to be the bad home for them.  Although a better way to organize them is to put them in a `test` package, such as `forseti-security/install/scripts/test` to more clearly identify them as test runners.  Thoughts?

**Comment by ocervell** [comment]
Couldn't we have folders like `forseti-security/tests/unit` and `forseti-security/tests/docker` ? e.g: OpenCensus something similar in their Python [repo](https://github.com/census-instrumentation/opencensus-python/tree/master/tests). Are the `docker_setup_forseti.sh` and `docker_install_forseti.sh` currently used outside of testing purposes ?

**Comment by mirons-google** [comment]
+1 to @ocervell 's suggestion. The docker scripts have no reason for being in install, they're tests...
