### ISSUE TITLE
Consider Using Priority for Scanner Rules

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2002]
We currently have issues to express exceptions or precedences to multiple rules.

For example:
Rule 1: org-level blacklist for allUsers
Rule 2: project-level whitelist which would allow allUsers in project1, project2, project3

The intention with the example above is to disallow allUsers on all the org's projects, but allow it on the 3 projects.  But as of today, this is not possible to express, and violation would be triggered.

The usage of a priority (like firewall rule priority) would address this, and would determine which rule has precedence, and enable a resource to have several different blacklists and whitelists, and produce the correct violations.

**Comment by blueandgold** [comment]
Another user input:
![image](https://user-images.githubusercontent.com/6977544/45368284-17938380-b598-11e8-8d34-de6ceb078129.png)

**Comment by lukwam** [comment]
Can't you do this for buckets by simply setting up a whitelist, and anything that isn't on the whitelist will be a violation?

**Comment by blueandgold** [comment]
Taking a step back, the bucket ACL also does not have a whitelist mode, but is tracked in the issue below.
https://github.com/GoogleCloudPlatform/forseti-security/issues/787

Even if we do have the whitelist mode, we still have the issue here.  So, that could be one approach, i.e. (similar to firewall rules) having a default or implied blacklist in place for everything, and create rules to define the allowed access to the buckets.  

But currently, in the bucket acl scanner, violation is evaluated if there is a rule that matches a bucket.  if there is no rule that matches the bucket, there will be no violation, i.e. in effect, this is an implied whitelist.

For example, if someone only has 1 rule to define the whitelist for `allUsers` on bucket AAAA, there will be no violation for `allUser` on bucket BBB or bucket CCC since there are no rules explicitly defined for them.
