### ISSUE TITLE
Bug template error

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#2013]
Bug template says:

- [ ] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).

-> this file does not exist anywhere. (no dir google/cloud/security either)

Perhaps you mean:
/home/ubuntu/forseti-security/google/cloud/forseti/__init__.py (client)
or
/home/admin_/forseti-security/google/cloud/forseti/__init__.py (cloud shell)

**Comment by MartenvanWezel** [comment]
This seems easily fixable (and btw it needs to be fixed in github).. I just ran into this again.

(also, there are tons and tons of __init__.py files in that path.. )

1/ Suggest to be clear what you mean by "your installation" - server, client or cloud shell
2/ Fix path and/or just say "cat /home/ubuntu/forseti-security/google/cloud/forseti/__init__.py"

**Comment by blueandgold** [comment]
The issues template is here:
https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/.github/ISSUE_TEMPLATE.md

**Comment by dekuhn** [comment]
fixed by https://github.com/forseti-security/forseti-security/pull/2622
