### ISSUE TITLE
Feature Request - Parse out project name from the full_name in the findings

### ISSUE THREAD

**Issue by davidlauen** [forseti-security/forseti-security#2092]
- [2.5 ] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
 - [ scanner] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.

It would be nice to not have to parse out the project name from the full_name column in a finding report. The full_name column is great, it would be nice to have an **extra column that had only the project name.** In a large organization where we have multiple folder levels the full_name is quite long. example (organization/1234/folder/1234/folder/2234/folder/3234/folder/4234/project/abcd/bucket/bucketname/.

**Comment by jjawad-google** [comment]
This will require some design work on our part and will be part of the next gen inventory.

**Comment by umairidris** [comment]
Does https://github.com/GoogleCloudPlatform/forseti-security/pull/1864 solve part of this?
