### ISSUE TITLE
Request for inventory report to include external ip address count and IAM Member count

### ISSUE THREAD

**Issue by ibenrodriguez** [forseti-security/forseti-security#2121]
- I'm using forseti 2.5

 is there a way for the inventory report to include things like external IP addresses and IAM Member count? 

I will watch the code changes needed to complete this request and then as future changes are requested we can add them ourself.  

If the process to do this is already documented please point me to that so we can include it in the user guide.

Thanks!

**Comment by jjawad-google** [comment]
Are you willing to contribute a notifier to do this? If so we can help you get started.
