### ISSUE TITLE
add scanners and inventory report for dns information

### ISSUE THREAD

**Issue by ibenrodriguez** [forseti-security/forseti-security#2124]
- using forseti version 2.5

I can run the following gcloud cli commands to see DNS details - can these be collected and reported on by forseti?

The inventory report should include:
- count of managed zones
- count of zones with "state" = on <-- this indicates DNSSEC is enabled
- count of zones with "state" = off <-- this indicates DNSSEC is NOT enabled

$ gcloud dns managed-zones list
NAME  DNS_NAME   DESCRIPTION
vzxy  vzxy.net.  VZXY Network Domain

Then for each managed zone we need to collect the details with the "describe" command

$ gcloud dns managed-zones describe vzxy
creationTime: '2018-10-05T21:53:09.649Z'
description: VZXY Network Domain
dnsName: vzxy.net.
dnssecConfig:
  defaultKeySpecs:
  - algorithm: rsasha256
    keyLength: 2048
    keyType: keySigning
    kind: dns#dnsKeySpec
  - algorithm: rsasha256
    keyLength: 1024
    keyType: zoneSigning
    kind: dns#dnsKeySpec
  kind: dns#managedZoneDnsSecConfig
  nonExistence: nsec3
  state: on
id: '1605086928118992716'
kind: dns#managedZone
name: vzxy
nameServers:
- ns-cloud-a1.googledomains.com.
- ns-cloud-a2.googledomains.com.
- ns-cloud-a3.googledomains.com.
- ns-cloud-a4.googledomains.com.

**Comment by jjawad-google** [comment]
Per our discussion last week, you guys would contributing here. We have assigned Hannah from the Forseti team to guide you.

**Comment by ahoying** [comment]
Note that this data is included in the 2.5+ inventory when CAI is enabled. It is not pulled into the Inventory when CAI is not enabled for an organization.

**Comment by ibenrodriguez** [comment]
CAI is enabled by default so the inventory is already collected and including this information.  We only need here.  We will make a new issue for the inventory report and then there will be 2 pull requests - one for each issue.

Writing the new involves a few steps:

1. collect the inventory data in JSON format - done
1. import data from inventory to data model - updating "importer.py" to include specific data desired for the scanner (DNS) - done - need to verify
1. create "dnssec_scanner.py" that will query the data model for information user
1. create "dnssec_rules_engine.py"
1. scanner "dnssec_rules.yaml" is one part of this request - we will also need to create a unit test python file.

**Comment by jjawad-google** [comment]
@hshin-g any update on working with @ibenrodriguez on this issue?

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
