### ISSUE TITLE
Forseti ver 2.6.0 installation error for not an Org Admin

### ISSUE THREAD

**Issue by trawa05** [forseti-security/forseti-security#2158]
- Forseti ver 2.6.0 
 - installation script
 - ERROR: (gcloud.alpha.resource-manager.folders.describe) User [xxx] does not have permission to access folder [yyy] (or it may not exist): The caller does not have permission
 - installation using cloud shell by installer for both client and server

Hey, i am new here and this is my first Forseti installation. I checked all the issues ad found similar problems but i didnt find exact (step by step) explanation how to solve it.

I am trying to setup Forseti for specific project, but getting error message:
_Check parent: folders/yyy
Command "gcloud alpha resource-manager folders describe yyy --format=json" failed/timeout, retrying...
Command "gcloud alpha resource-manager folders describe yyy --format=json" failed/timeout, retrying...
ERROR: (gcloud.alpha.resource-manager.folders.describe) User [xxx] does not have permission to access folder [yyy] (or it may not exist): The caller does not have permission
You need to have an organization set up to use Forseti_

In documentation it is stated: If you are not an Org Admin, there will be errors, but you can safely disregard, as you will manually assign the correct roles later. But in my case no VMs or serivce accounts are created.

To me it is strange that error message indicates folder yyy, which is not the same number as my organization id, and honestly i have no idea how to find what is this yyy folder?

**Comment by knitterb** [comment]
I'm running into the same issue on tags/v2.7.0 for a non-admin installation.

**Comment by trawa05** [comment]
i've tried with 2.7.0, also i checked that i have owner rights for a folder where these project resides - still the same error.
Thing that bothers me is that error refers to project/folder ID that i dont recognize, is there a way to check more details based on ID?

**Comment by jjawad-google** [comment]
@blueandgold who knows how this works to follow up.

**Comment by Red-Five** [comment]
> @blueandgold who knows how this works to follow up.

I think this is a user documentation issue; Ref. https://github.com/GoogleCloudPlatform/forseti-security/issues/2506#issuecomment-456594820

The user running the installation script needs permission to run "gcloud alpha resource-manager folders describe" on all parent folders as the installer jumps to each parent folder in turn until it finds the org parent.
