### ISSUE TITLE
Allow passing in project_id to Forseti installer

### ISSUE THREAD

**Issue by umairidris** [forseti-security/forseti-security#2182]
Today the Forseti installer deduces the project to install the instance by calling gcloud info. We should be able to pass in a project_id flag similar to the gcloud binary to override this.

**Comment by jjawad-google** [comment]
@umairidris would you be willing to contribute this capability?

**Comment by umairidris** [comment]
Sure, it's pretty low priority so no rush on it

**Comment by frozen425** [comment]
Working on this in target_project branch. At the moment the implementation requires a new forseti installation and a single project id. It would not yet support multiple project ids.

**Comment by frozen425** [comment]
Sorry, I misunderstood this ask. #2596 enables a new install arg --target-project, which sets the project to be inventoried, not the project to host the forseti installation.

I'll start this work this week. --project-id , to remove the installation dependency on the gcloud config set project <project Y> , prior to calling the install script.

**Comment by umairidris** [comment]
@frozen425 is this issue fixed with the PR above being merged?

**Comment by dekuhn** [comment]
@umairidris is this request still applicable with the migration to the Terraform installer?

Please reopen if this is still needed. Thanks!
