### ISSUE TITLE
Container Registry Vulnerability Scan Issues

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2190]
After creating Forseti images via Cloud Build (v2.7.0 tag) the Container Registry Vulnerability Scanner report raises multiple security vulnerability issues on the images. 

This could be a blocker for large corporations deploying Forseti as the deployment may not pass the build process acceptance criteria.

**Comment by jjawad-google** [comment]
@angelsungoogle to follow up.

**Comment by angelsungoogle** [comment]
@Red-Five are you using the [https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/docker/cloudbuild.yaml](current docker image we have) ? 
In addition, are you referring to this vulnerabilities section? 
![image](https://user-images.githubusercontent.com/44174167/48799387-d74d3180-ecbb-11e8-94d1-9a95badc6b5f.png)

**Comment by Red-Five** [comment]
Hi Angel, yes and yes :)
Do you have scanning turned on? Vulnerabilities report should not be blank.
(There is a bug on the GUI that the button always says 'Disable Vulnerability Scanning' regardless if is on/off. Feedback already submitted on that.)

**Comment by angelsungoogle** [comment]
Well that’s a very good feedlback. Apparently i don’t have it on. I thought
I had it on when I saw the disable button 😂

**Comment by Red-Five** [comment]
Example

![image](https://user-images.githubusercontent.com/25078066/53456873-0d5a2a00-39fe-11e9-92bc-73ad8c7245f5.png)

**Comment by dekuhn** [comment]
@kevensen @hshin-g can you review this issue and if this is no longer an issue with the new containers for the work we are doing close this as obsolete.

**Comment by kevensen** [comment]
TL;DR - Base container images are immutable.  Over time, as new vulnerabilities are discovered, the registry scanner will reflect this.  This is an unfortunate inevitability.

That said, there are ways to address this.
1. Use a distroless container.  This is dependent on addressing https://github.com/forseti-security/forseti-security/issues/2922.
2. Keep updating the base image as new versions become available.

I think we should close the issue.  Please note, this will be an ongoing and legitimate concern.

**Comment by kevensen** [comment]
I am going to close this issue.  This is something of which we are cognizant.  Please reopen if this merits further discussion here.
