### ISSUE TITLE
Add CloudFunctions

### ISSUE THREAD

**Issue by antoine-castex** [forseti-security/forseti-security#2199]
Adding Cloud functions in the inventory

**Comment by jjawad-google** [comment]
@blueandgold to check with the CAI team when it will be available or we will add it by API.

**Comment by ryanismert** [comment]
@blueandgold to update this issue with CAI timeline.

**Comment by dekuhn** [comment]
We will integrate Cloud Functions when the data is exposed in CAI. Hopefully we will see something here in late Q1 or Q2 2020. 

When supported we will automatically add the integration to our CAI integration for the quarter.
