### ISSUE TITLE
Blacklist scanner failure to grab IP list should raise a Violation and not just err out a Scan run.

### ISSUE THREAD

**Issue by rllin-fathom** [forseti-security/forseti-security#2239]
If just one blacklist endpoint temporarily 504s or is down, https://github.com/GoogleCloudPlatform/forseti-security/blob/82130c33e3ff15a5154449e29f5483fb80a58fa9/google/cloud/forseti/scanner/audit/blacklist_rules_engine.py#L153
will bring down Forseti scans indefinitely.

This should result in a Violation so that it is reported alongside other Violations rather than all scans just being silent.  Failure can only be seen if we look at logs on the VM.

**Comment by knitterb** [comment]
> will bring down Forseti scans indefinitely

Can you explain by "bring down" means?  Does the Forseti server crash?  Do subsequent scans hang?  More details would really help both reproduce and debug this.

> Failure can only be seen if we look at logs on the VM

Which VM and VM logs are you referring to?  Is this on the Forseti server?

**Comment by angelsungoogle** [comment]
@rllin-fathom could you provide a screenshot of the error when forseti is "bring down"? Looks like this could be solved by a straightforward try-catch, but I'd like to see the error to make sure.

**Comment by angelsungoogle** [comment]
handled in [another github issue](https://github.com/GoogleCloudPlatform/forseti-security/issues/2294)

**Comment by rllin-fathom** [comment]
@angelsungoogle @knitterb sorry for the slow response.  The exception that is raised is a standard urllib2 502 exception.  This causes the entire forseti run script to stop.

Could this issue be reopened?  The "fix" just simply skips the violating rule and does not bubble it up to the level of a Forseti Violation.

This means blacklist rules can be silently failing without opportunity for triage.

**Comment by rllin-fathom** [comment]
also i don't believe that other github issue is related?  i may be reading it wrong though.  this is in the scanner of the blacklist engine and not related to network interfaces

**Comment by angelsungoogle** [comment]
@rllin-fathom let us take a look again and get back to you

**Comment by angelsungoogle** [comment]
hey @blueandgold could you please take a look?

**Comment by dekuhn** [comment]
Will not fix. Plan is to deprecated this scanner and not support it going forward.

**Comment by red2k18** [comment]
@dekuhn Can this issue be closed?

**Comment by gkowalski-google** [comment]
Link to the issue to deprecate this scanner: https://github.com/forseti-security/forseti-security/issues/3521.
