### ISSUE TITLE
Starting Forseti Server in Docker Causes Container to Resize, Delaying Startup

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2286]
This is a feature under development and does not require 'production' support.

Investigating. Any ideas welcome.

The re-size delays startup by a minute or so.

**Comment by jjawad-google** [comment]
@angelsungoogle will follow up.

**Comment by Red-Five** [comment]
Closing this issue for now; There was an issue here with cos development earlier, but since I switched focus to k8s deployment this has not been an issue. Will re-open if it becomes an issue worth investigating.
