### ISSUE TITLE
Missing firewall scanner online documentation

### ISSUE THREAD

**Issue by BrunoReboul** [forseti-security/forseti-security#2348]
On line documentation just covers briefly the default firewall rule
https://forsetisecurity.org/docs/latest/configure/scanner/rules.html#location-rules

The configuration section for the firewall scanner is missing here (latest)
https://forsetisecurity.org/docs/latest/configure/scanner/rules.html 

As the firewall is the only topic for which we currently have also an inforcer, it will be great to document it end to end
https://forsetisecurity.org/docs/latest/use/cli/enforcer.html

**Comment by dekuhn** [comment]
Done, thanks Closing Issue.
