### ISSUE TITLE
Update CSCC Integration Documentation

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2353]
Ref. https://forsetisecurity.org/docs/v2.5/configure/notifier/index.html#cloud-scc-notification

States 
![image](https://user-images.githubusercontent.com/25078066/49547247-2ac0a180-f8b0-11e8-8327-9cbe11ae5ab2.png)

This is misleading. The Forseti service account can used.

At the Organization level, go to IAM & Admin -> IAM and add the security center editor role to
the Forseti service account. 

(Today CSCC went into Beta, replace the blurb about the Alpha program signup. Verify that security center editor is still the correct role required.)

**Comment by Red-Five** [comment]
This issue can be closed. I was able to integrate CSCC with Forseti using the new documentation.

**Comment by dekuhn** [comment]
Thanks for the feedback. Closing the issue.
