### ISSUE TITLE
FR - Location scanner - rules should be assessed at the first applicable point in the ancestory tree that has rules

### ISSUE THREAD

**Issue by BrunoReboul** [forseti-security/forseti-security#2371]
Feature Request.

Scanner: location
Request:
Improve the location scanner to work like the firewall scanner, in the way it enables to combine multiple scanner rules following GCP hierarchy: Organization / Folders / Projects, like described [here](https://github.com/GoogleCloudPlatform/forseti-security/blob/v2.8.0/google/cloud/forseti/scanner/audit/firewall_rules_engine.py#L122) 

User story:
As a security manager I want to control that all resources in my organization are located in Europe but I could allow a few exceptions by projects or by folder. I want to do this in a manner that limit the number of forseti location rules to be created:
- At organization level: one rule to white list only resources located in Europe
- For a few folders or even projects a few exception rules, white listing Europe and other locations

So, rules should be assessed at the first applicable point in the ancestory tree that has rules

**Comment by umairidris** [comment]
@BrunoReboul maybe I am misunderstanding the bug, but you're asking for a rule on the ancestor of a resource to apply to the resource correct? e.g. if bucket is in a project in an organization then rules set on the project or organization apply to the bucket.

If so, it is already the case: https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/forseti/scanner/audit/location_rules_engine.py#L229

The test cases use this as well: https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/tests/scanner/audit/location_rules_engine_test.py#L39

The rule is set on the organization resource, and then individual resources are set via the applies_to field.

To apply to all resources, the applies_to fields be type and resource ids can both be set to * (see test case test_find_violations_applies_all_resources).
