### ISSUE TITLE
FR - Lien scanner - enable * wildcard in project ids

### ISSUE THREAD

**Issue by BrunoReboul** [forseti-security/forseti-security#2372]
Feature Request

Scanner: lien
Request:
- enable usage of * wild card in resource_ids list

User story:
As an operation manager, I want to control that all the production projects in my organization are protected from deletion by a lien using the naming convention of project when all production projects are not below one folder in the GCP hierarchy.

Example: 
- naming convention:  production project must have a suffix '-prod'
- scanner resource_ids will be: - '*-prod'

**Comment by jjawad-google** [comment]
Hi @umairidris could you take a look?

**Comment by umairidris** [comment]
@BrunoReboul most scanners don't support wildcard with text in resource ids. It's either '*' or a non regex string.

It doesn't seem like that would be sufficient for your use case, but I wanted to confirm.

**Comment by umairidris** [comment]
Wildcard only resource id support is added in #2380.
