### ISSUE TITLE
Setup a more comprehensive test environment

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#242]
Customer issues like #241 are being reported, that would have been caught if we have a more better domain for testing.  "better" means more realistic, more production-like, especially in size.  This would allow us to uncover bugs or code executions that would only happen at scale, which our current test/dev domains do not allow us to do.

**Comment by carise** [comment]
I think it makes sense to track this internally. Closing it.

**Comment by carise** [comment]
To clarify, we have a domain that we can use. @blueandgold

**Comment by carise** [comment]
We would also need this domain to be standalone, i.e. no reusing test domains internally.

**Comment by mirons-google** [comment]
This is related to #280
