### ISSUE TITLE
Verify Installation Is Really Completed (was 2.9.0 Installation failure)

### ISSUE THREAD

**Issue by zachberger** [forseti-security/forseti-security#2421]
I was doing a fresh installation of Forseti 2.9.0 in an organization where I am org admin. After the installation completed, when I went to run `forseti inventory create` I get the following.

```
zberger_scefast_com@forseti-client-vm-9d85e7f:~$ forseti inventory create
Error communicating to the Forseti server.
Please check the status of the server and make sure it's running.
If you are accessing from a client VM, make sure the `server_ip` field inside the client configuration file in the Forseti client GCS bucket contains the right IP address.
```

I validated the client configuration file and it contains the following:

```yaml
server_ip: 10.128.0.2
```

which is the server's IP address:

![vms](https://user-images.githubusercontent.com/1634878/50119068-6fc8ca00-0206-11e9-941e-343f67db7e0a.png)

I've attached the deployment.log files from both the client and the server, but nothing stands out there:
[client-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688027/client-deployment.log)
[server-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688028/server-deployment.log)

The server service is in fact running:
```
zberger@forseti-server-vm-9d85e7f:~$ sudo systemctl status forseti
● forseti.service - Forseti API Server
   Loaded: loaded (/lib/systemd/system/forseti.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-12-17 21:54:06 UTC; 25min ago
 Main PID: 12165 (forseti_server)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/forseti.service
           └─12165 /usr/bin/python /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql://root@12

Dec 17 21:54:06 forseti-server-vm-9d85e7f systemd[1]: Started Forseti API Server.
```

And is listening on port 50051:
```
zberger@forseti-server-vm-9d85e7f:~$ sudo lsof -iTCP | grep 50051
forseti_s 12165          ubuntu   58u  IPv6  39589      0t0  TCP *:50051 (LISTEN)
forseti_s 12165          ubuntu  112u  IPv6  49035      0t0  TCP ip6-localhost:35850->ip6-localhost:50051 (ESTABLIS
HED)
forseti_s 12165          ubuntu  113u  IPv6  49816      0t0  TCP ip6-localhost:50051->ip6-localhost:35850 (ESTABLIS
HED)
```

And I can establish a connection to 50051:
```
zberger_scefast_com@forseti-client-vm-9d85e7f:~$ telnet 10.128.0.2 50051
Trying 10.128.0.2...
Connected to 10.128.0.2.
```

Workaround: restarting the forseti server service allowed the client to connect. 

Here are the server runtime logs: 
[server-runtime.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688238/server-runtime.log)

**Comment by blueandgold** [comment]
Hi Zach, the server still requires a period of initialization after the installation finishes.  We used to check by ssh into the server and check the `/tmp/deployment.log`, but the ssh has stopped working recently.  So, we should work on issue #1112 to final an alternate way to verify that the server is up and running, before calling the installation complete.

**Comment by zachberger** [comment]
Thanks @blueandgold, however this persisted for hours

**Comment by nandigamchaitanya** [comment]
> sudo lsof -iTCP | grep 50051



> I was doing a fresh installation of Forseti 2.9.0 in an organization where I am org admin. After the installation completed, when I went to run `forseti inventory create` I get the following.
> 
> ```
> zberger_scefast_com@forseti-client-vm-9d85e7f:~$ forseti inventory create
> Error communicating to the Forseti server.
> Please check the status of the server and make sure it's running.
> If you are accessing from a client VM, make sure the `server_ip` field inside the client configuration file in the Forseti client GCS bucket contains the right IP address.
> ```
> I validated the client configuration file and it contains the following:
> 
> ```yaml
> server_ip: 10.128.0.2
> ```
> 
> which is the server's IP address:
> 
> ![vms](https://user-images.githubusercontent.com/1634878/50119068-6fc8ca00-0206-11e9-941e-343f67db7e0a.png)
> 
> I've attached the deployment.log files from both the client and the server, but nothing stands out there:
> [client-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688027/client-deployment.log)
> [server-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688028/server-deployment.log)
> 
> The server service is in fact running:
> 
> ```
> zberger@forseti-server-vm-9d85e7f:~$ sudo systemctl status forseti
> ● forseti.service - Forseti API Server
>    Loaded: loaded (/lib/systemd/system/forseti.service; disabled; vendor preset: enabled)
>    Active: active (running) since Mon 2018-12-17 21:54:06 UTC; 25min ago
>  Main PID: 12165 (forseti_server)
>     Tasks: 10 (limit: 4915)
>    CGroup: /system.slice/forseti.service
>            └─12165 /usr/bin/python /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql://root@12
> 
> Dec 17 21:54:06 forseti-server-vm-9d85e7f systemd[1]: Started Forseti API Server.
> ```
> And is listening on port 50051:
> 
> ```
> zberger@forseti-server-vm-9d85e7f:~$ sudo lsof -iTCP | grep 50051
> forseti_s 12165          ubuntu   58u  IPv6  39589      0t0  TCP *:50051 (LISTEN)
> forseti_s 12165          ubuntu  112u  IPv6  49035      0t0  TCP ip6-localhost:35850->ip6-localhost:50051 (ESTABLIS
> HED)
> forseti_s 12165          ubuntu  113u  IPv6  49816      0t0  TCP ip6-localhost:50051->ip6-localhost:35850 (ESTABLIS
> HED)
> ```
> And I can establish a connection to 50051:
> 
> ```
> zberger_scefast_com@forseti-client-vm-9d85e7f:~$ telnet 10.128.0.2 50051
> Trying 10.128.0.2...
> Connected to 10.128.0.2.
> ```
> Workaround: restarting the forseti server service allowed the client to connect.
> 
> Here are the server runtime logs:
> [server-runtime.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688238/server-runtime.log)

**Comment by nandigamchaitanya** [comment]
Hi can you please help me how to resolve the issue
i have configured forseti multiple times


> @blueandgold to investigate this issue in more detail and follow up.

**Comment by nandigamchaitanya** [comment]
> I was doing a fresh installation of Forseti 2.9.0 in an organization where I am org admin. After the installation completed, when I went to run `forseti inventory create` I get the following.
> 
> ```
> zberger_scefast_com@forseti-client-vm-9d85e7f:~$ forseti inventory create
> Error communicating to the Forseti server.
> Please check the status of the server and make sure it's running.
> If you are accessing from a client VM, make sure the `server_ip` field inside the client configuration file in the Forseti client GCS bucket contains the right IP address.
> ```
> I validated the client configuration file and it contains the following:
> 
> ```yaml
> server_ip: 10.128.0.2
> ```
> 
> which is the server's IP address:
> 
> ![vms](https://user-images.githubusercontent.com/1634878/50119068-6fc8ca00-0206-11e9-941e-343f67db7e0a.png)
> 
> I've attached the deployment.log files from both the client and the server, but nothing stands out there:
> [client-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688027/client-deployment.log)
> [server-deployment.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688028/server-deployment.log)
> 
> The server service is in fact running:
> 
> ```
> zberger@forseti-server-vm-9d85e7f:~$ sudo systemctl status forseti
> ● forseti.service - Forseti API Server
>    Loaded: loaded (/lib/systemd/system/forseti.service; disabled; vendor preset: enabled)
>    Active: active (running) since Mon 2018-12-17 21:54:06 UTC; 25min ago
>  Main PID: 12165 (forseti_server)
>     Tasks: 10 (limit: 4915)
>    CGroup: /system.slice/forseti.service
>            └─12165 /usr/bin/python /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql://root@12
> 
> Dec 17 21:54:06 forseti-server-vm-9d85e7f systemd[1]: Started Forseti API Server.
> ```
> And is listening on port 50051:
> 
> ```
> zberger@forseti-server-vm-9d85e7f:~$ sudo lsof -iTCP | grep 50051
> forseti_s 12165          ubuntu   58u  IPv6  39589      0t0  TCP *:50051 (LISTEN)
> forseti_s 12165          ubuntu  112u  IPv6  49035      0t0  TCP ip6-localhost:35850->ip6-localhost:50051 (ESTABLIS
> HED)
> forseti_s 12165          ubuntu  113u  IPv6  49816      0t0  TCP ip6-localhost:50051->ip6-localhost:35850 (ESTABLIS
> HED)
> ```
> And I can establish a connection to 50051:
> 
> ```
> zberger_scefast_com@forseti-client-vm-9d85e7f:~$ telnet 10.128.0.2 50051
> Trying 10.128.0.2...
> Connected to 10.128.0.2.
> ```
> Workaround: restarting the forseti server service allowed the client to connect.
> 
> Here are the server runtime logs:
> [server-runtime.log](https://github.com/GoogleCloudPlatform/forseti-security/files/2688238/server-runtime.log)

Hi may i know How this issue was resolved

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
