### ISSUE TITLE
Firewall Scanner Rule Configuration Is Missing from Website Documentation

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2452]
User reports that the [Defining Rules](https://forsetisecurity.org/docs/latest/configure/scanner/rules.html) page is missing the documentation for Firewall Scanner rule. This should be added, describing the full schema, what is optional and required, and link to the [examples here](https://github.com/GoogleCloudPlatform/forseti-security/tree/dev/samples/scanner/scanners/firewall_rules).

**Comment by jjawad-google** [comment]
#2458 Also look at FS 1.0 documentation on the website. # of sample rules included in scanner + tests that could be used to rev engineer the docs.

**Comment by Red-Five** [comment]
What is the firewall rule schema to define a check for "sourceRanges": ["0.0.0.0/0"] ?

**Comment by blueandgold** [comment]
Looks like this has been added to our website documentation.
