### ISSUE TITLE
Firewall Use Cases

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2458]
Submitted on slack:

- Ability to model internal network (corporate subnets and GCP VCPs) in one place and reference elsewhere in rules. Routable over VPN tunnels on GCP shared VPC

- Ability to model external IP of corporate egress gateways or VPC NAT gateways

- Ability to model and track other external IPs of clients/partners (reference inventory) and use in rules

- Blacklist set of ports (ssh, rdp, etc) that should not be exposed to internet (0.0.0.0/0) but in some cases may be allowed to restricted (external set) due to need to use private VPC (GKE is prime case at moment but better support of private VPC seems to be coming)

- Enforce restricted port lockdown for specific projects

- Some means to handle exceptions / overrides (whether this is implemented as hierarchy exceptions to org level policies or some other means)

**Comment by jjawad-google** [comment]
We will perform a gap analysis of this request against our current firewall scanner.
