### ISSUE TITLE
Enforcer Use Cases

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2459]
Submitted on slack:

- Enforce labels on projects or resources for cost management and ownership tracking (vuln management escalation for example). Required below project level. Capability to tattoo from one resource to all linked resources (compute to network / storage)

**Comment by jjawad-google** [comment]
Hi @antoine-castex, this would be a great contribution to the upcoming GitHub Organization that we are planning to roll out soon.
