### ISSUE TITLE
Notifier fails silently

### ISSUE THREAD

**Issue by ramshazar** [forseti-security/forseti-security#2468]
First, help us help you by providing the following information when opening an issue.

 - [v2.9] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
 - [notifier] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [x] Include errors, log output, and host operating system, including installed packages.
 - [Cloud Shell and github repository] Note how you deployed (via Deployment Manager, local system, etc.).

Hi,

Im new to Forseti Security. I tried to use the notifier with an sendgrid API key to alert me about a misconfiguration of a public bucket.
I misspelled the configuration option for the notifier which resulted an no notification. There also was no hint that something went wrong. It had not been logged to /var/log/forseti.log.

A manual run of the notifier revealed that there has been some error:
`ubuntu@forseti-server-vm-05ee292:~$ forseti notifier run --inventory_index_id 1546608364403399
{
  "serverMessage": "Retrieved 1 violations for resource 'iam_policy_violations'"
}
{
  "serverMessage": "Running 'email_violations' notifier for resource 'iam_policy_violations'"
}
{
  "serverMessage": "Error occurred during the notification process."
}
ubuntu@forseti-server-vm-05ee292:~$`

It would be helpful if the error message would be more verbose.
It would be helpful to find this error in the general Forseti Security log.
If I did this correctly it does not help to set the log_level to debug.

Steps to reproduce:
a) Install Forseti Security
b) Create a violation of a rule. I used a public bucket.
c) Misspell a configuration option of the triggered rule. I substituted "sendgrid_api_key" with "ssendgrid_api_key" in the resource "iam_policy_violations".
d) Wait for the cronjob to run or run it manually.

Steps to debug:
a) cat /var/log/forseti.log
b) forseti notifier run --inventory_index_id $(mysql -s -N -u root -h 127.0.0.1 forseti_security -e 'select id from inventory_index ORDER BY id DESC LIMIT 1;')

**Comment by jjawad-google** [comment]
@ramshazar -- thank you for reporting this issue, we will investigate and plan to fix by the next release.
