### ISSUE TITLE
Forseti server can't find projects inside folders

### ISSUE THREAD

**Issue by umairidris** [forseti-security/forseti-security#2472]
The forseti server is not able to list projects inside folders on which it does not have folder viewer permissions, even though the individual projects grant the forseti server service account 'browser' permissions. Projects not in folders are found without a problem.

Is there a way to grant Forseti access to projects within a folder without granting permissions on the folder itself? Perhaps the projects list could be modified (i.e. use projects.search instead)?

/cc @dufton

**Comment by jjawad-google** [comment]
@joecheuk to investigate how folders are owned or used by users who have projects in them.

**Comment by jjawad-google** [comment]
@joecheuk to follow up with @blueandgold who can explain how this works.

**Comment by umairidris** [comment]
We were able to use composite root in our forseti server config to fix this. You may still wish to fix this bug as it seems like unexpected behaviour, but as there is a workaround this isn't a critical issue for us anymore.

**Comment by dekuhn** [comment]
@joecheuk is there still something you feel we should do by default without composite root

**Comment by dekuhn** [comment]
Composite root is the right solution for the reported issue. Closing this issue.
