### ISSUE TITLE
Enable unattended-upgrade to allow security patches to be installed automatically

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2483]
Add command

`sudo unattended-upgrade`

to the startup script.

Description of the package:

>  This package can download and install security upgrades automatically
>  and unattended, taking care to only install packages from the
>  configured APT source, and checking for dpkg prompts about
>  configuration file changes.

Relates to #2196

**Comment by Red-Five** [comment]
I see how this is valuable for the GCE deployments.

Just a comment that for docker deployments this may circumvent CI\CD controls and image security scan.
(Ideally the image would be read only though not sure we can get there yet.)
