### ISSUE TITLE
Create default scanner rules for CIS recommendations for Kubernetes Engine, and the GKE Hardening Guideline

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2511]
For the [ke_scanner_rules.yaml](https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/rules/ke_scanner_rules.yaml), we have some of the rules in place that meet the CIS recommendations, but not all (such as autoUpgrade).

In looking through the KE cluster data in inventory, and we can add additional scanner rules to meet the CIS recommendations, and leave them as examples in the [ke_scanner_rules.yaml](https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/rules/ke_scanner_rules.yaml).

GKE Hardening Guideline
https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster

**Comment by Red-Five** [comment]
CIS Benchmarks (with CIS Level 1 or 2)
7 Kubernetes Engine	
- [ ] 7.1 Ensure Stackdriver Logging is set to Enabled on Kubernetes Engine Clusters (Scored)	1
- [ ] 7.2 Ensure Stackdriver Monitoring is set to Enabled on Kubernetes Engine Clusters (Scored)	1
- [ ] 7.3 Ensure Legacy Authorization is set to Disabled on Kubernetes Engine Clusters (Scored)	1
- [ ] 7.4 Ensure Master authorized networks is set to Enabled on Kubernetes Engine Clusters (Not Scored)	1
- [ ] 7.5 Ensure Kubernetes Clusters are configured with Labels (Not Scored)	1
- [ ] 7.6 Ensure Kubernetes web UI / Dashboard is disabled (Scored)	1
- [ ] 7.7 Ensure `Automatic node repair` is enabled for Kubernetes Clusters (Scored)	1
- [ ] 7.8 Ensure Automatic node upgrades is enabled on Kubernetes Engine Clusters nodes (Scored)	1
- [ ] 7.9 Ensure Container-Optimized OS (cos) is used for Kubernetes Engine Clusters Node image (Not Scored)	2
- [ ] 7.10 Ensure Basic Authentication is disabled on Kubernetes Engine Clusters (Scored)	1
- [ ] 7.11 Ensure Network policy is enabled on Kubernetes Engine Clusters (Scored)	1
- [ ] 7.12 Ensure Kubernetes Cluster is created with Client Certificate enabled (Scored)	1
- [ ] 7.13 Ensure Kubernetes Cluster is created with Alias IP ranges enabled (Scored)	1
- [ ] 7.14 Ensure PodSecurityPolicy controller is enabled on the Kubernetes Engine Clusters (Scored)	1
- [ ] 7.15 Ensure Kubernetes Cluster is created with Private cluster enabled (Scored)	1
- [ ] 7.16 Ensure Private Google Access is set on Kubernetes Engine Cluster Subnets (Scored)	1
- [ ] 7.17 Ensure default Service account is not used for Project access in Kubernetes Clusters (Scored)	2
- [ ] 7.18 Ensure Kubernetes Clusters created with limited service account Access scopes for Project access (Scored)	1

**Comment by Red-Five** [comment]
Below info may assist with identifying the fields to be inspected by each rule.
Data referenced from CIS Benchmarks for GCP document under Creative Commons Public License.

7 Kubernetes Engine |  
-- | --
7.1 Ensure Stackdriver Logging is set to Enabled on Kubernetes Engine Clusters (Scored) | To check logging status for an existing cluster, run the following command, gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.loggingService'The output should return logging.googleapis.com if logging is Enabled.
7.2 Ensure Stackdriver Monitoring is set to Enabled on Kubernetes Engine Clusters (Scored) | To check monitoring status for an existing cluster, run the following command, gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.monitoringService' The output should return monitoring.googleapis.com if monitoring is Enabled.
7.3 Ensure Legacy Authorization is set to Disabled on Kubernetes Engine Clusters (Scored) | To check Legacy Authorization status for an existing cluster, run the following command: gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.legacyAbac'The output should return null set({}) if Legacy Authorization is Disabled. If Legacy Authorization is enabled above command will return true value set to Enabled.
7.4 Ensure Master authorized networks is set to Enabled on Kubernetes Engine Clusters (Not Scored) | To check Master authorized networks status for an existing cluster, run the following command, gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.masterAuthorizedNetworksConfig'The output should return "enabled": true in set if Master authorized networks is Enabled. If Master authorized networks disabled above command will return null set.
7.5 Ensure Kubernetes Clusters are configured with Labels (Not Scored) | To check for the existence of Labels for an existing cluster, run the following command, gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.resourceLabels'The output should return Key and value pairs in set if Labels are configured. If Labels are not configured above command will return null set.
7.6 Ensure Kubernetes web UI / Dashboard is disabled (Scored) | gcloud container clusters describe [CLUSTER_NAME] --zone [ZONE] --format json \| jq '.addonsConfig.kubernetesDashboard'Ensure the output of the above command has JSON key attribute disabled set to true { "disabled": true }
7.7 Ensure `Automatic node repair` is enabled for Kubernetes Clusters (Scored) | gcloud container node-pools describe default-pool --cluster timos-cluster --zone us-central1-a --format json \| jq '.management'Ensure the output of the above command has JSON key attribute autoRepair set to true { "autoRepair": true }
7.8 Ensure Automatic node upgrades is enabled on Kubernetes Engine Clusters nodes (Scored) | To check existence of Automatic node upgrades for an existing cluster's node pool, run the following command, $ gcloud container node-pools describe [NODE_POOL] --cluster [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.management'168 \| P a g eEnsure the output of the above command has JSON key attribute autoUpgrade set to true { "autoUpgrade": true }If autoUpgrade is disabled above command output will not contain the autoUpgrade entry.
7.9 Ensure Container-Optimized OS (cos) is used for Kubernetes Engine Clusters Node image (Not Scored) | To check Node image type for an existing cluster nodes, run the following command: $ gcloud container node-pools describe [NODE_POOL] --cluster [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.config.imageType'The output of the above command returns COS, if Container-Optimized OS (cos) used for Node images.
7.10 Ensure Basic Authentication is disabled on Kubernetes Engine Clusters (Scored) | To check Basic authentication status for an existing cluster nodes, run the following command: gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.masterAuth.password and .masterAuth.username' The output of the above command should return false, if Basic authentication is disabled. If Basic authentication is enabled above command will return true.
7.11 Ensure Network policy is enabled on Kubernetes Engine Clusters (Scored) | To check Network policy is enabled for an existing cluster, run the following command, gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.networkPolicy'Ensure the output of the above command has JSON key attribute enabled set to true { "enabled": true }
7.12 Ensure Kubernetes Cluster is created with Client Certificate enabled (Scored) | To check Client certificate is enabled for an existing cluster, run the following command, gcloud container clusters describe change-acc-group-test-cluster --zone us-central1-a --format json \| jq '.masterAuth.clientKey'Ensure the output of the above command should not return null or empty value.
7.13 Ensure Kubernetes Cluster is created with Alias IP ranges enabled (Scored) | To check Alias IP is enabled for an existing cluster, run the following command: gcloud container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.ipAllocationPolicy.useIpAliases'The output of the above command should return true, if VPC native (using alias IP) isenabled. If VPC native (using alias IP) is disabled above command will return null.
7.14 Ensure PodSecurityPolicy controller is enabled on the Kubernetes Engine Clusters (Scored) | To check Pod Security Policy is enabled for an existing cluster, run the following command, gcloud beta container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.podSecurityPolicyConfig'Ensure the output of the above command has JSON key attribute enabled set to true { "enabled": true }If Pod Security Policy is disabled above command output will return null set.
7.15 Ensure Kubernetes Cluster is created with Private cluster enabled (Scored) | To check Private cluster is enabled for an existing cluster, run the following command, gcloud beta container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.privateCluster'The output of the above command should return true, if the Private cluster is enabled. If the Private cluster is disabled above command will return null.
7.16 Ensure Private Google Access is set on Kubernetes Engine Cluster Subnets (Scored) | To get subnet name of the Cluster, run the following command: gcloud beta container clusters describe [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.subnetwork'The command will return you subnet name. Note down the subnet name and mention the same name at following command which will check Private Google access status, run the following command: gcloud compute networks subnets describe [SUBNET_NAME] --region [REGION] --format json \| jq '.privateIpGoogleAccess'The output of the above command returns true, if Private Google access is set on Cluster subnetwork. If Private Google access is set to Off above command will return false.
7.17 Ensure default Service account is not used for Project access in Kubernetes Clusters (Scored) | To check which Service account is set for an existing cluster, run the following command: $ gcloud container node-pools describe [NODE_POOL] --cluster [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.config.serviceAccount'The output of the above command will return default if default Service account is used for Project access.
7.18 Ensure Kubernetes Clusters created with limited service account Access scopes for Project access (Scored) | To check Access scopes set for an existing cluster, run the following command: gcloud container node-pools describe [NODE_NAME] --cluster [CLUSTER_NAME] --zone [COMPUTE_ZONE] --format json \| jq '.config.oauthScopes'The output of the above command will return array set access scopes. Make sure you have provided limited required scopes for each node clusters. If you are accessing private images in Google Container Registry, the minimally required scopes are only logging.write, monitoring, and devstorage.read_only.

**Comment by Red-Five** [comment]
https://github.com/GoogleCloudPlatform/forseti-security/pull/2659

@blueandgold  Please could you arrange for a peer review?

**Comment by kbroughton** [comment]
Looking forward to these landing.  One small note: 7.12 recommendation to use client certs has been reversed on the official documentation. It seems the latest guidance from the cluster creation page is to only access with IAM credentials because certs are hard to revoke and don't auto-rotate.

Best is to use apparently IAM access.
It seems the latest guidance from the cluster creation page is to only access with IAM credentials because certs are hard to revoke and don't auto-rotate.

This correction has been accepted by reviewers of the Draft CIS GCP 1.1 version.

**Comment by gkowalski-google** [comment]
The Kubernetes policies have been ported to the Policy Library, and the sample K8s policies have the CIS annotations. Example: https://github.com/forseti-security/policy-library/blob/master/samples/gke_dashboard_disable.yaml.
