### ISSUE TITLE
Google Deployment Manager in region other than US

### ISSUE THREAD

**Issue by mmaningab** [forseti-security/forseti-security#2515]
Feature request

Version 2.9
Google Deployment package
No error logs, Sever are always deployed in the US
Deployed Deployment Manager.

Hi,

We would like to see options to change the Region in which Forseti is deployed, currently it only deploys to the US we would like to be able to deploy to the EU and other Regions.

Thanks
Maurice

**Comment by blueandgold** [comment]
Great suggestion.  We will add this appropriately to our upcoming work schedule.

**Comment by ryanismert** [comment]
@blueandgold can scope this so that we can see about scheduling?

**Comment by gkowalski-google** [comment]
Hi @mmaningab, I apologize for not getting back to you sooner. Forseti now supports installation through [Terraform](https://registry.terraform.io/modules/terraform-google-modules/forseti/google/1.4.0) and many of these types of options are now available for you to customize, including the region. Please let me know if you have any questions or if we can close this out.

**Comment by gkowalski-google** [comment]
@mmaningab we have not heard back from you in 2 weeks, and this is an old issue. Closing the issue for now. Please reopen and if this is still valid and you need assistance.
Thanks!
