### ISSUE TITLE
Feature Request: Create an Official DockerHub Repo for Forseti Docker Images

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2520]
Consider setting up an 'official' Forseti Security docker image repo on DockerHub and arrange for the images to be 'Docker certified'.

Possibly a sub folder here? https://hub.docker.com/u/google

This will eliminate the need for users to create and store their own Forseti docker images.

**Comment by dekuhn** [comment]
Thanks for creating an issue. Was actually exploring this yesterday for real-time-enforcer.

**Comment by Abdennebi** [comment]
Does it make sense to also create a [cloud builde](https://github.com/GoogleCloudPlatform/cloud-builders)r?

**Comment by Red-Five** [comment]
@Abdennebi Salut

Ref. https://github.com/forseti-security/forseti-security/blob/dev/install/docker/cloudbuild.yaml

could be modified to push to DockerHub

**Comment by dekuhn** [comment]
I have setup a Docker Hub org now that is building real-time-enforcer  https://hub.docker.com/r/forsetisecurity.

Currently docker hub is configured to build new containers on tagged releases.

**Comment by dekuhn** [comment]
As we work on #2084 we can use docker hub as the source.
