### ISSUE TITLE
Feature request: option to install in read-only mode

### ISSUE THREAD

**Issue by imtheoperator** [forseti-security/forseti-security#2576]
Possibly related to #2471 , I need to install Forseti in an organisation which already has many production projects but few folders - without risk of the enforcer impacting existing projects.

By default, Forseti has a lot of privileges, so I would like to be able to install Forseti in read-only mode, so that there is no chance of enforcing a policy that may affect an existing project. This would just run in inventory/scanner mode (and maybe explainer?).

This would mean the _enforcer_ could not enforce a policy, until the config is reloaded with a read-write config.

**Comment by joecheuk** [comment]
Hey @ahoying , can you scope and schedule this?

**Comment by ahoying** [comment]
The installer supports read only mode, but enable write is hard coded as True here: https://github.com/GoogleCloudPlatform/forseti-security/blob/56057f63fcb1040cc6ba121b50ebf3c0d95e9386/install/gcp/installer/forseti_server_installer.py#L35.

The installer needs to have a flag that modifies that value.

**Comment by janmasarik** [comment]
Is there any way to do read-only mode now when https://github.com/forseti-security/forseti-security/pull/3273 got merged @ahoying / @gkowalski-google? 🙏  

We use terraform for everything, so having org write admin there would be useless for us.

**Comment by dekuhn** [comment]
This feature is supported in the terraform installer and we no longer support the python installer method.. Closing as obsolete. 

Please re-open if have additional questions or concerns.
