### ISSUE TITLE
Feature Request : Detect HMAC authentication (Interoperability API) on bucket

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [forseti-security/forseti-security#2579]
Hello,
In some use case we have to use HMAC authentication on GCS bucket (Interoperability API). I have a case with a CDN we want to place in front of a GCS bucket for distributing content.
The problem come that this API is enabled per project member, not per project.
So let me imagine the worst case : an org admin use his personnal account to configure the HMAC authentication on GCS bucket... so all organizations bucket are accessible with this authentication.
I think in can be very useful to be able to detect it with forsety.
Please tell me if it's enough clear or if i can help
thanks in advance

**Comment by gkowalski-google** [comment]
Please follow up and provide some instructions for how this can be done with Config Validator.

**Comment by jf-marquis-Adeo** [comment]
Hi Guys
config validator is not sufficient because everything is not going through Teraform ;-)
This HMAC option is really a big security hole
