### ISSUE TITLE
Support broader Forwarding Rule matches for load balancer scheme matches

### ISSUE THREAD

**Issue by julianvmodesto** [forseti-security/forseti-security#2593]
As of Forseti 2.11, the forwarding rule scanner must match on load balancer scheme (e.g. internal or external), IP and protocol for a rule match.

https://forsetisecurity.org/docs/v2.11/develop/reference/_modules/google/cloud/forseti/scanner/audit/forwarding_rule_rules_engine.html#Rule.find_match

However, it would be great to be able to create a rule to whitelist all forwarding rules with an `INTERNAL` load balancing scheme i.e. whitelist all internal load balancers, and thus create rule violations for all external load balancers.

One way to broaden the forwarding rule matcher is to simply allow rule matches for load balancer scheme-only matches, which would satisfy this use case.

**Comment by hshin-g** [comment]
@joecheuk Is this something that can be addressed by Config Validator?

**Comment by gkowalski-google** [comment]
@julianvmodesto Hello, please consider using [this Config Validator template to whitelist Load Balancer forwarding rules](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_lb_forwarding_rules_whitelist.yaml).
