### ISSUE TITLE
Allow users to choose a bigger cloud sql instance/VM

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2599]
We should add manual steps to the installation guide to document the steps for users to increase the size of the cloud sql instance / VM.

We can also include a flag to the installer to allow user to increase the size during the installation.

**Comment by blueandgold** [comment]
relates to #2591 

@hshin-g, now that we have terraform, are things like size or disk types easier to do by flag or by configuration?

**Comment by hshin-g** [comment]
You can change the size/disk types through the configuration in terraform.

**Comment by joecheuk** [comment]
Verified it's part of the TF variables. Would be nice to have some documentation around that as TF has many variables.
