### ISSUE TITLE
Forseti installer should set composite root by default

### ISSUE THREAD

**Issue by umairidris** [forseti-security/forseti-security#2614]
A composite root has the functionality of a single root but allows for additional roots if needed. There is not much use of a single root anymore, thus I propose setting a composite root id by default and deprecating root_resource_id.

```
root_resource_id: {ROOT_RESOURCE_ID}

# can be converted to
composite_root_resources:
- {ROOT_RESOURCE_ID}
```

Optional:
Long term replacing both root_resource_id and composite_root_resources with "root_resources" may be the cleanest syntax.

cc @frozen425

**Comment by red2k18** [comment]
@ahoying Should we set composite root by default?

**Comment by dekuhn** [comment]
Need to investigate if this would break explain feature if so more work is required to address this request.

**Comment by dekuhn** [comment]
@joecheuk you are the expert on composite root; is this still applicable with our migration to Terraform installation?

**Comment by umairidris** [comment]
This can be skipped in the terraform module if desired (though IMO this field should be deprecated/removed entirely there too). If the python installer is deprecated feel free to close it here.

**Comment by dekuhn** [comment]
@joecheuk you are the expert on composite root; is this still applicable with our migration to Terraform installation?

**Comment by joecheuk** [comment]
This is still applicable, though we need to make sure the other issues are addressed  before doing that: https://github.com/forseti-security/terraform-google-forseti/issues/375

The roles don't seem to be assigned properly when composite roots field is used.
