### ISSUE TITLE
Inventory creation time ranges from 4 to 6 hours or even longer in some cases. Please investigate with the CAI team. This issue was reported by many customers after upgrading to v2.1.2.0.

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#2621]
Please investigate with the CAI team. This issue was reported by many customers after upgrading to v2.1.2.0.

**Comment by red2k18** [comment]
Please investigate with the CAI team. This issue was reported by many customers after upgrading to v2.1.2.0.

**Comment by dekuhn** [comment]
Marking as duplicate of: https://github.com/forseti-security/forseti-security/issues/2676
