### ISSUE TITLE
Server Config File Scanner rules_path 

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2625]
Re server config file

scanner rules_path defaults to /home/ubuntu/forseti-security/rules

On k8s/docker it needs to be changed to /forseti-security/rules

According to the comments in config file it seems it can also reference gs://[bucket]/rules
Perhaps that would be a better default as it works for both VM approach and docker approach?

If gs:// format used, then assume we would not need to download the rules files locally at the start of each scan?

**Comment by kevensen** [comment]
By default, I believe this should point to rules in GCS.  Thoughts?

I'll open a PR today.

**Comment by kevensen** [comment]
It is possible to address this in the Helm charts.  I am working to fix it there and have opened a new issue in that repository.
