### ISSUE TITLE
Update Forseti Documentation to update Location Scanner Supported Types

### ISSUE THREAD

**Issue by garrettwong** [forseti-security/forseti-security#2643]
Forseti Security [v2.13] [Scanner] 

Update documentation for Scanner **"Location rules"** https://forsetisecurity.org/docs/latest/configure/scanner/rules.html

Document should be updated to reflect that location scanner supports more than just "bucket".  

The code supports additional (SUPPORTED_LOCATION_RESOURCE_TYPES) types:
https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/forseti/scanner/audit/location_rules_engine.py

**Comment by red2k18** [comment]
#2751
