### ISSUE TITLE
Investigate Big Query Dataset With No Tables Breaks Inventory Collection

### ISSUE THREAD

**Issue by osandoval011** [forseti-security/forseti-security#2655]
Investigate Big Query Dataset With No Tables Breaks Inventory Collection.

**Comment by dekuhn** [comment]
@osandoval011 can you either answer the template or remove it. Is this a scanner module issue? The description sounds like inventory? 

Please add any other details that will help the engineer who gets assigned to this work. Also sas this a customer reported issue or something you discovered yourself?

**Comment by dekuhn** [comment]
Sizing this to 1 day for investigation

**Comment by blueandgold** [comment]
I am unable to reproduce the problem.

How this was tested:

1. Created a new dataset in an existing project.
2. No table is created in the new dataset.
3. Built a new inventory.
4. Inventory completed successfully.  Dataset data looks like the following.
```
{"datasetReference": {"datasetId": "henrytest123", "projectId": "release-2-18-0"}, "id": "release-2-18-0:henrytest123", "kind": "bigquery#dataset", "location": "US"}
```
5. Built a new model using this inventory.
6. Dataset data look like the following. 
```
{"datasetReference": {"datasetId": "henrytest123", "projectId": "release-2-18-0"}, "id": "release-2-18-0:henrytest123", "kind": "bigquery#dataset", "location": "US"}
```

Closing this as problem can not be reproduced.  If there's any new information or comment, please re-open.
