### ISSUE TITLE
Feature Request: Allow Firewall Scanner to match or verify policies by logConfig field

### ISSUE THREAD

**Issue by Limezest** [forseti-security/forseti-security#2675]
**Version:** 2.12.0  
**Module:** Scanner

Hello!
I couldn't find a way for Firewall Scanner to match or verify rules based on the [logConfig field](https://cloud.google.com/compute/docs/reference/rest/v1/firewalls#Firewall.FIELDS.log_config).  
I also saw that Enforcer supports enabling logging now.

An example use case would be to ensure all "allow ssh" rules are logged for instance.

What do you think?

**Comment by joecheuk** [comment]
Hi @Limezest , thanks for opening the issue, we current might not have bandwidth to work on this but we are more than happy to work with you to get this feature in if this is something you are interested in doing!
