### ISSUE TITLE
Inventory Takes Long Time to Complete: O(day)

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2676]
We are getting reports that the Inventory process is taking 18 to 28 hours to complete (v2.12, v2.13). Although slow, it does complete.  We are currently investigating what is the cause.

**Comment by Red-Five** [comment]
Ref. https://github.com/uber/pyflame
is a light weight profiler that could be installed on the production VM with no modifications needed to server. It states it fully supports multi threading.

(I have not used it myself.)

Other options discussed here https://rivolaks.com/posts/profiling-python/

**Comment by blueandgold** [comment]
@Red-Five thanks for the pyflame pointer!  Here are the instructions we have for running pyflame.

```
1. Log in to the Forseti server in two console windows.
2. Download and install PyFlame
3. Find the PID of the running forseti server ( i.e. $ ps ax|grep forseti_server|grep python|awk '{print $1}' )
4. Run pyflame pointed to the PID of the forseti server for a couple of minutes: $ src/pyflame -p <PID_FROM_ABOVE> --threads -s <SECONDS_TO_CAPTURE> -o /tmp/forseti-flame.dump ( i.e. src/pyflame -p 15993 --threads -s 120 -o /tmp/forseti-flame.dump)
5. With pyflame running, in the second window run forseti inventory create (or whatever you are wanting to profile).
6. Log into your engineering workstation
7. When the pyflame returns, download the dump file to your local system with gcloud: gcloud compute scp --project <FORSETI_PROJECT> <FORSETI_SERVER_INSTANCE>:/tmp/forseti-flame.dump .
8. Download flamegraph.pl
9. Run FlameGraph/flamegraph.pl forseti-flame.dump > forseti.svg
10. Open forseti.svg in Chrome to interact with the graph.
```

**Comment by dekuhn** [comment]
Any update on this P0 issue? What is needed here to move this to resolution.

**Comment by blueandgold** [comment]
No update, as customer did not try this yet.  Asked @joecheuk to follow this up with another customer that he is helping.

**Comment by dekuhn** [comment]
Marking issue blocked. We do not have any profiling data to assist in diagnosing this issue.

**Comment by dekuhn** [comment]
Downgrading the priority to P1. @ryanismert  will follow-up with a few customers to see if we can get some engagement on profiling code to assist in debugging the issue.

**Comment by dekuhn** [comment]
Please add this back to 1 - Planning once we have actionable feedback and work we can do on this issue.

**Comment by dekuhn** [comment]
@joecheuk have you been able to get any customer data to help us understand where the problem is happening.

**Comment by Red-Five** [comment]
Now that we have migrated to Python3, we can consider including Stackdriver Profiling code in the standard codebase (with a flag to turn it on/off). 

https://cloud.google.com/profiler/docs/profiling-python

**Comment by red2k18** [comment]
Will add flag to #2317. Thanks @Red-Five for the suggestion.

**Comment by hshin-g** [comment]
@joecheuk to write separate issue detailing technical challenges related to this.

**Comment by sanjogpandasp** [comment]
+1 to this issue. Same here. Inventory creation is not stuck (as i tail -f on the logs) but it just keep creating in slow pace. I am running it on 25 GCP projects and have multiple huge bigquery resources in some of the projects.

**Comment by gkowalski-google** [comment]
Hi @sanjogpandasp, thanks for letting us know. Do you know how many resources are in the inventory? If you can provide any breakdown on the types of resources that would be helpful too. We have been working on this issue and are testing some changes that appear to be drastically improving the inventory time; the test org we are testing with has 2 million resources. Our hope is to include these improvements in one of the releases in the next month, but still have more testing to do. We will be sure to keep this thread updated.

**Comment by sanjogpandasp** [comment]
> Hi @sanjogpandasp, thanks for letting us know. Do you know how many resources are in the inventory? If you can provide any breakdown on the types of resources that would be helpful too. We have been working on this issue and are testing some changes that appear to be drastically improving the inventory time; the test org we are testing with has 2 million resources. Our hope is to include these improvements in one of the releases in the next month, but still have more testing to do. We will be sure to keep this thread updated.

I am currently scanning 25 projects in the Organization and the total assets number is **301967**

Let me know if you want the breakdown of those, or the number is enough. Just to let you know...I was looking into the logs and it generally takes time while going through the bigquery datasets, rest of the assets is really fast.

**Comment by sanjogpandasp** [comment]
> FYI: @ryanismert
> 
> @sanjogpandasp We have made some significant improvements to address this problem I highlight a few below.
> 
> FYI: We are tracking our efforts in the GitHub project [Forseti Inventory Performance](https://github.com/forseti-security/forseti-security/projects/9)
> 
> The first issue below here once in a public release will speed up the collection of BigQuery resources. The other improvements will address the the processing of the large number of items into the Cloud SQL inventory database.
> 
> 1. We are enabling BigQuery resources through CAI
> 
> * Implement BigQuery CAI GA Resources in Forseti Inventory #3035
> 
> 1. We made significant changes in how we process and import the CAI and other inventory data into our database. These changes have shown over 100X improvement in processing time building the inventory database.
> 
> * Refactored inventory to remove global write lock on database. #3050
> * Add autocommit and retry to read only sql sessions for CAI temp table. #2672
> * Stream CloudAsset data straight to sqlite database. #3027
> * Speed up import of cloudasset data into temporary sql table. #3019

I have installed forseti using terraform. Is an upgrade already available or should I wait for some more time?

**Comment by sanjogpandasp** [comment]
> Hi @sanjogpandasp ,
> 
> We have the release candidate build ready that should drastically improved the time it takes to do the inventory.
> 
> Can you follow the following steps to upgrade your forseti?
> 
> Specify the forseti_version and version in main.tf to forseti-inventory-optimization-rc and 4.0.1, i.e.
> 
> ```
> module "forseti" {
>   ...
>   version = "4.0.1"
>   forseti_version = forseti-inventory-optimization-rc
>   ...
> }
> ```
> 
> Then you can do `terraform init` and `terraform apply`.
> 
> Let us know if you have any problem setting it up.

I cannot really find the terraform files (any .tf files) in my forseti server. Do I have to git clone again ?

**Comment by hshin-g** [comment]
@sanjogpandasp Where did you originally run the Terraform deployment from? You should have a `main.tf` somewhere (perhaps on your local?) where you ran `terraform init` and `terraform apply`, and that is where you would make the changes- they would not be in the Server VM.

**Comment by hshin-g** [comment]
@sanjogpandasp Were you able to upgrade to the release candidate build?

**Comment by sanjogpandasp** [comment]
@hshin-g 
while doing this upgrade I wanted to change the cloudsql disk size to "50"
While changing cloudsql_disk_size in terraform main.tf and terraform.tfvars it gave error. 

I believe `cloudsql_disk_size` keyword is not present is terraform version 4.0.1 and hence it is giving error while doing terraform init.

**Comment by hshin-g** [comment]
@sanjogpandasp You're correct that the `cloudsql_disk_size` keyword is not present in Terraform v4.0.1. We are planning on adding this variable in our upcoming release (4.2.0 - early next week), with a new CloudSQL submodule.

Let us know if you have any questions here, and whether you would like to proceed with changing the `cloudsql_disk_size` for the next release or using the current version.

**Comment by katze120** [comment]
will `version = "4.2.0"` and `forseti_version = forseti-inventory-optimization-rc` work together?

**Comment by sanjogpandasp** [comment]
> @sanjogpandasp Where did you originally run the Terraform deployment from? You should have a `main.tf` somewhere (perhaps on your local?) where you ran `terraform init` and `terraform apply`, and that is where you would make the changes- they would not be in the Server VM.

I was able to deploy the CAI optimisation branch and i gave a very good performance improvement. The inventory collection and scanninng takes around 1.5 hour now, which (as compared to 10-12 hours) is nice. 

Thanks for help. This solves the issue.

**Comment by joecheuk** [comment]
@sanjogpandasp Thanks for the feedback, we will be including the changes in the release this week. I will go ahead and close the issue for now, feel free to open a new issue if you see more performance issue!
