### ISSUE TITLE
Improve documentation around external_project_access_scanner

### ISSUE THREAD

**Issue by nbards** [forseti-security/forseti-security#2677]
Since the external project access scanner is meant to be run manually, and the current docs specify how to do that, but that's not the full process.  Inventory, model, and notifier all also need to be run manually.  A slightly richer example would be very helpful.

even if just something like this:
```
export INV=`date +Y-%m-%d-%s`
forseti inventory create --import_as ${INV}
forseti model use ${INV}
forseti scanner run --scanner external_project_access_scanner
forseti notifier run --scanner_index_id <scanner index id>
```

i suspect that switching the output from json to text would allow some simple shell work to capture the scanner index id and let the whole thing be a single cut-n-paste, which i'd verify and provide if my instance wasn't in the middle of running the external project access scanner :)

**Comment by red2k18** [comment]
#2755 resolves this.
