### ISSUE TITLE
Update forsetisecurity.org-dev travis website build to include output for external contributors

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2697]
This will fail due to the long execution time with no output:
https://github.com/GoogleCloudPlatform/forseti-security/blob/9d827ea8b40da51941a1ebcbd8456dd83c4fb899/.travis.yml#L22

The way we output information during the build is defined here for the secured build:
https://github.com/GoogleCloudPlatform/forseti-security/blob/9d827ea8b40da51941a1ebcbd8456dd83c4fb899/travis/jekyll_build.sh#L22

**Comment by mirons-google** [comment]
Keep in mind how this works and the reasons it works this way for forks.

https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
https://docs.travis-ci.com/user/best-practices-security/#recommendations-on-how-to-avoid-leaking-secrets-to-build-logs

**Comment by dekuhn** [comment]
This requires core forseti team to merge as admin. Let us look at this issue when we decouple the website from dev repo.

**Comment by blueandgold** [comment]
External contributors used to get see output about build failures due to unable to decrypt secrets: #1913

**Comment by dekuhn** [comment]
I have tested this and external contributors are no longer getting the errors on the PR builds for the website. However the website build is timing out with no screen output.

To address this issue #3086 will add the travis_wait command to resolve the timeout issue.
