### ISSUE TITLE
Remove Google Cloud SDK Root Dependency in base

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#2700]
Update Google Cloud SDK install so that root is not required to use it in Docker/GKE deployment

Ref. https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

https://github.com/GoogleCloudPlatform/forseti-security/blob/d9fe8e4883976e8ff3d14ec4e9c1e44e71492592/install/docker/base#L27

https://github.com/GoogleCloudPlatform/forseti-security/blob/d9fe8e4883976e8ff3d14ec4e9c1e44e71492592/install/scripts/forseti.server.template.yaml#L45

https://github.com/GoogleCloudPlatform/forseti-security/blob/d9fe8e4883976e8ff3d14ec4e9c1e44e71492592/install/scripts/forseti.cronjob.template.yaml#L38

https://github.com/GoogleCloudPlatform/forseti-security/blob/d9fe8e4883976e8ff3d14ec4e9c1e44e71492592/install/scripts/forseti.client.template.yaml#L40

**Comment by dekuhn** [comment]
This work aligns with some of the GKE work planned for this quarter.

**Comment by Red-Five** [comment]
This can probably be closed. 

The new Helm approach (under development by @kevensen ) externalizes configs to k8s ConfigMap and removes the need for gsutil to be installed on the image.
