### ISSUE TITLE
Research on: cloud_sql_proxy should use private IP's

### ISSUE THREAD

**Issue by marko7460** [forseti-security/forseti-security#2714]
cloud_sql_proxy should use private IP's to connect to Cloud SQL. This is a more secure way and more compliant way of connecting to database.

**Comment by red2k18** [comment]
Can this be released next week?

**Comment by hshin-g** [comment]
As per comment in #2715, closing relevant PRs until more investigation is done.

**Comment by kevensen** [comment]
Per the [cloud_sql_proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy#private-ip) docs, the ` --ip_address_types=PRIVATE` is used when a CloudSQL instance has BOTH a public and private IP.  The reason for this is without the switch, the cloud_sql_proxy will default to using the public IP.

That said, the open PR for this, https://github.com/forseti-security/terraform-google-forseti/pull/144, configures it as an either or scenario.  In this case, the `--ip_address_types=PRIVATE` flag is unnecessary, likely throwing an error.

I think https://github.com/forseti-security/terraform-google-forseti/pull/144 is a good approach.
