### ISSUE TITLE
Rollback PR #2659 and Patch to 2.14

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2716]
We are working on supporting CIS benchmarks but aren't yet able to do so at this time.

We'll accept this change in the future when that's possible.

https://github.com/GoogleCloudPlatform/forseti-security/pull/2659/files

**Comment by dekuhn** [comment]
Can we please close this issue. I will open a new issue to integrate the PR rolled back when things are ready.

**Comment by dekuhn** [comment]
I created new issue #2728 to track future integration of the PR #2659
