### ISSUE TITLE
Removed gmail from default group rule

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2725]
By default gmail addresses should not be whitelisted (from a security standpoint)

**Comment by dekuhn** [comment]
We need to make this change in the terraform repo as well for this release.
https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/rules/templates/rules/group_rules.yaml

**Comment by dekuhn** [comment]
Change was made in other repo. Closing.
