### ISSUE TITLE
Integrate ke_scanner_rules.yaml with CIS Benchmark Examples

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2728]
Before integration please validate we have required approvals to add these examples.

PR: https://github.com/GoogleCloudPlatform/forseti-security/pull/2659/files

**Comment by dekuhn** [comment]
We need to address dependency work before this can be resolved.  https://github.com/GoogleCloudPlatform/forseti-security/issues/2734 and https://github.com/GoogleCloudPlatform/forseti-security/issues/2735

**Comment by dekuhn** [comment]
This is blocking pending formal agreement / license to use CIS content.

**Comment by dekuhn** [comment]
Please validate the CIS benchmark items against the spec as part of PR review.

**Comment by dekuhn** [comment]
Sorry for the duplication of posts; Just trying to keep the PR and issues in sync.

Can we add this CIS disclaimer then we can submit.
"# This scanner has not been validated by the formal CIS certification process."

One other detail to note:
There is a comment here: https://github.com/forseti-security/forseti-security/issues/2511 about the 7.12 benchmark which likely requires a change.

Looking forward to these landing. One small note: 7.12 recommendation to use client certs has been reversed on the official documentation. It seems the latest guidance from the cluster creation page is to only access with IAM credentials because certs are hard to revoke and don't auto-rotate.
Best is to use apparently IAM access.

This correction has been accepted by reviewers of the Draft CIS GCP 1.1 version.

**Comment by gkowalski-google** [comment]
@dekuhn @blueandgold Please review and see what would we should do here. The functionality of this issue/PR has already been added to the [Terraform rule](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/rules/templates/rules/ke_scanner_rules.yaml).

**Comment by gkowalski-google** [comment]
@dekuhn Any update on this ticket? Should I move this to the v2.25.0 milestone?

**Comment by dekuhn** [comment]
Here are the to dos as I see them:

- [ ] Add CIS Disclaimer on Terraform rule file [here](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/rules/templates/rules/ke_scanner_rules.yaml): ` # This constraint has not been validated by the formal CIS certification process.`
- [ ] Determine and annoitate the proper CIS version to be specific about the CIS benchmark either CIS 1.0 or CIS 1.1
- [ ] Ensure the benchmark recommendation is still valid. I believe a number of items were removed from CIS 1.1
