### ISSUE TITLE
Silence non-fatal ERROR messages from CAI for delete pending projects during Inventory creation

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/forseti-security#2731]
Silence non-fatal ERROR messages from CAI for delete pending projects during Inventory creation, as this clutters up logging and detracts from actual fatal errors / confuses successful runs.

**Comment by osandoval011** [comment]
@blueandgold @ryanismert Do we know more or less when we plan to address this?  Seems to always come up when I'm on interrupt and I just got pinged by another customer about it

**Comment by joecheuk** [comment]
Relates #2710
