### ISSUE TITLE
Forseti should pull and build a released version of FCV instead of uploading the binary to our repos

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2733]
Forseti should pull and build a Forseti Config Validator binary from the FCV github referencing a released version instead of using the binary directly.

Current we are upload the binary to Forseti repository here:
https://github.com/GoogleCloudPlatform/forseti-security/tree/dev/external-dependencies/config-validator

**Comment by gkowalski-google** [comment]
This is a duplicate of #3248 and #3314.
