### ISSUE TITLE
Update Config Validator violation category

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2734]
## Story
All the config validator violations has violation type 'CONFIG_VALIDATOR_VIOLATION' but we should separate them on a more granular level, maybe per rule name instead since the FCV instance can contain multiple rules and the resulting violation file can be huge and hard to read for users.

## Proposed Solution
Update the violation category to be `CV_{RULE_NAME}`.

## Acceptance Criteria
- Existing findings in CSCC do not get duplicated
- New CV findings in CSCC have the new category
- [Update CV end-to-end test assertions](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-config_validator_gcs_policy.rb#L63)

**Comment by dekuhn** [comment]
Feedback from Forseti day customers raised this CSCC issue. We should prioritize this based on the customer feedback.
