### ISSUE TITLE
Silence non-fatal ERROR messages from CSCC for findings that already exists.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2737]
These are non-fatal, but we should silence it (i.e. not shown as error), just handle it as debug level.
```
HttpError: <HttpError 409 when requesting https://securitycenter.googleapis.com/v1/organizations/302681460499/sources/7460974056269853532/findings/a6f9f27a3a5f25c5ebad67271c39cc78?alt=json returned "Requested entity already exists">
```

**Comment by ocervell** [comment]
+1 for this, those are just making users anxious :)

**Comment by blueandgold** [comment]
This issue should not be closed, until the PR is actually merged.  Which will be done automatically for you when you use the keyword `fixes`.
https://help.github.com/en/articles/closing-issues-using-keywords
