### ISSUE TITLE
Missing scanner yaml file will cause every scanner not to run.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2740]
This is when location scanner yaml file is not in the GCS bucket, then scanner.py will stop.  Then have to look at the stackdriver log to find out what error happend.

**Comment by dekuhn** [comment]
@blueandgold can you provide more context the title and description seem to conflict each other. Does this stop scanning or cause all scanners to run?

**Comment by dekuhn** [comment]
What are the steps to reproduce this issue so we can determine what the right solution is here.

**Comment by ocervell** [comment]
To reproduce, just remote the location scanner yaml file, reload the server config, and run the scanners.

**Comment by gkowalski-google** [comment]
This issue has been resolved, possibly by [this recent PR](https://github.com/forseti-security/forseti-security/pull/3479/files#diff-b3ab31b8737b069d164ab56066436a0bR125). If the rules file is missing then Forseti will log an error and continue running the other scanners.
