### ISSUE TITLE
Database scheme fields are being checked even though all the database columns are present.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2741]

**Comment by hshin-g** [comment]
@blueandgold What is the result of this issue? Need more information to prioritize.

**Comment by dekuhn** [comment]
Needs more details to better understand the impact of this issue.

**Comment by gkowalski-google** [comment]
We are looking at resolving these false positives in this ticket: https://github.com/forseti-security/forseti-security/issues/3386. Right now the db migrator script runs and logs lots of errors when DB columns already exist, which should not trigger an error.
