### ISSUE TITLE
Scanner run failing on server side with NoneType has no get.

### ISSUE THREAD

**Issue by pvangara** [forseti-security/forseti-security#2754]
First, help us help you by providing the following information when opening an issue.

 - [ 2.13.0] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
 - [ scanner] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ ] Include errors, log output, and host operating system, including installed packages.
2019-04-19 21:16:27,527 INFO google.cloud.forseti.services.scanner.service(Run): Run scanner service with model: 0543daa88673a6f34fdc052478a4206f
2019-04-19 21:16:27,586 ERROR google.cloud.forseti.services.scanner.service(_run_scanner): 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/services/scanner/service.py", line 117, in _run_scanner
scanner_name)
File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 103, in run
model_description.get('source_info').get('inventory_index_id'))
AttributeError: 'NoneType' object has no attribute 'get'

 - [ ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).
Deployed as a container.

We are having the above issue in our prod env. Need help!

Thanks,
Ranga.

**Comment by Red-Five** [comment]
Are you seeing this issue with the scheduled cronjob or a manual scan?

Are you able to try a manual scan? Some things to try...

forseti inventory list
/# Any errors?

forseti model list
/# Any Errors?

/# Purge inventory older than 0 days (all) CAUTION ONLY IF YOU DON'T NEED OLD INVENTORY
forseti inventory purge 0

/# Create new inventory and load into new ad hoc model
/# Model name can be anything, randomly using “model_adhoc” here
forseti inventory create --import_as model_adhoc

/# Use the model for subsequent violations scan
forseti model use model_adhoc
forseti scanner run

/# Notify violation results (to GCS bucket, CSCC and/or via email etc)
forseti notifier run

/# Remove the “model_adhoc” when done with it.
forseti model delete model_adhoc

**Comment by abhishekupadhyaya** [comment]
We ran the code from 2.14.1 release branch and followed the above instructions. However, we are still getting the same error:
`File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.1-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 103, in run
model_description.get('source_info').get('inventory_index_id'))
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by pvangara** [comment]
select name,description from model;
+-------------+-------------+
| name        | description |
+-------------+-------------+
| model_adhoc | {}          |
+-------------+-------------+
1 row in set (0.00 sec)


I wonder.... if this is the issue, where when the model is created, the description is not needed with source_info and hence get is returning a None.

**Comment by pvangara** [comment]
Model Create failing 

ERROR google.cloud.forseti.services.model.importer.importer(_flush_session): Unexpected SQLAlchemyError occurred during model creation.
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.1-py2.7.egg/google/cloud/forseti/services/model/importer/importer.py", line 216, in _flush_session
self.session.flush()
...
...
OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')

**Comment by pvangara** [comment]
Because of which 
importer.py... 

description = {
                    'source': 'inventory',
                    'source_info': {
                        'inventory_index_id': inventory.inventory_index.id},
                    'source_root': self._type_name(root),
                    'pristine': True,
                    'gsuite_enabled': inventory.type_exists(
                        ['gsuite_group', 'gsuite_user'])
                }
                LOGGER.debug('Model description: %s', description)
                self.model.add_description(json.dumps(description,
                                                      sort_keys=True)

...
may not be getting committed.

Appreciate any help on this.
Thanks,
Ranga.

**Comment by Red-Five** [comment]
Is the DB turned on and connected? Sorry for the dumb questions but they have to be asked lol.

Can u confirm you have connectivity from the container (independent of Forseti) to the MySQL instance?

**Comment by pvangara** [comment]
yes.. in fact it continued writing afterwards also...

**Comment by pvangara** [comment]
What's the max number of accounts it was tested against? Is it tested with 300-400 projects?
Thanks,
Ranga.

**Comment by pvangara** [comment]
It creates inventory, and all. It consistently fails while creating the model. Same place during flush call.

**Comment by pvangara** [comment]
After we bumped up the DB instance class on AWS, this issue went away. Closing the issue.
