### ISSUE TITLE
Discussion: Deprecate Forseti installer wizard

### ISSUE THREAD

**Issue by morgante** [forseti-security/forseti-security#2758]
This issue is to gather discussion on a proposal to deprecate the existing Forseti installer in favor of the [Terraform module](https://github.com/terraform-google-modules/terraform-google-forseti).

The full proposal is captured in [this document](https://docs.google.com/document/d/1Q9Id6yX01Qryv3sr4au_4GlCyoUJw2BRkMFrNNRuBjI/edit).

**Comment by Red-Five** [comment]
I think it's more efficient to standardize on terraform; 

If we just use Terraform, would would we still have a path to offer a push button deployment from Google Cloud Marketplace?

**Comment by morgante** [comment]
> If we just use Terraform, would we still have a path to offer a push button deployment from Google Cloud Marketplace?

I don't believe it's currently possible to install from the Marketplace with either installer, but it's something we could explore in the future.

**Comment by nbards** [comment]
Is GCP deprecating deployment-manager in favor of terraform generally?  As an enterprise customer, with my account team and Google Professional Services telling me to use Forseti, creating additional pre-reqs to installing and managing the tool is not very appealing.
(i don't have access to the document so only have the info in this issue.)

**Comment by morgante** [comment]
@nbards There are not plans to deprecate DM across the board, but maintaining two different installers is a substantial operational burden.

That being said, before deprecating the DM installer we plan to build a guided install experience in Cloud Shell (w/ Terraform pre-reqs installed) available—would that address your concerns?

**Comment by nbards** [comment]
@morgante I understand that.  I have substantial operational burdens using forseti in my enterprise, too.  Glad to discuss.  I'm happy to participate, and trial the "guided install experience".
Since Google is telling me as a paying customer to use forseti, who from Google could participate in the discussion as well?

**Comment by morgante** [comment]
@nbards Once we have the guided install, I'm happy to trial it with you. (I work at Google.)

**Comment by gkowalski-google** [comment]
Forseti has fully moved over to Terraform, no longer support DM.
