### ISSUE TITLE
Incorrect zone for client on forseti_client_installer.py

### ISSUE THREAD

**Issue by fawix** [forseti-security/forseti-security#2759]
version = 2.14.0
module: installer (via gcp_installer.py)

The `forseti_client_installer.py` is not obtaining the Client Instance Zone properly. 

```python
        if success:
            instance_name = 'forseti-{}-vm-{}'.format(
                self.config.installation_type,
                self.config.identifier)
            zone = '{}-c'.format(self.config.bucket_location)  # <== THIS!! Line 70
            gcloud.enable_os_login(instance_name, zone)
            # Create firewall rules.
            self.create_firewall_rules()
            self.wait_until_vm_initialized(instance_name)
        return success, deployment_name
```

That means it will get the bucket region name and append a -c to get the zone name - this is totally misleading (also, there are other zones besides "c").

it generates the following logs when you are *not* using the default:

```log
+-------------------------------------------------------------------------------
|  Backing Up Important Files To GCS
+-------------------------------------------------------------------------------

Copying the Forseti client configuration file to:
        gs://forseti-client-ae2e185/configs/forseti_conf_client.yaml
Copying the Forseti client deployment template to:
        gs://forseti-client-ae2e185/deployment_templates/
Command "gcloud compute instances add-metadata forseti-client-vm-ae2e185 --metadata enable-oslogin=TRUE --zone us-central1-c" failed/timeout, retrying...
Command "gcloud compute instances add-metadata forseti-client-vm-ae2e185 --metadata enable-oslogin=TRUE --zone us-central1-c" failed/timeout, retrying...
Command "gcloud compute instances add-metadata forseti-client-vm-ae2e185 --metadata enable-oslogin=TRUE --zone us-central1-c" failed/timeout, retrying...
Command "gcloud compute instances add-metadata forseti-client-vm-ae2e185 --metadata enable-oslogin=TRUE --zone us-central1-c" failed/timeout, retrying...
Command "gcloud compute instances add-metadata forseti-client-vm-ae2e185 --metadata enable-oslogin=TRUE --zone us-central1-c" failed/timeout, retrying...
ERROR: (gcloud.compute.instances.add-metadata) Could not fetch resource:
 - The resource 'projects/forseti-238321/zones/us-central1-c/instances/forseti-client-vm-ae2e185' was not found
```

Locally I have modified line 70 to read as follows: 

```python
zone = self.server_zone
``` 

From what I saw in the code it looks like "server" here is referring to instance and not the forseti server vm. If someone can confirm my understanding I can submit a PR with the change.

**Comment by gkowalski-google** [comment]
Hi @fawix, sorry to get back to you so late on this issue. Forseti now supports installation through [Terraform](https://registry.terraform.io/modules/terraform-google-modules/forseti/google/1.4.0) and many of these types of options are now available for you to customize, including the client zone. Please let me know if you have any questions or if we can close this out.

**Comment by gkowalski-google** [comment]
@fawix we have not heard back from you in 2 weeks, and this is an old issue. Closing the issue for now. Please reopen and if this is still valid and you need assistance.
Thanks!
