### ISSUE TITLE
Update Forseti docs for CSCC API now in GA

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2760]
- [x] Update Forseti docs to reflect CSCC API now GA.
- [x] Please confirm if there are any changes required to the Forseti SCC Marketplace workflow with the move to GA or no changes are required
https://console.cloud.google.com/marketplace/details/forseti/forseti-security-cloud-scc-connector?folder&organizationId=527263219430

Related to: https://github.com/forseti-security/forseti-security/pull/2680

**Comment by red2k18** [comment]
#2765 updates the doc.

No changes are required. Functionality remains same.
