### ISSUE TITLE
BucketsAclScanner not working

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/forseti-security#2763]
Reported by Antoine.

BucketsAclScanner not working due to "Commands out of sync; you can't run this command now" error.

Error:

```File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler raise errorclass, errorvalue ProgrammingError: (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'SELECT `86b68fabef8f4387ab709b6f639cf271_resources`.cai_resource_name AS `86b68fabef8f4387ab709b6f639cf271_resources_cai_resource_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.cai_resource_type AS `86b68fabef8f4387ab709b6f639cf271_resources_cai_resource_type`, `86b68fabef8f4387ab709b6f639cf271_resources`.full_name AS `86b68fabef8f4387ab709b6f639cf271_resources_full_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.type_name AS `86b68fabef8f4387ab709b6f639cf271_resources_type_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.parent_type_name AS `86b68fabef8f4387ab709b6f639cf271_resources_parent_type_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.name AS `86b68fabef8f4387ab709b6f639cf271_resources_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.type AS `86b68fabef8f4387ab709b6f639cf271_resources_type`, `86b68fabef8f4387ab709b6f639cf271_resources`.policy_update_counter AS `86b68fabef8f4387ab709b6f639cf271_resources_policy_update_counter`, `86b68fabef8f4387ab709b6f639cf271_resources`.display_name AS `86b68fabef8f4387ab709b6f639cf271_resources_display_name`, `86b68fabef8f4387ab709b6f639cf271_resources`.email AS `86b68fabef8f4387ab709b6f639cf271_resources_email`, `86b68fabef8f4387ab709b6f639cf271_resources`.data AS `86b68fabef8f4387ab709b6f639cf271_resources_data` \nFROM `86b68fabef8f4387ab709b6f639cf271_resources` \nWHERE `86b68fabef8f4387ab709b6f639cf271_resources`.type_name = %s'] [parameters: (u'project/gbl-imt-ve-datalake-prod',)] (Background on this error at: http://sqlalche.me/e/f405)```

**Comment by red2k18** [comment]
@hshin-g can this be closed?
