### ISSUE TITLE
Add new CAI resources (k8s)

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2772]
CAI has announced these new resources, and these should be added to Forseti inventory.

k8s.io/Node | (2019-04-24)
k8s.io/Pod | (2019-04-24)
k8s.io/Namespace | (2019-04-24)
rbac.authorization.k8s.io/Role | (2019-04-24)
rbac.authorization.k8s.io/RoleBinding | (2019-04-24)
rbac.authorization.k8s.io/ClusterRole | (2019-04-24)
rbac.authorization.k8s.io/ClusterRoleBinding | (2019-04-24)

**Comment by red2k18** [comment]
#2916 adds kubernetes resources to inventory.

**Comment by dekuhn** [comment]
This PR should be part of this issue for tracking: https://github.com/forseti-security/terraform-google-forseti/pull/184

**Comment by red2k18** [comment]
Actually #184 will have all the 2.17 release changes including k8s changes. That's why I did not link this issue in that PR. Let me know if you want me to link it there.
