### ISSUE TITLE
Findings reported to CSCC are not being properly updated when resolved

### ISSUE THREAD

**Issue by supersmo** [forseti-security/forseti-security#2779]
When findings are resolved they remain unchanged with an old timestamp in CSCC.
Would be good if they had their status changed to inactive.

Found a discussion regarding this in the forseti forum:
https://groups.google.com/a/forsetisecurity.org/forum/#!searchin/discuss/cscc%7Csort:date/discuss/eAHvgCzIVww/IVPcJqOdBQAJ

**Comment by red2k18** [comment]
@supersmo this has been fixed in v2.13.0. What version are you on? Are you filtering for active findings on CSCC?

**Comment by supersmo** [comment]
We were on 2.14.1 
We tested to create a firewall violation, altered the firewall rule so it still was violating the rule, removed the firewall rule while running the forseti scan inbetween each step. The end result was 2 findings regarding the rule and none of them went from active to inactive.
Today we upgraded to 2.14.2 and my colleague ran the tests again and the behaviour was the same but he found some log messages regarding cscc so that could have something to do with it.
I'm off work at the moment so I don't have the details where I'm at so I just want to let you know that we're still investigating. We'll dig into this some more later this week and probably have a more proper report with log messages and finding entries etc.

**Comment by red2k18** [comment]
@supersmo Thanks. Please provide more details and/or screenshot if possible so we can investigate.

**Comment by supersmo** [comment]
Sure here's a screenshot: ![image](https://user-images.githubusercontent.com/12717958/57776608-401fde80-7720-11e9-9249-5ada62d05830.png)
We created a VM with an external network IP which triggered a finding at 2:02 PM.
Then we deleted the VM and ran forseti again at 2:38 PM but the old finding remains active.

We checked the logs generated with debug logging active, but didn't find any entries regarding:
`LOGGER.debug('Updating finding CSCC:\n%s.', finding)`
from: [cscc_notifier.py](https://github.com/forseti-security/forseti-security/blob/b92ed049f45337db3f750ed2fe19e6df1e886454/google/cloud/forseti/notifier/notifiers/cscc_notifier.py)

**Comment by red2k18** [comment]
@supersmo  Thanks for the information! Sorry for the delayed response. I was not tagged so I was not notified of your response.

Could you also share the screenshot which says that these violations were not generated when you ran the Notifier followed by the Scanner?

**Comment by red2k18** [comment]
@supersmo Please share more information when you get a chance.

**Comment by red2k18** [comment]
@supersmo We've fixed this issue in v2.13.0. Let us know if you're still seeing INACTIVE findings after checking the Active findings check box on CSCC.

**Comment by supersmo** [comment]
Hi,
We are on Forseti 2.16.
The feature is not working for us at all.
As the screenshot I posted earlier indicates the old findings are not put in inactive when they are fixed. They remain active with an timestamp.

Here is an extraction of the log from the latest run. Doesn't show much except that we have debug logging on and that it finds violations and successfully sends them to cscc. It's hard to show lines about the fixed violations since they don't exist in the logs:
`2019-06-10 06:06:14,207 DEBUG [forseti-security][2.16.0] google.cloud.forseti.common.gcp_api.securitycenter(create_finding): Creating finding.
2019-06-10 06:06:14,786 DEBUG [forseti-security][2.16.0] google.cloud.forseti.common.gcp_api.securitycenter(create_finding): Created finding response: {'name': 'organizations/yyyyyyyy/s
ources/4309252352274325465/findings/3df310548128826739eab785f3931653', 'parent': 'organizations/yyyyyyyy/sources/4309252352274325465', 'resourceName': 'organization/yyyyyyyy/folder/
345886931040/folder/819406524069/project/common-dev-xxxxxx/bucket/sam-voice-recognition-output/', 'state': 'ACTIVE', 'category': 'LOCATION_VIOLATION', 'sourceProperties': {'source': 'FORS
ETI', 'db_source': 'table:violations/id:17016', 'inventory_index_id': 1560146409699845, 'resource_data': '{"acl": [], "billing": {}, "cors": [], "defaultObjectAcl": [], "encryption": {}, "e
tag": "CAE=", "iamConfiguration": {"bucketPolicyOnly": {"enabled": false}}, "id": "sam-voice-recognition-output", "kind": "storage#bucket", "labels": {}, "lifecycle": {"rule": []}, "locatio
n": "US", "logging": {}, "metageneration": 1, "name": "sam-voice-recognition-output", "owner": {}, "projectNumber": xxxxxx, "retentionPolicy": {}, "selfLink": "https://www.googleapis.com
/storage/v1/b/s
2019-06-10 06:06:14,787 DEBUG [forseti-security][2.16.0] google.cloud.forseti.notifier.notifiers.cscc_notifier(_send_findings_to_cscc): Successfully created finding in CSCC:
{'name': 'organizations/yyyyyyyy/sources/4309252352274325465/findings/3df310548128826739eab785f3931653', 'parent': 'organizations/yyyyyyyy/sources/4309252352274325465', 'resource_na
me': 'organization/yyyyyyyy/folder/345886931040/folder/819406524069/project/common-dev-xxxxxx/bucket/sam-voice-recognition-output/', 'state': 'ACTIVE', 'category': 'LOCATION_VIOLATION
', 'event_time': '2019-06-10T06:02:45Z', 'source_properties': {'source': 'FORSETI', 'db_source': 'table:violations/id:17016', 'inventory_index_id': 1560146409699845, 'resource_data': '{"acl": [], "billing": {}, "cors": [], "defaultObjectAcl": [], "encryption": {}, "etag": "CAE=", "iamConfiguration": {"bucketPolicyOnly": {"enabled": false}}, "id": "sam-voice-recognition-output", "kind": "storage#bucket", "labels": {}, "lifecycle": {"rule": []}, "location": "US", "logging": {}, "metageneration": 1, "name": "sam-voice-recognition-output", "owner": {}, "projectNumber": xxxxxx, "retentionPolicy": {}, "s
`

**Comment by red2k18** [comment]
Hi, thanks for the information! I think it will be easier to hop on a call and see what is going on. Let me know your availability so I can schedule a call. Thanks!

**Comment by red2k18** [comment]
We will prioritize this for next release.

**Comment by ocervell** [comment]
+1 running into this as well

**Comment by red2k18** [comment]
Sorry for the inconvenience caused. The fix will be part of 2.17 scheduled to release this Thursday.

**Comment by red2k18** [comment]
Feel free to reopen this issue if the issue persists.

**Comment by supersmo** [comment]
Great! Thanks! Been on vacation and currently a bit overswamped with work. I'll report back when the fix is verified.

**Comment by red2k18** [comment]
Looking forward to hearing from you.

**Comment by supersmo** [comment]
It works! Thanks for the fix! :-)

**Comment by red2k18** [comment]
Awesome! Thanks for letting me know. :)
