### ISSUE TITLE
Cloudsql Password update

### ISSUE THREAD

**Issue by sparthe123** [forseti-security/forseti-security#2785]
Hi,

 Every time where there is a version update for Forseti, I need to update my cloudsql password (vi /lib/systemd/system/forseti.service) after update complete.Is there any way I can achieve this during deployment, so it can update in all required places. 
Thanks!

**Comment by nbards** [comment]
Also, the `forseti-security/install/gcp/upgrade_tools/db_migrator.py` script fails in the default no-password configuration, this created a problem in the 2.13 to 2.14 upgrade.

if there is a way to properly store a secret like a db password, that would be great!  I haven't found one appropriate to deployment-manager templates, though.

Perhaps in `forseti-security/deployment-templates/compute-engine/server/forseti-instance-server.py` a check could be made for a local file of a particular name that could bring in additional config info?   if just env vars, then some shell if/then could update both the db_migrator.py cmd line and the creation of the service file injecting the password if it exists.  (the password is clearly displayed on `ps` listings, so being locally available on the box is a different scope of problem then having it stored clear-text in a deployment template or a cloud storage bucket.)

currently i'm using a sed command to update the service file via cron job as the ubuntu user
```
sudo systemctl stop forseti
sed -e 's!--forseti_db mysql://root@127.0.0.1:3306/forseti_security!--forseti_db mysql://root:${my_password}@127.0.0.1:3306/forseti_security!' /lib/systemd/system/forseti.service > ~/forseti.service.fixed
sudo cp ~/forseti.service.fixed /lib/systemd/system/forseti.service
sudo systemctl daemon-reload
sudo systemctl restart forseti
```
