### ISSUE TITLE
LogSink is not working and generating wrong Violations

### ISSUE THREAD

**Issue by hariram01** [forseti-security/forseti-security#2788]
Dear Team

I am using Forseti V2.14 and I am having issue with Log Sink Scanner.
I am trying to run logsink scanner which is not working. I created one logsink of my one project but still it is showing in violation report.

I deployed Forseti on Local.

I am attaching supporting artifacts of this issue

Regards
Hari
[Log SInk Issue.docx](https://github.com/forseti-security/forseti-security/files/3142078/Log.SInk.Issue.docx)

**Comment by red2k18** [comment]
Size 1 as it needs to be investigated.

**Comment by blueandgold** [comment]
Hi @hariram01 , I am able to reproduce your issue.  It looks like you have a line break in your log sink rule.

![image](https://user-images.githubusercontent.com/6977544/61265671-1dbd3800-a746-11e9-853d-055a894e2997.png)

So, combine the `filter` value into one line, and the scanner will match it correctly to your log sink, and then no violation will be found.

I will go ahead and close this issue.  If you have any more questions, please don't hesitate to re-open it.
