### ISSUE TITLE
Database column error reported by multiple customers after upgrading to 2.14

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#2799]
Below id the complete error message reported by multiple customers after upgrading to 2.14.

Suggested user to reset the server VM and check if startup script is executed successfully. Error persists.

```
Error occurred on the server side, message: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'cai_resource_name' in 'field list'") [SQL: u'INSERT INTO gcp_inventory (inventory_index_id, cai_resource_name, cai_resource_type, category, resource_type, resource_id, resource_data, parent_id, other, inventory_errors)
```

**Comment by nbards** [comment]
for me this was due to setting a cloudsql password according to the faq.  the db_migrator.py script has no mechanism for getting a passworded connect string due to pulling code from github on reboot.  i manually ran the update script.

**Comment by red2k18** [comment]
Did manually running the update script help?

**Comment by nbards** [comment]
yes, manually running the update script with the password in the connect string per the FAQ on setting a db password fixed the problem.  (and looking at the data read audit trail for cloudsql when rebooting/resetting the server vm makes it clear that it was an authentication error when running the db_migrator.py script.)

**Comment by red2k18** [comment]
Cool, thank you for the information.
