### ISSUE TITLE
A single scanner failure crashes entire scan and provides no log

### ISSUE THREAD

**Issue by osandoval011** [forseti-security/forseti-security#2800]
When a single scanner fails, it crashes whole scanning process (of all scanners), and no logs are provided even with debug set at log level

First, help us help you by providing the following information when opening an issue.

 - [ ] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
 - [ ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ ] Include errors, log output, and host operating system, including installed packages.
 - [ ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

Secondly, if the issue is a feature request, be descriptive regarding what needs to be
changed and why, e.g. what to scan for, what would be a 'good' state and what would be
a 'violation' etc.

Finally, be sure to see the [FAQ](https://forsetisecurity.org/docs/latest/faq/) and [Get Help](https://forsetisecurity.org/docs/latest/develop/get-help.html)
for assistance.

Thanks!

**Comment by ocervell** [comment]
+1 very hard to debug
