### ISSUE TITLE
don't use root as the cloudsql db user

### ISSUE THREAD

**Issue by nbards** [forseti-security/forseti-security#2802]
- [ 2.13, 2.14, 2.14.1, 2.15 ] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` on the client).
 - [ installer ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ n/a ] Include errors, log output, and host operating system, including installed packages.
 - [ deployment manager ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

Following reasonable industry practices, the mysql root user should not be used by applications for operational access.  It would be great if forseti used a non-root user with minimal necessary permissions, revoking un-needed and un-used rights per https://cloud.google.com/sql/docs/mysql/users

**Comment by cybermerc** [comment]
There is a reason for the current setup documented here  https://github.com/forseti-security/forseti-security/issues/921

That being said, its a bit dated so going to look and see if this can be addressed now

**Comment by gkowalski-google** [comment]
Resolved by #3217
