### ISSUE TITLE
facing issue when I use this code to provide Source IP Ranges

### ISSUE THREAD

**Issue by ksulakh98** [forseti-security/forseti-security#2842]
When we use sourceRanges to blacklist any IP ranges
It does not work as expected and does not generate violation for that IP Range.
We have followed proper indentation. 

Version: v2.15.0
Module: Scanner

**Comment by red2k18** [comment]
Hi, is it possible for you to share with us the rule you have configured for this?

**Comment by dekuhn** [comment]
@ksulakh98 We can't do much to help fix this without more details. Please re-open the issue and provide us with your rule please.
