### ISSUE TITLE
Firewall source range rule applied to a Firewall that uses sourceTags

### ISSUE THREAD

**Issue by urbanenomad** [forseti-security/forseti-security#2860]
- [ ] Which version of Forseti Security you're using 
Forseti version: 2.13.1

 - [ ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
scanner

 - [ ] Include errors, log output, and host operating system, including installed packages.
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 - [ ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).
locally deployed on GCP VM

I created the following rule
`
rules:
  - rule_id: 'prevent_allow_all_ingress'
    description: Detect allow ingress to all policies
    mode: blacklist
    match_policies:
      - direction: ingress
        allowed: ['*']
    verify_policies:
      - allowed:
        - IPProtocol: 'all'

  - rule_id: 'CIS_GCP_3.6-No all CIDR access ssh'
    description: Ensure that SSH access is restricted from the internet
    mode: blacklist
    match_policies:
      - direction: ingress
        allowed: ['*']
        sourceRanges:
          - '0.0.0.0/0'
    verify_policies:
      - allowed:
        - IPProtocol: 'tcp'
          ports:
            - '22'
            
  - rule_id: 'CIS_GCP_3.7-No all CIDR access RDP'
    description: Ensure that RDP access is restricted from the internet
    mode: blacklist
    match_policies:
      - direction: ingress
        allowed: ['*']
        sourceRanges:
          - '0.0.0.0/0'
    verify_policies:
      - allowed:
        - IPProtocol: 'tcp'
          ports:
            - '3389'
            
rule_groups:
  - group_id: 'default_rules'
    rule_ids:
      - 'prevent_allow_all_ingress'
  - group_id: 'CIS_GCP'
    rule_ids:
      - 'CIS_GCP_3.6-No all CIDR access ssh'
      - 'CIS_GCP_3.7-No all CIDR access RDP'

org_policy:
  resources:
    - type: organization
      resource_ids:
        - <<orgNumber>>
      rules:
        group_ids:
          - 'default_rules'
          - 'CIS_GCP'
`

I am getting the violation "CIS_GCP_3.6-No all CIDR access ssh" that is pointing to a FW rule that has the following FW configuration

Priority: 1000
Direction: Ingress
Action on match: Allow
Targets - Target tags: dataflow
Source filters - Tags: dataflow
Protocols and ports: tcp:1-65535

Why is that rule that uses sourceTags, a violation for a forseti FW rule that uses sourceRanges?  Did I not configure the rules properly?

**Comment by gkowalski-google** [comment]
Hi @urbanenomad, I apologize for not getting back to you sooner. Are you still experiencing this issue?

**Comment by blueandgold** [comment]
Closing this issue as there is no follow-up.  But please update here and I can re-open this issue.  Thanks.
