### ISSUE TITLE
Update Forseti docs to reference Python3

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2881]
Linking docs that need to be updated for Python 3.

https://forsetisecurity.org/docs/latest/develop/dev/setup.html#setting-up-a-local-environment
  brew install python@2

https://forsetisecurity.org/docs/latest/develop/dev/setup.html#troubleshooting
cd <virtual environment>/lib/python2.7/site-packages/google/cloud

Should we be running pylint --py3k - maybe this is addressed and I am missing where this is configured?

**Comment by red2k18** [comment]
#2886 fixes this.
