### ISSUE TITLE
Make "Contact Us" link more prominent on the front page.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#2883]
Currently, it's not easy to find out how to contact the forseti team on the website.  

When I go to the front page, nothing immediately sticks out, unless I do a lot of scrolling to the bottom, which seems not a good user experience since I am just guessing/hoping something might be down there.  

I would expect to find a Contact Us link at the top menu bar.

**Comment by red2k18** [comment]
I'm sure this will be super helpful to users.

**Comment by red2k18** [comment]
#2887 fixes this.
