### ISSUE TITLE
Unable to get scanner output results for multiple organizations using a single forseti_conf_server.yaml file

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#2884]
Hi,

I am using Forseti release-2.15.1

I am trying to get scanner output for multiple GCP organizations using the same conf file [`forseti_conf_server.yaml`]https://github.com/forseti-security/forseti-security/blob/dev/configs/server/forseti_conf_server.yaml.sample

As mentioned on the instruction (`You must set ONLY one of root_resource_id or composite_root in your configuration. Defining both will cause Forseti to exit with an error.`), instead of using `root_resource_id: organizations/<ORGANIZATION_ID1>`, I used:
```python
composite_root_resources:
       - "organizations/<ORGANIZATION_ID1>"
       - "organizations/<ORGANIZATION_ID2>"
```

However, I am getting the following error:
```
File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.15.0-py2.7.egg/google/cloud/forseti/services/explain/service.py", line 63, in _determine_is_supported
if 'organizations' in root_resource_id:
TypeError: argument of type 'NoneType' is not iterable
```

Could you please let us know what am I missing.

Thank you,
Abhishek

**Comment by red2k18** [comment]
Hi Abhishek, did you comment out `root_resource_id`? If not, what value did you provide for that field?

**Comment by abhishekupadhyaya** [comment]
I have commented out `root_resource_id`.

**Comment by red2k18** [comment]
Could you try this instead and let me know if it works - `root_resource_id: ""`?

**Comment by red2k18** [comment]
Did it work for you?

**Comment by abhishekupadhyaya** [comment]
@red2k18 thanks. It worked. I will close the issue.
