### ISSUE TITLE
Address website commits without CLA

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2889]
There are a number of [commits](https://github.corp.google.com/prinfo?q=/https://github.com/forseti-security/forseti-security/pull/2807) that did not have proper CLA signed and creates issues when integrating the web site. We need to address the missing CLA or revert the commits.

**Comment by dekuhn** [comment]
Can fix email address if we need to change to update someone's email to their CLA approved email for past commit.
https://www.git-tower.com/learn/git/faq/change-author-name-email

**Comment by dekuhn** [comment]
@blueandgold  I know you are working on this, but suspect we just have not been updating the issue. I assigned this issue to you. Please review and decide to keep open or close it based on where you are in the process of addressing the CLA. Thanks.

**Comment by blueandgold** [comment]
All website PRs have been checked for CLA.  Will have either `cla: yes` or `cla: no` labels.
