### ISSUE TITLE
Rotate Forseti server service account key as it is a best practice.

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#2903]
- [ ] Investigate GAE push for docs
- [ ] Investigate integration testing environment
---
No service account keys are generated for the Forseti deployments (GCE + GKE). The service account is bound to the GCE VMs so that no keys are generated. For GKE uses something similar, which is the workload identity.

There might be some service account keys used for the builds on Travis. Investigate and suggest a process to be followed by the release engineer.

**Comment by kevensen** [comment]
An IAM SA key is used by forsetisecurity.org to connect to App Engine.  It is encrypted.  I don't think there is an out of the box rotation mechanism for this scenario.  However, one could be constructed

**Comment by kevensen** [comment]
@kevensen To update internal release docs

**Comment by gkowalski-google** [comment]
Was this completed as part of the v2.24.0 release?

**Comment by kevensen** [comment]
D'oh.  No, this slipped through the cracks.  I can take a look at it later today.
