### ISSUE TITLE
Python3 environment setup process is not working

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2904]
Our Python3 setup instructions appear to not working for the team. We need to figure out what is broken and update the public docs.

**Comment by Red-Five** [comment]
Is this a duplicate of https://github.com/forseti-security/forseti-security/issues/2890 or are their other issues?

**Comment by blueandgold** [comment]
Thanks @Red-Five This is separate, this relates to the local development env setup.

**Comment by dekuhn** [comment]
@red2k18 Did you figure this out, if so can can we update the docs and close this issue out. Thanks!

**Comment by red2k18** [comment]
#2902 fixed this issue in June.
