### ISSUE TITLE
Integration / Release Automation

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#2906]
Automate the release process which is manual currently.  As much as feasible, this should involve automatically create the release branch, run the functional tests, sign the release, and then finalize the release.

**Comment by red2k18** [comment]
@dekuhn do we want to track integration testing / release automation work on GitHub? If yes, need to update this Epic with relevant issues. I can do that once it's decided.

**Comment by dekuhn** [comment]
@red2k18 yes
