### ISSUE TITLE
violation_data from CONFIG_VALIDATOR_VIOLATION have extra escape characters

### ISSUE THREAD

**Issue by katze120** [forseti-security/forseti-security#2909]
- version 2.16.0
 - module: scanner
 - violation data from CONFIG_VALIDATOR_VIOLATION have extra escape characters. They're not proper json format, keys cannot be sorted properly, causing duplicate violation_hash and subsequently duplicate findings on CSCC to be created

Example violation_data from CONFIG_VALIDATOR_VIOLATION in forseti_security.violation table and violation_data field of CSCC findings:
"{\n  \"resource\": \"//storage.googleapis.com/nonexistent-bucket-name-just-an-example\",\n  \"location\": \"ASIA-SOUTHEAST1\"\n}"

Expected output in eventual CSCC findings - no escape characters and keys sorted:
{"location": "ASIA-SOUTHEAST1",  "resource": "//storage.googleapis.com/nonexistent-bucket-name-just-an-example"}

Possibly we can look into _flatten_violations in google/cloud/forseti/scanner/scanners/config_validator_scanner.py  to fix escape characters

(then ViolationAccess.create in ./google/cloud/forseti/services/scanner/dao.py will be able to handle the key sorting)

**Comment by red2k18** [comment]
@joecheuk please determine the priority and add priority label to this issue.
