### ISSUE TITLE
Supporting whitelist mode for Cloud SQL networks scanner

### ISSUE THREAD

**Issue by Murcurio** [forseti-security/forseti-security#2911]
- [ v2.16.0 ] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
 - [ scanner ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ ] Include errors, log output, and host operating system, including installed packages.
 - [ terraform ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

We would like to be able to whitelist networks exposed on Cloud SQL rather than just blacklisting. Blacklisting allows us to stop Cloud SQL opening up to the world, but our use-case requires that Cloud SQL can only be available to corporate IP addresses.

**Comment by hshin-g** [comment]
@joecheuk Is this something that we can implement in the Config Validator?

**Comment by joecheuk** [comment]
Hi @Murcurio , this constraint template should address your use case:
https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_sql_allowed_authorized_networks_v1.yaml

You can read more [here](https://forsetisecurity.org/docs/latest/configure/scanner/descriptions.html#config-validator-scanner) on how to enable config validator scanner in Forseti.

**Comment by gkowalski-google** [comment]
Hi @Murcurio, do you need any help with this or were you able to get this setup?

**Comment by gkowalski-google** [comment]
@Murcurio Closing this issue since we have not heard back from you. Please re-open if you still need assistance. Thanks!
