### ISSUE TITLE
Consider Moving to mysql-connector

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#2922]
The current dependency "mysqlclient==1.4.2" relies on C libraries to compile the Python byte code.  The mysql-connector-python library doesn't have an C library dependencies: [https://pypi.org/project/mysql-connector-python/](https://pypi.org/project/mysql-connector-python/)

**Comment by dekuhn** [comment]
@kevensen Can you add some context how this benefits us in a GKE deployment? IIRC relying on the C lib means you had to make some considerations for this dependacy.

**Comment by kevensen** [comment]
I think this would benefit both the GCE and GKE deployments.  The fewer dependencies you install in a host or container, the smaller the surface of attack.

In the case of GKE, it's one less package installed resulting in a smaller container image (every MB makes a difference :-) ).  It's shorter time building the images as well.

**Comment by kevensen** [comment]
If opting for BigQuery as a data store, this is moot.

**Comment by kevensen** [comment]
If I understand correctly, Forseti will continue to use MySQL as a data store.  I think we should continue to  consider this.

**Comment by kevensen** [comment]
This will enable us to use distroless containers.

**Comment by kevensen** [comment]
We implemented PyMySQL.  This can be closed.
