### ISSUE TITLE
Wrong indentation for scanners block?

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#2939]
I believe the "scanners" block has one indent too many.

https://github.com/forseti-security/forseti-security/blob/e8478d39e47d5f4b65a87aa611a8e924f9ef796e/configs/server/forseti_conf_server.yaml.sample#L198-L248

**Comment by paskal** [comment]
True! `scanners:` line should be indented with one less space, currently, it's causing YAML validation problems like that: `did not find expected key while parsing a block mapping at line 203 column 5 `.
