### ISSUE TITLE
Add new compute.interconnect, compute.interconnect_attachment resources from CAI to forseti inventory

### ISSUE THREAD

**Issue by ahoying** [forseti-security/forseti-security#2957]
The following resource type(s) have been onboarded into the Cloud Asset Inventory and are now publicly available through the CloudAsset APIs:

Resource | Availability
-- | --
compute.interconnect | 2019-06-26
compute.interconnect_attachment | 2019-06-26

**Comment by kevensen** [comment]
Can this be pushed to 2.21?
