### ISSUE TITLE
Use MySQL in a container instead of CloudSQL?

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#2973]
Using MySQL in a container instead of CloudSQL may increase performance.  Investigation is required to assert this.

**Comment by blueandgold** [comment]
Thanks for the idea, putting into our planning backlog.

**Comment by kevensen** [comment]
Just a stream of thoughts....

1. Installation times will be faster if not dependent on a CloudSQL instance
2. Decreased cost
3. Less network traversal

**Comment by kevensen** [comment]
https://github.com/forseti-security/helm-charts/issues/28
