### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by hariram01** [forseti-security/forseti-security#2986]
Hi Team

I installed forseti V2.18 via deployment manager. I noticed that forseti is running since last 24+ hours in production. I checked the stack driver log and found error "MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') ".
Please find attached log also.
[Forseti Error.txt](https://github.com/forseti-security/forseti-security/files/3411416/Forseti.Error.txt)
 
How should I take this error? How can i fix? Is still forseti running or stop? 

Thanks
Hari

**Comment by joecheuk** [comment]
Working with Hari to resolve the problem, seems like the default cloud sql instance is not sufficient for bigger gcp orgs.

**Comment by joecheuk** [comment]
It doesn't happen any more after increasing the size of the cloudsql instance.
