### ISSUE TITLE
Add CAI Resource container.googleapis.com/NodePool

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3010]
- [ ] Pre-req" container.googleapis.com/NodePool needs to be GA and available in the CAI python library.

**Comment by dekuhn** [comment]
We need to wait for the NodePool feature to hit GA, currently in Beta. We are dependant on a CAI python library.

**Comment by gkowalski-google** [comment]
Status of the NodePool in CAI can be seen here: https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/overview.

**Comment by gkowalski-google** [comment]
NodePool still in beta.

**Comment by gkowalski-google** [comment]
Still in beta...

**Comment by gkowalski-google** [comment]
In GA.
