### ISSUE TITLE
Error getting Inventory Gsuite data

### ISSUE THREAD

**Issue by Gribel** [forseti-security/forseti-security#3025]
I'm trying to install and configure Forseti using all info provided from Forseti manual.

There's already some days I'm trying to create Inventory list but it still with PARTIAL_SUCCESS status. When I get an inventory detail it says:

"warnings": "GCP API Error: unable to get groups from GCP:\n<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/groups?customer=XXXXXXXXXXX&alt=json returned \"Not Authorized to access this resource/api\">\n{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"forbidden\",\n    \"message\": \"Not Authorized to access this resource/api\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Not Authorized to access this resource/api\"\n }\n}\n\n\nGCP API Error: unable to get users from GCP:\n<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/users?customer=XXXXXXXXXXXX&viewType=admin_view&alt=json returned \"Not Authorized to access this resource/api\">\n{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"forbidden\",\n    \"message\": \"Not Authorized to access this resource/api\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Not Authorized to access this resource/api\"\n }\n}\n\n\n",
    "errors": ""

I already did what the FAQ says about this error and everything is as docs tell me to do. It looks like can't connect to Gsuite, but when I try it from the same API I get 200 code.

https://developers.google.com/apis-explorer/#search/v1%20admin%20directory/m/admin/directory_v1/directory.groups.list?customer=XXXXXXXXX&domain=XXXXXXXX.com.br&_h=1&

**Comment by kevensen** [comment]
Hi @Gribel.  Thank you for submitting this issue.  Using the API explorer is a good first step in diagnosing the issue.  In this case you likely invoked the API explorer as your user identity.  The Forseti Server calls the API as the Forsti Server service account.  This is a possible reason why you are seeing two different results.

I see that you've reviewed the documentation.  Can you please confirm for me the following.
1. The version of Forseti you have deployed.
2. You've enabled [Domain Wide Delegation](https://forsetisecurity.org/docs/latest/configure/inventory/gsuite.html#enable-dwd-on-a-service-account) on the forseti-server service account.
3. In the GSuite admin console, you have added the [API scopes](https://forsetisecurity.org/docs/latest/configure/inventory/gsuite.html#enable-the-service-account-in-your-g-suite-admin-control-panel) to the client
4. The **Client Name** specified in the "Manage API client access" in the GSuite Admin Console is not the service account name but rather the DwD IAM Client ID from GCP IAM.

**Comment by red2k18** [comment]
@Gribel Please respond to the previous comment when you get a chance so we can investigate this issue further. Thanks!

**Comment by gkowalski-google** [comment]
@Gribel Following up to see if you were able to follow the steps above and get this working.

**Comment by dekuhn** [comment]
@Gribel we have not heard back from you in 2+ weeks. Closing the issue for now. Please reopen and provide feedback regarding the steps provided by kevensen with his Aug 13 comment.
