### ISSUE TITLE
TypeError in notification process

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3026]
Hi,

We just migrated to release-2.18.0, which uses Python3. We use this in our production system for security reporting, and has been impacted.

We are seeing the following error as part of notification process:

```
"serverMessage": "Error occurred during the notification process: 'Traceback (most recent call last):
  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/services/notifier/service.py\", line 129, in _run_notifier
    self.service_config)
  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/notifier/notifier.py\", line 187, in run
    InventorySummary(service_config, inventory_index_id).run()
  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py\", line 296, in run
    details_data = self._get_details_data()
  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py\", line 267, in _get_details_data
    details_data = self.transform_to_template(details)
  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/inventory_summary.py\", line 197, in transform_to_template
    return sorted(template_data, key=lambda k: k['resource_type'])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
'"
```

Could you please help in figuring this out?

Thank you,
Abhishek

**Comment by hshin-g** [comment]
@abhishekupadhyaya Would you be able to change the following line [here](https://github.com/forseti-security/forseti-security/blob/ee59008042be32726851d6850ea559a9b9ab25e6/google/cloud/forseti/notifier/notifiers/inventory_summary.py#L192) in your server VM to:

`return sorted(template_data, key=lambda k: (k['resource_type'] is None, k['resource_type']))`

Then run the below to apply the changes:

- `sudo python3 setup.py` install inside the `/home/ubuntu/forseti-security` folder within the VM
- `sudo systemctl restart forseti`

and see if that works?

Additionally, we have a Slack channel where you can post questions [here](https://join.slack.com/t/forsetisecurity/shared_invite/enQtNDIyMzg4Nzg1NjcxLTM1NTUzZmM2ODVmNzE5MWEwYzAwNjUxMjVkZjhmYWZiOGZjMjY3ZjllNDlkYjk1OGU4MTVhZGM4NzgyZjZhNTE).

**Comment by abhishekupadhyaya** [comment]
Thanks for your reply.

We disabled inventory summary in config file, which took care of the error since `inventory_summary` was not called.

However, could you please fix this as part of your next release.

Thank you.

**Comment by blueandgold** [comment]
Thanks @abhishekupadhyaya we have tagged this issue to be fixed at our next Sprint planning.

**Comment by kevensen** [comment]
Hi @abhishekupadhyaya we will attempt to get this in in the 2.20 release.  In any case we will keep you apprised.
