### ISSUE TITLE
Audit GA CAI resources ensure all are supported in Forseti Inventory

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3032]
https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/overview

**Comment by hshin-g** [comment]
@blueandgold Can you update this issue with the audit you have done?

**Comment by blueandgold** [comment]
This is the spreadsheet with the audit result.
https://docs.google.com/spreadsheets/d/1WgG4T9IDtXfp-8MJcZvyRGExOIdVZPZwDaAQ9hNgo94/edit#gid=0
