### ISSUE TITLE
Implement BigQuery CAI GA Resources in Forseti Inventory

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3035]
https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/overview

bigquery.googleapis.com/Dataset
bigquery.googleapis.com/Table

**Comment by hurgh** [comment]
Hi All,
How can I test out the bigquery Table component? 
I have some CAI exports from prior to the 23 August, which have bigquery table asset types in it, and I was using them, and for some reason, on the 23rd they stopped being populated.
Bigquery Datasets are still there, but no tables anymore.
I installed Forseti using terraform, but it is in a dev environment and I am happy to "upgrade" to a RC release to get the bigquery table CAI items back again.

**Comment by blueandgold** [comment]
Hi @hurgh, do you also notice any errors in the log, around Aug 23 when this stopped working?  You can check the log in stackdriver, like this:
![image](https://user-images.githubusercontent.com/6977544/63910288-e5fb0e80-c9da-11e9-96ba-c2e05ee9cb04.png)

**Comment by hurgh** [comment]
Hi @joecheuk 
Thanks for the response.
I have checked and the bigquery API is enabled in the forseti project.
Just to clarify, I have a number of CAI dump files on that day, and the first few all had bigquery.googleapi.com/Table in them, then at a point in the day and from then on, there have been no Table asset types in the files. There does not seem to have been anything that changed that I can see.
With your description of how BQ resources are currently gathered (calls to GCP API directly), would the items end up in the CAI dump file?
In the forseti_conf_server.yaml file, none of the API's are enabled, as in, they are all commented out. Again, this has not changed from when it work to now.

@blueandgold 
Thanks for the tip, I did look through the logs around the time of the last good scan and the next failed scan (when the CAI dump files changed) and i did not see any obvious errors that made me think they were related to BQ.

Could there have been a change to the GCP API that caused this to stop?

Thanks again for the pointers.

**Comment by joecheuk** [comment]
Hi @hurgh , thanks for the clarifications!

The data are stored in the forseti-server cloud sql instance, inside database `forseti_security`.

There are multiple ways to connect to the cloud sql instance, e.g. using [cloudsql proxy](https://cloud.google.com/sql/docs/mysql/quickstart-proxy-test)

For the purpose of verifying the data exists, you can try the following approach:

ssh to the forseti server VM

Install mysqlclient 
`sudo apt-get install mysql-client`

Connect to the cloudsql instance
`mysql -u root --host 127.0.0.1 --database forseti_security`

And query the gcp_inventory table
`select * from gcp_inventory where category='resource' and resource_type= 'bigquery_table' and inventory_index_id=(select id from inventory_index order by completed_at_datetime desc limit 1);`

**Comment by hurgh** [comment]
@joecheuk 
Thanks for that, I did check, and it appears that there is table data in the DB.
I added BQ Table Label checks to the "enforce_labels" rule for config validator, but i no longer get any findings in SCC for table label issues, only dataset ones.
Does config_validator rely on the output from CAI or should it work if there is data in the DB (as proved by the above query).

Thanks

**Comment by joecheuk** [comment]
Hi @hurgh ,

Yes, as for the config validator scanner we have in Forseti, we currently only scans on the data provided by CAI. The BQ table ingestion from CAI should be ready in the upcoming 1-2 releases and you will be able to scan that use case very soon. 

Thanks,
Joe

**Comment by hurgh** [comment]
Thanks all for the information and help.
I will probably just wait for the release and see how it goes then.

Regards

**Comment by joecheuk** [comment]
Hi @hurgh ,

Would you be ok to wait for another 2 weeks for the changes to go out or would you prefer having the feature asap?

Thanks,
Joe

**Comment by hurgh** [comment]
Hi All, 

Did this not make it into 2.22.0?

What is still outstanding for this to be integrated? I am happy to test this or something if required. 

Thanks

**Comment by blueandgold** [comment]
Hi @hurgh, the bigquery table data from CAI did not get released yet, pending testing.  At this point, it is being target for v2.23 release, which will go out next week.  @hshin-g for FYI

**Comment by hurgh** [comment]
Is this something I can help test?
Happy to do so if it means it will make it into 2.23 release.
Let me know what I need to do.

**Comment by blueandgold** [comment]
@hurgh Thanks for your interest to help this this.  The gotcha here is that this change is part of a much larger set of performance improvement changes, which needed further testing.  So, it is not something you can help, though we do appreciate it.  Will keep you in the loop on this.

**Comment by hurgh** [comment]
No problem.
Thanks

**Comment by blueandgold** [comment]
Hi @hurgh, the 2.23 release still needs more time to pass quality assurance.  Aiming for either later this week or early next week.  Thanks for your patience on this.

**Comment by hurgh** [comment]
@blueandgold Thanks for the update.

**Comment by blueandgold** [comment]
@hurgh Forseti v2.23.0 was release last Friday.  Can you upgrade to that, and see if the bigquery table are in inventory for you now?
