### ISSUE TITLE
Create mock dataset and inject into inventory import process

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3036]
- [x] Create mock dataset of CAI export to profile performance (e.g. 2M BQ Resources)
- [ ] Enable import process of mock data set vs CAI export for inventory process
   - [ ] Extend Inventory Config Object to fetch existing CAI export
   - [ ] Process should be reusable in release and test automation to profile performance
- [x] Create repo in Forseti Security repo for mock data generator tool
- [x] Commit Mock data tool to GitHub repo

**Comment by dekuhn** [comment]
@joecheuk can you confirm all the tasks for this issue have been addressed. If so please ack and resolve this issue. Thanks!

**Comment by joecheuk** [comment]
Issue is addressed.
