### ISSUE TITLE
Audit Forseti Inventory API data not currently supported by CAI

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3037]
- [ ] Audit data obtained by Forseti and which are only supported via APIs that are not available via CAI
- [ ] Work with CAI to add to roadmap and help with prioritization of these missing datasets for Forseti

Review commonly used APIs here: http://shortn/_pNbrtYV7rj

**Comment by blueandgold** [comment]
The result of the audit is in this doc.
https://docs.google.com/spreadsheets/d/1WgG4T9IDtXfp-8MJcZvyRGExOIdVZPZwDaAQ9hNgo94/edit#gid=0
