### ISSUE TITLE
 Improve SQL Server write bottlenecks

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3038]
- [ ] Improve Cloud SQL Server single write bottlenecks to improve Forseti Inventory performance
- [ ] Break apart the storage class into storage writer (use sqlalchemy core, optimize for fast bulk writes) and the storage reader class, which can remain using ORM as it does today.
- [ ] Update inventory and crawler initialization to use the new writer class with a a sqlalchemy engine that maintains a pool of connections shared between threads, and not use a global session object.
- [ ] Update the ParallelCrawler class to to not use a global lock on writes and updates.	
- [ ]  Optimize the writer class to have fewer SQL calls, optimize for bulk writes and few or no updates. Updates should be an exception, and strongly discouraged in code or removed completely (also needed for BigQuery streaming writer eventually).

**Comment by ahoying** [comment]
Additional work completed in PR #3068. Closing issue.
