### ISSUE TITLE
Increase Default Forseti VM size 

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3059]
- [x] Recommend new default Forseti VM size eg. (8 CPU / 8 GB RAM / 50 GB SSD) 
- [x] Add support during deployment with Terraform config options
- [ ] Document recommend Terraform settings for customer size (simple table 100k vs 1M)

**Comment by dekuhn** [comment]
Updated VM disk to 100GB SSD.

**Comment by joecheuk** [comment]
Addressed in the PR above.
