### ISSUE TITLE
Increase Default Cloud SQL size

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3060]
- [ ] Recommend new default Cloud SQL size
  - [ ] Need some bench-marking data to answer the changes to recommended size.
- [ ] Document recommend Terraform settings for customer size (simple table 100k vs 1M)

**Comment by dekuhn** [comment]
Need profile data results from #3058 to recommend new default sizing

**Comment by joecheuk** [comment]
addressed in the PR above
