### ISSUE TITLE
Profile and optimize process when building Inventory Model

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3062]
Profile the Inventory Model process and look to where we can optimize the processing performance time for GCP orgs with large numbers of resources.

**Comment by blueandgold** [comment]
@joecheuk Please resolve this based on your work here.

**Comment by joecheuk** [comment]
After profiling, the inventory process is the bottleneck and the model performance is acceptable at this moment, e.g. with 7 hours of inventory time it will take roughly 1-2 hours to build the model.
