### ISSUE TITLE
GCP API Error - The caller does not have permission

### ISSUE THREAD

**Issue by Ameurdx** [forseti-security/forseti-security#3076]
Hi,
I have installed forseti on a Folder (from Non-Organization Root)
i have make all the instruction here https://forsetisecurity.org/docs/latest/configure/general/non-org-root.html.

The problem is that when i do inventory i get PARTIAL_SUCCESS.
then it show that the there is a problem with the API Authentication

Thanks and sorry for my bad English!

{
  "inventory": {
    "id": "XXXXXXXXX",
    "startTimestamp": "2019-08-13T13:25:55Z",
    "completeTimestamp": "2019-08-13T13:26:09Z",
    "schemaVersion": 1,
    "countObjects": 52,
    "status": "PARTIAL_SUCCESS",
    "warnings": "GCP API Error: unable to get folders_sinks, name = folders/YYYYYYYY, from GCP:\n<HttpError 403 when requesting https://logging.googleapis.com/v2/folders/YYYYYYYYY/sinks?alt=json returned \"The caller does not have permission\">\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"The caller does not have permission\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n\n\nGCP API Error: unable to get folders/YYYYYYYYYYY from GCP:\n<HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v1/folders/YYYYYYYYYYYYY:listOrgPolicies?alt=json returned \"The caller does not have permission\">\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"The caller does not have permission\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n\n\n GCP API Error: unable to get folders/YYYYYYYYYYYYY from GCP:\n<HttpError 403 when requesting https://cloudresourcemanager.googleapis.com/v2/folders?parent=folders%2FYYYYYYYYYYYY&showDeleted=false&alt=json returned \"The caller does not have permission\">\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"The caller does not have permission\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n\n\n",
    "errors": ""
  }
}

![Inked2019-08-13 15_45_19-IAM – IAM   admin – test-projekt-gcp – Google Cloud Platform_LI](https://user-images.githubusercontent.com/13125822/62946933-ea6fd680-bde1-11e9-9823-5efa3f0b1fa0.jpg)

![Inked2019-08-13 15_50_58-New Issue · forseti-security_forseti-security_LI](https://user-images.githubusercontent.com/13125822/62947532-fad48100-bde2-11e9-8a28-3775530787be.jpg)
![Inked2019-08-13 15_53_23-a_meddeb_goreply_de@forseti-client-vm-54b017a_ ~_LI](https://user-images.githubusercontent.com/13125822/62947533-fad48100-bde2-11e9-925d-11f71fc235b7.jpg)

**Comment by kevensen** [comment]
Hi @Ameurdx 

Thanks for submitting this issue.  The screen shots are helpful.  Could you please provide the following information:

1. Was Forseti installed by a user with "Org Admin" credentials?

2. Did you install Forseti via the Python Installer or Terraform Installer?

**Comment by Ameurdx** [comment]
Thank you @kevensen 
Forseti was installed by a Folder Admin (that's why No-Organi Root install)
i have installed Forseti via Python installer (The tutorial just show how to do it with Python , not with Terraform ...)

https://forsetisecurity.org/docs/latest/configure/general/non-org-root.html

**Comment by kevensen** [comment]
@Ameurdx Thank you for the clarification.  I am spinning up a new Forseti environment to recreate this scenario.

**Comment by kevensen** [comment]
@Ameurdx I have been able to recreate this issue.  The screen shot you provided lists the correct IAM permissions.  However, they appear to be applied at the project level.  This is the default behavior when installing Forseti without Org Admin credentials as you noted you did not have.

Step 4 of the [Configure Forseti to Run on a Folder](https://forsetisecurity.org/docs/latest/configure/general/non-org-root.html#configure-forseti-to-run-on-a-folder) indicates that the [permissions granted at the organization level](https://forsetisecurity.org/docs/latest/concepts/service-accounts.html#permissions) (when the root resource ID is an organization) must be applied to the "target resource".

When I first read that, I was admittedly a little confused.  But the "target resource" in this case is your folder.  Once I applied those IAM permissions to the folder root resource, this issue cleared up.

Please let me know if applying the IAM permissions to your folder resolves your issue.

**Comment by Ameurdx** [comment]
I appreciate your help!  @kevensen
thank you

**Comment by kevensen** [comment]
@Ameurdx My pleasure.
