### ISSUE TITLE
Automate Inventory Performance Testing

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3078]
## Story
Automate performance testing of Forseti inventory creation by processing a large CAI export.

## Proposed Solution
Use mock CAI exports to be processed by Forseti to create inventory.

## Acceptance Criteria
- The inventory should take less than 12 minutes to complete.
- The resource counts should match the expected values in the inventory table.

**Comment by dekuhn** [comment]
In the interim we have manual load test documented.
