### ISSUE TITLE
Find Common Members Among a Set of Google Groups

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3085]
Just an idea here that would help with group management.

**Comment by kevensen** [comment]
@blueandgold  Where would the implementation go?  Are you thinking a new scanner?  Or a utility method somewhere?

Given a list of groupds  --> return --> list of users that are common to all groups in the list

**Comment by blueandgold** [comment]
A scanner would be best for this.  But at this point, I don't think there is any interests, so will close this.
