### ISSUE TITLE
Update Forseti deployment to support custom disk sizing and type for Terraform installations

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3089]
- [x] Add support to Forseti Terraform to customize both disk size and type (HDD vs SDD)
- [x] Increase the current deployment default disk size and format to SSD / 100GB
- [ ] Update the Forseti on GKE deployment to mirror these same changes.

**Comment by dekuhn** [comment]
Reopening so we add these same changes for the Forseti on GKE example. 

@kevensen FYI

**Comment by gkowalski-google** [comment]
Closing this out, created separate ticket in the terraform repo for the GKE change: https://github.com/forseti-security/terraform-google-forseti/issues/368.
