### ISSUE TITLE
Deprecation of docker_entrypoint.sh

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3093]
The configuration of the execution behavior of Forseti on GKE can and should be done via Kubernetes.  Altering the docker_entrypoint.sh script, thus changing the execution behavior, can inadvertently break the deployment in Kubernetes.  If a breaking change were made here, at the very least, the Helm charts would need to be updated.  This means making changes in two repos.

**Comment by kevensen** [comment]
This is still worth fixing

**Comment by gkowalski-google** [comment]
Keep
