### ISSUE TITLE
Auto-close stale issues

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3097]
- [x] Create and check-in stale-bot configuration
- [x] Enable stale-bot GitHub to begin processing

As a maintainer of Forseti, I would like a GitHub bot to automatically close stale issues older than 90 days in order to help manage the backlog.

Important issues can either be re-opened or a new issue can be created.

**Comment by hshin-g** [comment]
Needs to be integrated into dev branch to get stale-bot to work.

Need to make a sweep of all old issues to make sure they are not closed prematurely by stale-bot and reprioritize issues.

**Comment by dekuhn** [comment]
Reviewed issues in scope of stalebot settings with @blueandgold today. We enabled Stalebot on the Forseti-Security repo. May take an hour before it starts processing.

**Comment by dekuhn** [comment]
@blueandgold not seeing stale bot processing of issues. Need to figure out how to debug what is going on. I can only assume some configure parsing or issue there.

**Comment by dekuhn** [comment]
yaml format issues I think are preventing the bot from running. Just fixed yaml format issue with PR https://github.com/forseti-security/forseti-security/pull/3339
