### ISSUE TITLE
Remove GCS as a datastore

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3103]
As a user of Forseti I want to use a git repo as a store for my config files and rules in order to take advantage of true version control and git-sync to keep my files up to date.

**Comment by blueandgold** [comment]
+1 This has been asked by other customers before as well.  We have to think how to best organize & structure our repo(s) for best maintenance.  I made a comment to Gregg's design doc on this last night, and had a further chat with Gregg.  So, he has some ideas that he can propose here.  @gkowalski-google

**Comment by kevensen** [comment]
As I mentioned in the doc, I'll mention here for posterity.  The config-validator can be and is used independently of Forseti.  It follows that the policy-library can be and is used independently of Forseti.  Therefore we should keep the policy library separate from the "forseti-config" repo.

We can, however, accomplish the effect with the use of git-submodules.  For example

policy-library
|\libs
\policies

forseti-confg (repo)
|\ rules (folder)
|\ configs (folder)
\ policy-library (submodule)
  |\ libs
  \ policies

**Comment by blueandgold** [comment]
@gkowalski-google have confirmed with the Config Validator PM and Terraform Validator team @morgante that all the validator clients will be using the same repo.  So in this model, pulling in the policy library repo into the forseti repo is the right approach.

**Comment by kevensen** [comment]
Given recent conversations, customers may have a preference to use GCS.  Git repositories may be on-prem and without a VPC or Interconnect, using Git as a datastore is not a practical solution.
