### ISSUE TITLE
Scanner errors when running: "forseti scanner run" command

### ISSUE THREAD

**Issue by erikwalker** [forseti-security/forseti-security#3106]
- [ ] Fix IapScanner
- [x] Fix KeScanner (v2.21)
- [x] Fix KeVersionScanner (v2.21)
---

Installed forseti with terraform "Terraform v0.11.13"
The version of forseti security that is installed is:
__version__ = '2.18.0'
__package_name__ = 'forseti-security'

Having problem running forseti scanner:

when running "forseti scanner run":

The error output from the client is:

{
  "serverMessage": "Error running scanner: IapScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 682, in run\n    all_violations, _ = self._find_violations(iap_data)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 667, in _find_violations\n    for (iap_resources, project_resource_counts) in iap_data:\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 645, in _retrieve\n    instance_templates=instance_templates)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 95, in __init__\n    instance_template_url)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/instance_template.py\", line 158, in from_url\n    url)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/key.py\", line 109, in _from_url\n    path_components = urllib.parse.urlparse(url)[2].split('/')[3:]\nTypeError: a bytes-like object is required, not 'str'\n'"
}
{
  "serverMessage": "Running InstanceNetworkInterfaceScanner..."
}
{
  "serverMessage": "Error running scanner: KeScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n    ke_clusters = self._retrieve()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n    parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'"
}
{
  "serverMessage": "Error running scanner: KeVersionScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n    ke_clusters = self._retrieve()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n    parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'"
}

Please let me know what to check or if I need to pull a new version. I just installed about 1 month ago.

**Comment by kevensen** [comment]
Hi @erikwalker.  Thank you for reporting this issue.  We might have a couple of different problems here.  The first appears to be a string conversion error in the IAP scanner.  The second is with the KE version scanner.

If you could please answer a few questions, it will help provide me some context.

1. There is a new version, 2.19.0.  However, I don't see any updates between the two versions that would impact this issue.  In any case, do you mind attempting an update?

2. Do you have CAI enabled in the server config?

3. Are there any other errors in the Stackdriver log  

4. For background, did you install via the Python installer or Terraform?

**Comment by kevensen** [comment]
I am now seeing the second error in testing.

**Comment by erikwalker** [comment]
Hi @kevensen. Thanks to answer your questions. 
1. Ah i have not attempted newer update yet but could if it turns out to make a difference.
2. Have not enabled CAI on the server config because currently have installed and deployed on non-org root folder
3. I don't seem to have any other errors in the stackdriver log that could be related to this problem.
4. It was deployed with terraform v11

**Comment by erikwalker** [comment]
@kevensen  So i updated the CAI configuration to be "false"  and reloaded the configuration and restarted the server. 
When I run "forseti scanner run" I seem to have the same errors as above.

So I don't think having CAI as true or false is making a difference with the error. I will put back to "true" since this is the value that was provided when installing with terraform. Unless you advise differently.

**Comment by kevensen** [comment]
@erikwalker Thank you for the additional information and trying those suggestions.

When you set the CAI to false and restarted the server, did you create a new inventory model?

When I disabled the CAI, recreated the model and inventory, the issue went away (obviously not the fix).  But I'd like confirmation.  For moment, I am interested in the ke_base_scanner.

**Comment by mschlanser** [comment]
I'm seeing the same error on the Kubernetes scanner.  Anything I can do to resolve this?

Thanks,
Mike

**Comment by erikwalker** [comment]
@kevensen yes i will try your suggestion and revert back

**Comment by erikwalker** [comment]
@kevensen Actually after setting CAI to false and creating a new model and inventory I am still seeing the same errors as above.

**Comment by hshin-g** [comment]
@red2k18 Can you follow up on this issue?

**Comment by erikwalker** [comment]
Hi, i have not had much luck with other config settings. I am wondering is their a way with the forseti cli to debug the inventory batch job ? Perhaps maybe i can get some more detailed information on the inventory errors.

**Comment by hshin-g** [comment]
@erikwalker You can try to set the log level to debug to see if that helps to troubleshoot:

`forseti server log_level set debug`

**Comment by erikwalker** [comment]
Yes okay i am trying to debug. Thanks

**Comment by gkowalski-google** [comment]
Hi @erikwalker, were you able to get any more helpful info with debug mode? I believe I have a fix for the Kubernetes Scanners, and will start looking into the IapScanner issue this week as well.

**Comment by erikwalker** [comment]
@gkowalski-google  Okay great. I presume I will be just update my existing install. Or will I need to do fresh install with terraform ?

**Comment by erikwalker** [comment]
> Hi @erikwalker, were you able to get any more helpful info with debug mode? I believe I have a fix for the Kubernetes Scanners, and will start looking into the IapScanner issue this week as well.

I was not actually able to get any new pertinent information from debug.

**Comment by erikwalker** [comment]
@gkowalski-google I need to update forseti with terraform. Do you know if the changes have been added to the terraform-google-forseti repor (https://github.com/forseti-security/terraform-google-forseti)  ?

**Comment by gkowalski-google** [comment]
@erikwalker The fixes for the Kubernetes scanners will be included in the release going out this week. I will ping you on this ticket once it is ready.

**Comment by erikwalker** [comment]
@gkowalski-google Alright sure. i will hold off on the update. I am following instructions from this page: https://forsetisecurity.org/docs/latest/setup/upgrade.html#zippy-1
We are currently on 2.18.0 version. I would imagine it will probably be release 2.21.0. While updating from 2.18.0 to 2.19.0. I did get this error in my console while running terrraform init:

![image](https://user-images.githubusercontent.com/19658505/64989042-b5e8b200-d89a-11e9-9501-5951f27dc11c.png)

**Comment by gkowalski-google** [comment]
Hi @erikwalker, I think this might be due to a breaking change that was part of [v4.0.0 of the  Forseti Terraform module](https://github.com/forseti-security/terraform-google-forseti/blob/master/CHANGELOG.md#v400---2019-08-07). Can you please follow the [upgrade instructions](https://github.com/forseti-security/terraform-google-forseti/blob/master/docs/upgrading_to_v4.0.md), make sure to [upgrade Terraform 0.12.x](https://www.terraform.io/downloads.html), and let me know if that helps?

**Comment by erikwalker** [comment]
Okay i will check. Thanks

**Comment by gkowalski-google** [comment]
@erikwalker The Kubernetes Scanner fixes have been released as part v2.21.0.

**Comment by erikwalker** [comment]
@gkowalski-google Okay thanks I will arrange for upgrade.

**Comment by erikwalker** [comment]
@gkowalski-google We need to finish upgrades to tf 12 as we are using tf 11 still for most of our code. So I cannot do the upgrade right now. Please go ahead an resolve the issue for now and I can reopen later if I encounter problems with the KE scanner.

**Comment by gkowalski-google** [comment]
Assigning to @blueandgold, I have not had a chance to look into the issue with the IapScanner.

**Comment by blueandgold** [comment]
@erikwalker @gkowalski-google Regarding the IAP scanner error, I looked into this, and can not reproduce in my environment.

Upon researching, the actual message might be misleading.  Per this [SO response](https://stackoverflow.com/a/56241023/2830207), it seems that a byte type was passed in, where the function in question is expecting a string.
```
path_components = urllib.parse.urlparse(url)[2].split('/')[3:]
```

At this point, I would like to schedule a hangout with you, to debug the problem on your Forseti Server VM, and see what kind of data is actually being used here.  My schedule is US West Coast 8am to 4pm.  Please let me know what time works for you.

Thanks.

**Comment by erikwalker** [comment]
@blueandgold @gkowalski-google  Ah, our team is very small and have not yet completed terraform update to v12. So we have not yet taken in the most current release.  So the IAP scanner might not be a problem afterwards. I have logged all suggestions and will retest all the scanner functionality after we take in the release. So I believe you can go ahead and resolve this issue. Thanks for your help.

**Comment by blueandgold** [comment]
Thanks @erikwalker.  Please let us know again if you have any issues.  We are also on slack, so you can reach out to us there.  https://forsetisecurity.slack.com/
