### ISSUE TITLE
Remove session usage in Storage class in storage.py

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#3107]
Executing sql commands directly using the engine is sufficient.

**Comment by hshin-g** [comment]
@joecheuk Is this issue addressed?

**Comment by joecheuk** [comment]
No this is not addressed

**Comment by dekuhn** [comment]
Joe can you add a bit more context to the title and description. In our triage of this issue we did not have enough detail to understand the work.

**Comment by joecheuk** [comment]
With the updated changes, when writing to the database (for the inventory module), we no longer need to use a session to hold the connection to the database. Instead we have been executing SQL queries directly using the sql engine. We have not however removed all the use of session in the inventory module yet, those are be removed and replaced with executing sql queries using the engine.
