### ISSUE TITLE
Update Forseti Docker Container

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3109]
One of the reason the website build speed is slow, is because the docker container is out of date, and can be updated to improve the website build speed.  These are the 2 files can need to be updated.

https://github.com/forseti-security/forseti-security/blob/master/install/docker/base
https://github.com/forseti-security/forseti-security/blob/master/install/docker/forseti

**Comment by mirons-google** [comment]
@blueandgold it should be noted that the docker container isn't out of date but all of the actions take within it needed audited for the need relative to their contribution to the build time.

It should also be noted this is the same container for which Travis uses for unittests and linting of the application code and therefore should be considered carefully.

**Comment by kevensen** [comment]
@mirons-google Just FYI, the Docker container image used for unittests and linting is now derived from the Dockerfile in the root of the repository and not these files.  These files are actually slated for deprecation on 9/30 per https://github.com/forseti-security/forseti-security/blob/dev/install/docker/README.md.

I do agree that using this same container image for the purpose of building the website runs afoul of container image patterns.

**Comment by kevensen** [comment]
This is the file that should be updated if anything and should not be based on the Forseti container image.  https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org-dev/scripts/docker/generate_sphinx_docs.Dockerfile

**Comment by red2k18** [comment]
Tried using a docker container image different from the one used for linting and unit tests, but it is adversely impacting the website build time. Closed [PR](https://github.com/forseti-security/forseti-security/pull/3537) and closing this issue.
