### ISSUE TITLE
Optimize Website Build with include_cached

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3110]
Instead of just using `include`, we should be using `include_cached` where possible to optimize the website build.

**Comment by mirons-google** [comment]
@blueandgold it should be noted the implications of using cached and where it can help.

Optimizations should be prioritized by running jekyll build with --profile so see liquid inefficiencies. Those should be tackled separately.

[Here's](https://forestry.io/blog/how-i-reduced-my-jekyll-build-time-by-61/) an example of a methodical approach to improving the build time using various strategies (there are many out there).

@blueandgold I would suggest we re-title this issue to be general speed improvements with a checklist of many items to do, one of them being the careful application of include_cached.

**Comment by red2k18** [comment]
Closing this issue as several improvements have been made resulting in 92.5% improvement in the build time on Travis.

Original Build time on Travis: 20 minutes
New build time on Travis: [1.5 minutes](https://travis-ci.org/forseti-security/forseti-security/builds/626802711?utm_source=github_status&utm_medium=notification) 
Local testing: 4 seconds
