### ISSUE TITLE
Improve Website Build for Non-Admin PRs

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3111]
When non-admin contribute PRs for the website, the build should only do the following:
- jekyll build
- htmlproofer

**Comment by gkowalski-google** [comment]
@blueandgold Was this resolved as part of the work that @dekuhn completed?

**Comment by blueandgold** [comment]
@gkowalski-google AFAIK, this work has not been done yet.  I'll put this on the backlog, and we can put it in the right sprint.

**Comment by red2k18** [comment]
This issue has been fixed as part of the recent work to speed-up the website build time on Travis. 

[This build](https://travis-ci.org/forseti-security/forseti-security/builds/626802711?utm_source=github_status&utm_medium=notification) shows that only Jekyll is built and htmlproofer is run for every PR (including the one's submitted by non-admin).
