### ISSUE TITLE
Website Images Should Use Proper Tags

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3112]
The proper way to use image tags is below, so the images resize properly:
```
{% responsive_image path: images/docs/concepts/forseti-architecture.png alt: "forseti architecture" %}
```
Audit everything in our doc, and make sure all images use this tag.

**Comment by red2k18** [comment]
`responsive_image` tags is already being used for all the images in `.md` files. Enable caching for all the images and disabled saving the files to the source folder. 

#3507 addresses this.
