### ISSUE TITLE
bigquery violations is not working after install v2.18

### ISSUE THREAD

**Issue by marciosian** [forseti-security/forseti-security#3121]
I am using the default rule configuration for big query violations.
I have opened one dataset to public using allUsers, allAuthenticatedUsers and shared with @gmail 
It has worked in v2.12

But i got :
[forseti-security][2.18.0] google.cloud.forseti.notifier.notifier(run): Resource 'bigquery_acl_violations' has no violations
-----
forseti_conf_server.yaml:
    scanners:
        - name: bigquery
          enabled: true
-----
rules:
  - name: BigQuery rule to search for public datasets
    mode: blacklist
    resource:
      - type: organization
        resource_ids:
          - 'my organization id'
    dataset_ids: ['*']
    bindings:
      - role: '*'
        members:
        - special_group: 'allAuthenticatedUsers'
-------

I have no error in my logs

**Comment by kevensen** [comment]
Hi @marciosian.  Thank you for bringing this issue to our attention.  One thing we might try is making the logs more verbose.

On the Forseti client VM, can you please run:

`forseti server log_level set debug`

Then run the scanner and notifier again?

**Comment by marciosian** [comment]
Hi again, 

Nothing weird in logs , just informations like:
[forseti-security][2.18.0] google.cloud.forseti.common.gcp_api.bigquery(get_tables): Getting tables for the project **** and dataset

**Comment by hshin-g** [comment]
@red2k18 Can you follow up on this issue?

**Comment by gkowalski-google** [comment]
Assigning to @blueandgold, I have not had a chance to look into this.

**Comment by blueandgold** [comment]
Hi @marciosian, I looked into your issue.  Per the rule that you provided, the violation it will find is specifically for a dataset policy that grants access like this:
```
{"role": "READER", "specialGroup": "allAuthenticatedUsers"}
```
Can you please verify that your dataset is indeed looks like this?  Because I tested this in my environment, and it is working.

Please let me know.  Thanks.

**Comment by gkowalski-google** [comment]
@marciosian Have you had a chance to look into the last comment? Please let us know if this is still an issue.

**Comment by red2k18** [comment]
Hi @marciosian, following up to see if you had a chance to check what your dataset looks. We need this to be able to investigate further. Thanks!

**Comment by red2k18** [comment]
I'm closing this issue as we haven't heard back in a while. Please feel free to reopen this issue with more information.
