### ISSUE TITLE
Scanner hang up after a long run

### ISSUE THREAD

**Issue by hariram01** [forseti-security/forseti-security#3123]
Hey Forseti Team

I installed Forseti V2.19 via deployment Manager. Inventory creation has been completed after 25 days but scanner is not auto execute. 

I started scanner couple of times but every time it hang up and violations table is also empty. 

Thanks!
Hari

**Comment by joecheuk** [comment]
This issue has been addressed offline as the RC version of Forseti will include a fix to this. Instead of writing to the database at the end of all the scanner runs, we are doing it per scanner now.
