### ISSUE TITLE
Implement smart threading improvements

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3126]
- [ ] Start pulling gsuite resources as soon as inventory starts, do not wait for CAI export to complete.
- [ ] Remove blocking API calls from the visit() function and move them all into child resources
- [ ] Aggressively fork API requests into a separate thread queue from CAI sourced data

**Comment by ahoying** [comment]
1) Start pulling gsuite resources as soon as inventory starts, do not wait for CAI export to complete.
2) Remove blocking API calls from the visit() function and move them all into child resources
3) Aggressively fork API requests into a separate thread queue from CAI sourced data

**Comment by dekuhn** [comment]
Analysis shows little time gain kicking off GCP API gathering before CAI. This work would only gain us a few mins improvement. 

Closing as Will not Fix.
