### ISSUE TITLE
Define config validator upgrade process

### ISSUE THREAD

**Issue by t12g** [forseti-security/forseti-security#3140]
This is a feature request.

Config validator exists as a binary under the [external dependencies directory](https://github.com/forseti-security/forseti-security/tree/dev/external-dependencies/config-validator). Upgrading to a new version is ad hoc. We should define and automate an upgrade process. As part of the process, it should also stamp the config validator version in Forseti's user agent string. Currently when config validator is enabled, the [user agent string ](https://github.com/forseti-security/forseti-security/blob/3e489059bc5b3049e6671a8e45cb32b9bd0730ea/google/cloud/forseti/services/base/config.py#L469) only includes "config-validator" and not the versioning information.

**Comment by gkowalski-google** [comment]
@red2k18 For this issue, can we document any steps necessary on the website to upgrade to a new version of CV?

**Comment by red2k18** [comment]
I see that the steps to install and upgrade CV are missing on the website and in the CV repo. I think this is something that should be documented. Do you know if the steps are documented elsewhere (internal documentation)?

**Comment by gkowalski-google** [comment]
Document how to manage the CV protos based on CV version.

**Comment by gkowalski-google** [comment]
Versions of CV newer than the default value included use OPA 0.17.x, which is not compatible with some of the policies. Document this with the CV website docs.
