### ISSUE TITLE
Compute Engine Resource: Image Creation Time checks

### ISSUE THREAD

**Issue by GitJumpin** [forseti-security/forseti-security#3142]
Feature request to include Compute Engine resource checks, including Image Creation Time as a criteria to validate.

Idea is to have no VMs running that have an image >30 days. If one exists, produce finding.

**Comment by hshin-g** [comment]
@red2k18 Can you do a high level scoping of this work (is this a new scanner / updating an existing scanner / config validator rule)?

**Comment by dekuhn** [comment]
@GitJumpin can you describe in more detail the business use case you are trying to solve for? Is purely a 30 day old image file? Or would looking at image type or family more useful than just creation time?

e.g. example image / family
Image: ubuntu-1804-bionic-v20190813a
Image family: ubuntu-1804-lts

**Comment by gkowalski-google** [comment]
Hi @GitJumpin, please see @dekuhn's questions above. We will consider adding this, just want to make sure it is done right.

**Comment by dekuhn** [comment]
@GitJumpin we have not heard back from you in 2 weeks. Closing the issue for now. Please reopen and provide us more details about the business use case so we can consider how to best consider this feature request.
Thanks!
