### ISSUE TITLE
Unable to perform unit tests locally on updated code

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3143]
As a developer of Forseti I want to be able to edit code and copy it to the running docker container so that I can efficiently perform unit and pystyle tests as described [here](https://forsetisecurity.org/docs/latest/develop/dev/testing.html#update-code-and-re-run-test).

**Background:**
When files are copied to the running container via `docker cp` they retain the uid:gid ownership that they have on the host.  That means if a file is owned by UID 2000 on the host running the container, the file, when copied, will retain that UID.

Previously this wasn't a problem because the containers ran as root.  Now that containers run as less privileged users with UID 1000, the unit tests run fine only when the container is rebuilt and restarted.

Why wasn't this determined before?  When I redid the containers, I did not test all the concepts on the [develop/testing](https://forsetisecurity.org/docs/latest/develop/dev/testing.html#testing) page of the  Forseti Security docs.

**Resolution**

This can be fixed in the docker scripts by building the containers with a different UID when not built in TravisCI using the `ARGS` directive in the Dockerfile.  The default UID and GID will be 1000.  But when run on the hosts, the Docker scripts will use the UID and GID of the current user on the host.

**Comment by hshin-g** [comment]
@kevensen Is this already done?

**Comment by kevensen** [comment]
It is now!
