### ISSUE TITLE
Firewall exceptions

### ISSUE THREAD

**Issue by GitJumpin** [forseti-security/forseti-security#3144]
Feature Request: Due to the nature of the firewall rules, creating a firewall rule to trigger on "allow all ingress" creates findings from GKE. GKE dynamically creates FW rules with this ruleset, and we would like to create an exception based off of rule name. An example of how this might look would be as follows;

```
  - rule_id: 'prevent_allow_all_ingress'
    description: Detect allow ingress to all policies
    mode: blacklist
    match_policies:
      - direction: ingress
        allowed: ['*']
        exception: ['gke-*']
    verify_policies:
      - allowed:
        - IPProtocol: 'all'
```

**Comment by hshin-g** [comment]
@red2k18 Can you do a high level scoping / troubleshooting for this issue?

**Comment by red2k18** [comment]
This is a feature request. Firewall rules today doesn't allow specifying exceptions. This use case is currently not supported in Forseti. It's a nice feature to have.

**Comment by gkowalski-google** [comment]
@GitJumpin Thanks for the feature request. We recommend you try out Config Validator which has a firewall rule template, and [soon will support exceptions](https://github.com/forseti-security/policy-library/pull/211).
