### ISSUE TITLE
Update all GitHub references from old repo GoogleCloudPlatform/forseti-security to new org repo.

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3149]
We still have a lot of out dated references to https://github.com/GoogleCloudPlatform/forseti-security repo. 

GitHub redirects automatically, but we should replace references in our code to the new org path and repo name.

Action: Update all GitHub references from https://github.com/GoogleCloudPlatform/forseti-security to https://github.com/forseti-security/forseti-security

e.g. https://github.com/forseti-security/forseti-security/search?q=GoogleCloudPlatform%2Fforseti-security&unscoped_q=GoogleCloudPlatform%2Fforseti-security

https://github.com/forseti-security/terraform-google-forseti/search?q=GoogleCloudPlatform%2Fforseti-security&unscoped_q=GoogleCloudPlatform%2Fforseti-security

**Comment by red2k18** [comment]
https://github.com/forseti-security/forseti-security/pull/3182 addresses this.

**Comment by dekuhn** [comment]
@red2k18 Is there a PR to address the Terra-form repo as well? Maybe I missed it?

**Comment by red2k18** [comment]
#3182 updates all the references in forseti-security repo. Will submit another PR to update the references in terraform-google-forseti repo.

**Comment by red2k18** [comment]
Opened https://github.com/forseti-security/terraform-google-forseti/pull/248 to update references in terraform-google-forseti module.
