### ISSUE TITLE
Verify Dev Environment Instructions

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3162]
The [dev environment setup instructions](https://forsetisecurity.org/docs/latest/develop/dev/setup.html) needs to be verified to make sure it's up-to-date, consistent, and repeatable. Instructions for both ubuntu and mac should be verified.

The verification should be done with Virtual Machines. For ubuntu, this can be done on GCP.  For mac, Virtual Box is good.

@dekuhn has PR #3147 to update some instructions, and this needs to be verified.

Relates to #2729.

**Comment by gkowalski-google** [comment]
Keep
