### ISSUE TITLE
Website build issue on linux

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#3183]
`Pull access denied for forseti/generate_sphinx_docs, repository does not exist or may require 'docker login'`

This error message was thrown while running `./scripts/generate_sphinx_docs.sh release-2.20.0`

**Comment by gkowalski-google** [comment]
Were you able to workaround this with the last release? If so, how did you do that?

**Comment by dekuhn** [comment]
@red2k18 can you provide any details as to the workaround or way you resolved this with the last release.

**Comment by red2k18** [comment]
`sudo apt-get install jq` did the trick for me.

**Comment by gkowalski-google** [comment]
This is related to a minor change to the docker file. I have updated the release documentation.
