### ISSUE TITLE
Additional check in startup-script (no EXTERNAL IP/Cloud NAT) & functionality with Private Access

### ISSUE THREAD

**Issue by ttodo-softserve** [forseti-security/forseti-security#3186]
When installing Forseti without internet connection startup-script removes the Python modules and removes the installation. Due to missing internet connection afterwards it can't be installed/upgraded. Additional check in the script will be useful before removing the product.

Python3 modules 

Before restart :
root@forseti-client-vm-88ca767:~# pip3 list | wc -l
104

After restart : 
root@forseti-server-vm-88ca767:~# pip3 list | wc -l
80

Startup-script attached.

Question : if we reinstall the product and remove the startup script will it be safe or some part of the install process will attach it later again?

[startup-script.zip](https://github.com/forseti-security/forseti-security/files/3596571/startup-script.zip)

**Comment by gkowalski-google** [comment]
Hi @ttodo-softserve, thanks for submitting this issue. The startup script will get re-added if Terraform is run again to update/install.

Do you plan on adding a Cloud NAT? Any reason you did not add a Cloud NAT as part of the installation?

Forseti will not be able to work without one, since it has to make external calls to get Inventory data, amongst other things. If your process is to install Forseti, and then later go back and add a cloud NAT, then we can probably add in a check within the startup script to exit if there is no internet connection.

**Comment by ttodo-softserve** [comment]
@gkowalski-google - thank you for your inputs! Appreciated.
We will be careful when using the TF or restart instances.

As for the Cloud NAT - it's a policy on organizational level, unfortunately.

I was thinking that using VPC network + assign private IP to CloudSQL will overcome missing external IPs and missing cloud NAT, leaving us with non-patched installation but still fully functional.

Managed to setup the internal VPC + CloudSQL with internal IP and during creation of inventory I got this partially failed (looks like permission issue but let me know if not) : 

Please help me understand - what else will not work if there is no Cloud NAT, no external IPs + using VPC and Private CloudSQL ?

    "status": "PARTIAL_SUCCESS",
    "warnings": "GCP API Error: unable to get groups from GCP:\n<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/groups?customer=C02uoh0ff&alt=json returned \"Not Authorized to access this resource/api\">\n{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"forbidden\",\n    \"message\": \"Not Authorized to access this resource/api\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Not Authorized to access this resource/api\"\n }\n}\n\n\nGCP API Error: unable to get users from GCP:\n<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/users?customer=C02uoh0ff&viewType=admin_view&alt=json returned \"Not Authorized to access this resource/api\">\n{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"forbidden\",\n    \"message\": \"Not Authorized to access this resource/api\"\n   }\n  ],\n  \"code\": 403,\n  \"message\": \"Not Authorized to access this resource/api\"\n }\n}\n\n\n",

**Comment by gkowalski-google** [comment]
HI @ttodo-softserve, if the Forseti server cannot access the internet, then it will have the following issues:
- Inventory: API calls to CAI or GCP APIs will fail, and this will prevent any inventory data to be collected.
- Scanner: Should be fine, this between server and db
- Notifier: Email, Slack, CSCC notifications will fail as these all rely on access to public internet

The error you mention above looks like it is due to not configuring G Suite to allow Forseti to connect. [Please follow these steps](https://forsetisecurity.org/docs/latest/configure/inventory/gsuite.html).

As for the Cloud NAT policy, let me look into this some more to see if there is anything we can do. We are planning on releasing the Alpha version of the Real Time Scanner next quarter (hopefully early in the quarter). I'm not 100%, but it's possible that we would be able to use that for scanning without public internet access. This would scan resources as changes are made, but the periodic inventory/scans run by the cron job would still not work.

**Comment by ttodo-softserve** [comment]
@gkowalski-google , I would like to provide more details of the current status - where MySQL is accessible via internal IP, Private access is ON on the default network. 

Can you please advice which URL is Forseti trying to open in the scanner exception stack?
Any other comments are welcome - if the setup is with Private Access ON to run explain,inventory,model,scanner (notifier will be not OK as you mentioned).

I did a small script to check from the server instance access to the APIs :

for i in `gcloud services list | egrep -v "NAME|TITLE"`; do echo $i; curl -s https://$i/ > /dev/null; echo "Result $?"; done;

admin.googleapis.com
Result 0
appengine.googleapis.com
Result 0
bigquery-json.googleapis.com
Result 0
bigquerystorage.googleapis.com
Result 0
cloudapis.googleapis.com
Result 0
cloudasset.googleapis.com
Result 0
cloudbilling.googleapis.com
Result 0
clouddebugger.googleapis.com
Result 0
cloudresourcemanager.googleapis.com
Result 0
cloudtrace.googleapis.com
Result 0
compute.googleapis.com
Result 0
container.googleapis.com
Result 0
containerregistry.googleapis.com
Result 0
datastore.googleapis.com
Result 0
deploymentmanager.googleapis.com
Result 0
groupssettings.googleapis.com
Result 0
iam.googleapis.com
Result 0
iamcredentials.googleapis.com
Result 0
iap.googleapis.com
Result 0
logging.googleapis.com
Result 0
monitoring.googleapis.com
Result 0
oslogin.googleapis.com
Result 0
pubsub.googleapis.com
Result 0
securitycenter.googleapis.com
Result 0
servicemanagement.googleapis.com
Result 0
servicenetworking.googleapis.com
Result 0
serviceusage.googleapis.com
Result 0
sql-component.googleapis.com
Result 0
sqladmin.googleapis.com
Result 0
storage-api.googleapis.com
Result 0
storage-component.googleapis.com
Result 0

The ERRORs I see in the forseti log are : 

2019-09-16 12:51:36,187 INFO [forseti-security][2.19.1] google.cloud.forseti.scanner.scanner_builder(_instantiate_scanner): Initializing the rules engine:
Using rules: /home/ubuntu/forseti-security/rules/blacklist_rules.yaml
2019-09-16 12:55:57,008 ERROR [forseti-security][2.19.1] **google.cloud.forseti.services.scanner.service(_run_scanner): <urlopen error [Errno 110] Connection timed out>**
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out


2019-09-16 12:49:55,758 ERROR [forseti-security][2.19.1] google.cloud.forseti.services.inventory.base.resources(accept): **GCP API Error: unable to get users from** GCP:
<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/users?customer=C02uoh0ff&viewType=admin_view&alt=json returned "Not Authorized to access this resource/api">


2019-09-16 12:49:55,428 ERROR [forseti-security][2.19.1] google.cloud.forseti.services.inventory.base.resources(accept): **GCP API Error: unable to get groups from GCP:**
<HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/groups?customer=C02uoh0ff&alt=json returned "Not Authorized to access this resource/api">

**Comment by gkowalski-google** [comment]
@ttodo-softserve Thank you for digging into this! We know this is something that needs to get documented for others to setup. [We opened an issue recently to add a new Terraform example for a private deployment of Forseti](https://github.com/forseti-security/terraform-google-forseti/issues/254).

As for the URL that the Blacklist Scanner is attempting to hit, it is this: https://github.com/forseti-security/forseti-security/blob/dev/rules/blacklist_rules.yaml#L3. I will add a note to the issue mentioned above to ensure we look into working around this. I think it's OK to ignore this error for now. If you want, you can disable this scanner in the Forseti config.yaml file and you should not see that error anymore.

**Comment by ttodo-softserve** [comment]
@gkowalski-google - my bad for the users/groups exceptions. Did not recognize config is overwritten each time server runs. Now is OK - please ignore this.

Status so far (only internal and no internet connection) - inventory is collected, SQL is reachable. We have around 6000+ items in the inventory.

Issues : 

- SendGrid Email notification is not working as mentioned by you as well. Same setup with external IP/internet works - without has exception. Is it possible to use internal Google API for SendGrid?

- BlackList module though disabled still throws exceptions : 

  _- name: blacklist
          enabled: false_

 _File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.19.1-py3.6.egg/google/cloud/forseti/scanner/audit/blacklist_rules_engine.py", line 160, in get_and_parse_blacklist
    data = urllib.request.urlopen(url).read().decode('utf-8')
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>_

Question - has SCC connector been tested without external IPs?

**Comment by ttodo-softserve** [comment]
Just a note : I've tested and SCC connector is OK with only private IPs as per above thread.

**Comment by gkowalski-google** [comment]
Assigning to @blueandgold. @ttodo-softserve is trying to setup Forseti with no external IP or cloud NAT. The outstanding questions/issues are:

- SendGrid Email notification is not working as mentioned by you as well. Same setup with external IP/internet works - without has exception. Is it possible to use internal Google API for SendGrid?
- BlackList scanner is still throwing an exception when getting the blacklisted URLs, even though it is disabled. Why?

**Comment by blueandgold** [comment]
@ttodo-softserve , if you made changes to the `forseti_conf_server.yaml` file, such as disabling the a scanner, you have to tell the server to reload the config.  Please run this command on the Forseti Server/Client VM:
```
forseti server configuration reload
```

As for using SendGrid, with private IP, this is something that we are looking into in #2946.  I will have to look into this and follow-up with a solution.

**Comment by ttodo-softserve** [comment]
@blueandgold - done it multiple times. Plus restart of the service.
It's minor issue, can be ignored for now.

How can all email notifications be disabled since SendGrid will not work anyhow without internet access?

**Comment by blueandgold** [comment]
Hi @ttodo-softserve, if want to disable email notifications, you can do update the `notifier` section of the `forseti_conf_server.yaml` file like below.  (note: you will have to update the source file that is stored in GCS, which is then pulled onto the Forseti server)

I will go ahead and close this issue.  But if you need any more help, please feel free to re-open.
Thanks.

![image](https://user-images.githubusercontent.com/6977544/66732190-b3cd3100-ee0f-11e9-88dd-8e6c029a1e26.png)
