### ISSUE TITLE
Is it possible to specify zone and not only region for terraform deployment ?

### ISSUE THREAD

**Issue by zarga5** [forseti-security/forseti-security#3194]
Release 2.18.0 deployed via Terraform

Hi, 

I'm using Terraform to install Forseti on GCP and noticed that i can only specify region to install Cloud SQL instance and 2 VMs (Server & client) but they are always created in different zone so traffic between VMs (for example based in europe-west1-c) and Cloud SQL (based in europe-west1-d) are not free ... :(
So is it possible to specify specific zone in terraform.tfvars file to have all of them in same zone ?
Because only inputs region existing in TF and not zone ... :(

Many thanks for your quick reply
Regards

**Comment by zarga5** [comment]
Hi gkowalski, many thanks for your quick reply !

Yes i think this part should be added soon to avoid to have Forseti splitted in 2 zones in the same region (VMs and Cloud SQL instance) to minimize traffic cost.

I tried to modify /module/server/main.tf by adding in setting part location_preference section to specify europe-west1-c but when i check result of _terraform plan_ command ,  i still have SQL instance in the same zone (europe-west1-d) as you can noticed in screen shot below 
![image](https://user-images.githubusercontent.com/47218799/64864380-40c97280-d637-11e9-887f-7a6deeeef76f.png)
Do you know where this current variable location_preference is stored ? 

Many thanks in advance for your help.
Best regards

**Comment by gkowalski-google** [comment]
@zarga5 You should be able to see it in the `terraform.tfstate` file, search for `location_preference`. Was this a new installation or an upgrade/apply in place? Perhaps it is being ignored for existing CloudSQL instances. I can do some testing on that.

**Comment by gkowalski-google** [comment]
I was able to move a CloudSQL instance by updating the location preference. If you manually move the instance and re-run terraform apply, does the instance get moved back to the old zone (europe-west1-d)?
