### ISSUE TITLE
[ Forseti 2.20 ] duplicated field Resource.data.ipprotocol in CAI export for GlobalForwardingRule

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [forseti-security/forseti-security#3209]
Hello
Since 2.20 Forseti CAI Export is generated a duplicated entry in json for GlobalForwardingRule : Resource.data.ipprotocol.
Can you correct please ?
See json sample file coming from my CAI dump file 
`{
  "name": "//compute.googleapis.com/projects/xxx-dtp/global/forwardingRules/xxx-preprod",
  "asset_type": "compute.googleapis.com/GlobalForwardingRule",
  "resource": {
    "version": "v1",
    "discovery_document_uri": "https://www.googleapis.com/discovery/v1/apis/compute/v1/rest",
    "discovery_name": "GlobalForwardingRule",
    "parent": "//cloudresourcemanager.googleapis.com/projects/262351850719",
    "data": {
      "IPAddress": "4.6.13.12",
      "IPProtocol": "TCP",
      "creationTimestamp": "2019-07-02T05:28:51.043-07:00",
      "description": "",
      "id": "2226998196531818732",
      "ipAddress": "4.6.13.12",
      "ipProtocol": "TCP",
      "loadBalancingScheme": "EXTERNAL",
      "name": "xxx-preprod",
      "networkTier": "PREMIUM",
      "portRange": "443-443",
      "selfLink": "https://www.googleapis.com/compute/v1/projects/xxx-dtp/global/forwardingRules/xxx-preprod",
      "target": "https://www.googleapis.com/compute/v1/projects/xxx-dtp/global/targetHttpsProxies/xxx-preprod-target-proxy"
    }
  }
}
`

**Comment by gkowalski-google** [comment]
Hi @jf-marquis-Adeo, an [issue](https://github.com/GoogleCloudPlatform/professional-services/issues/318) has been opened with the Asset Inventory tool for this. Is it OK to close out this issue and track within the GCP repo?

**Comment by jf-marquis-Adeo** [comment]
yes sure
thanks a lot
