### ISSUE TITLE
Sidebar in Contact Us Page Becomes the Main Content

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3210]
When the page is smaller, the `Contact Us` page seems to show the CLI commands sidebar as the main content.  The design should be improved here.

https://forsetisecurity.org/docs/latest/use/get-help.html

![image](https://user-images.githubusercontent.com/6977544/65059902-b0877800-d92b-11e9-84ec-42b083c9e743.png)

**Comment by gkowalski-google** [comment]
This is due to the Contact Us page being part of the Use section of the docs. Consider removing this from the Docs and making it a standalone page that would not show the CLI menu.

**Comment by joecheuk** [comment]
Low priority, will put it back to the backlog.
