### ISSUE TITLE
Naming Convention Scanner

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#3215]
The subject is fairly self-explanatory, but perhaps this is hard to implement. 

But I would want to simply(?) run regex matches against resource names. 

Effectively I could set up that for each resource type, e.g. buckets need to be named something like org-location-dev-bucket and create a regex that matches these variances. Then the scanner would run an inverse regex search and flag any bucket that does not match that regex.

**Comment by MartenvanWezel** [comment]
Perhaps a dumb idea but maybe a regex scanner can be even expanded slightly to parse the entire resource json for a number of things, you could even fairly easily detect if e.g. a specific resource has flag xyz if you're good enough at regex.

Performance might become a problem if you're too enthusiastic here..

**Comment by dekuhn** [comment]
@MartenvanWezel do we have a customer asking for this scanner feature?

**Comment by hshin-g** [comment]
This should be able to be done in a straightforward way as a Config Validator policy- would the customer be willing to contribute here?

**Comment by MartenvanWezel** [comment]
All of them. It's part of Security 101 on our Cloud Security Deliveries to have a good naming convention for resources in place. To check this is enforced is fundamental.

I might have a customer, yes.

**Comment by dekuhn** [comment]
@MartenvanWezel I don't want to just build something random here. I would like to ensure we build something that addresses a specific customer(s) use case and need. Someone we can validate the work with once we do it. 

Can you help provide requirements and guidelines that is recommend to customers that we can build a rule around.

1) What key resources do we want to scan for naming standard?
2) Is there a example or suggested naming standard we recommend as a starting point for the different resources?

**Comment by MartenvanWezel** [comment]
HI @dekuhn +cc @yunus 

To answer your question:

1/ All of them - we recommend to explicitly name every resource around established patterns so they can be easily found, checked by search for descriptive sub-elements etc.
2/ Yes - it's here: https://www.cloudconnect.goog/docs/DOC-34590 (we have a slightly updated version internally)

The core idea is as stated: it is highly recommended to use a standard naming pattern. It would be great to have a scanner that allows users to specify one regex per resource type and list any resources that do not have a regex-match. That would be the MVP.

v1.1 would be to provide suggested regexes to match the sheet from my item #2.

**Comment by yunus** [comment]
Here is my first draft: https://github.com/forseti-security/policy-library/pull/213

**Comment by dekuhn** [comment]
Thanks @yunus for the https://github.com/forseti-security/policy-library/blob/master/samples/gcp_enforce_naming.yaml

Closing.
