### ISSUE TITLE
SCC connector not updating new findings

### ISSUE THREAD

**Issue by ttodo-softserve** [forseti-security/forseti-security#3216]
Forseti version - 2.18.0

Issue : 
Test bucket violation created (read permissions to everyone). 
After run the email attached CSV report do recognize and report it as violation.

In SCC it's shown as new asset (aka seen and refreshed inventory) but the violation (findings) are not updated (showing last status) no matter what is chosen, nor where is clicked for refresh.

Where can we debug this issue and how to decide if an issue or mis-communication  / mis-configuration?

**Comment by blueandgold** [comment]
Hi @ttodo-softserve, can you please clarify if you have completed the integration between Forseti and CSCC?  Did you follow the steps here in this guide?
https://forsetisecurity.org/docs/latest/configure/notifier/index.html#cloud-scc-notification

For example, does anything else show up in CSCC for you, or is it only this test bucket that did not show up?

If you have setup CSCC already, you can set the forseti server into debug mode.  And then check if the following debug level shows up.

On the server vm, run this command:
```
forseti server log_level set debug
```

See the stackdriver log of the server vm like this:
![image](https://user-images.githubusercontent.com/6977544/65299859-1b040800-db26-11e9-8851-28498357eb58.png)

Look for these debug logs:

https://github.com/forseti-security/forseti-security/blob/dev/google/cloud/forseti/notifier/notifiers/cscc_notifier.py#L246

https://github.com/forseti-security/forseti-security/blob/dev/google/cloud/forseti/notifier/notifiers/cscc_notifier.py#L257


Please let us know.

**Comment by ttodo-softserve** [comment]
@blueandgold - thanks for clarifying! Appreciated.

Opening the debug I found the error - configuration. 
Sorry for bothering, at least I've learned how to debug it on-the-fly.

Findings are updated after the forseti run is finished and results are updated to SCC.

Last question - when does the inventory update in SCC? 
1. Upon each forseti run finish
2. or it's needed to do manually Assets - > RE-SCAN in SCC
3. or after an hour they will be reflected

Cheers and thanks again!

**Comment by blueandgold** [comment]
@ttodo-softserve Inventory in SCC is created and updated by SCC itself, which I believe happens periodically every few hours (you don't have to manually trigger a re-scan).  Forseti only updates the findings.

I will go ahead and close this issue.  If you have any other questions, please feel free to re-open this one, or a new issue.  Thanks.

**Comment by ttodo-softserve** [comment]
Perfect! Thank you!
