### ISSUE TITLE
Set password on MySQL root account

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3217]
- [ ] Investigate what parts of Forseti rely on the root account
  - [ ] rename the account from root to something that is not a default to brute force
- [ ] Update Terraform module to set root password
- [ ] Update Forseti to use root password (if needed)
---

### Story
The Forseti Terraform module [creates a root account with no password](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/cloudsql/main.tf#L98) (after [Terraform deletes the default root account](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html)). This does not follow best practices and leaves the database in a potentially vulnerable state.

### Proposed Solution
Investigate if/what parts of Forseti rely on this root account. Update Terraform module and Forseti to support CloudSQL root account with a password.

### Acceptance Criteria
- [ ] GIVEN: a new project
WHEN: Forseti GCEis installed
THEN: the MySQL root user has a password
- [ ] GIVEN: an existing Forseti installation on GCE
WHEN: Forseti is upgraded via Terraform
THEN: the MySQL root user has a password

**Comment by kevensen** [comment]
I think we need to solve https://github.com/forseti-security/terraform-google-forseti/issues/310 in the process of resolving this.

**Comment by gkowalski-google** [comment]
Notes about why these changes got reverted. Please take the following into consideration.

**Issues**
1) User installs Forseti 2.24.0 with Terraform < 5.1.0: Forseti 2.24.0 will expect Terraform to pass in the Cloud SQL user/pass via environment variable. If this is not passed in (for example someone uses Terraform < 5.1.0), then Forseti will not be able to connect to Cloud SQL
2) User installs Forseti < 2.24.0 with Terraform >= 5.1.0: Terraform 5.1.0 sets a different Cloud SQL user and random password. Forseti < 2.24.0 will attempt to connect as root with no password, and will not be able to connect to Cloud SQL
3) Users who are connecting to the database will need to know how to get the username/password and update their processes/apps.
4) Investigate if Forseti Visualizer will be effected.

**Possible Solutions**
- Resolve #1 by updating Forseti to default to root and no password if none provided
- Resolve #2 by moving the initialize_forseti_services script to Terraform repo so that regardless which version of Forseti is deployed, the Terraform module would be in control of the VM metadata startup script. By doing so, we can configure the Cloud SQL proxy to work with user/password regardless of the version of Forseti deployed.

**Comment by gkowalski-google** [comment]
Need to wait and decide how to handle backwards compatibility between Forseti and Terraform, perhaps this will be covered by LTS plan.
