### ISSUE TITLE
Update Docs for GSuite Setup 

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3220]
User Feedback for the [GSuite Setup page](https://forsetisecurity.org/docs/latest/configure/inventory/gsuite.html):

1: Screenshots on the GSuite setup page don't match the current GSuite Admin pages.  (No specific on which screenshot, so please verify.)

2: `Go to your Google Admin Manage API client access Security settings.`
The link doesn't work for the user. But the screenshots are totally correct though.

**Comment by hshin-g** [comment]
Link to GSuite docs so that we do not have to constantly update screenshots.
