### ISSUE TITLE
Integrate Config Validator release updates into Forseti release process

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3248]
## Story
Forseti uses a binary of Config Validator which is [checked into the Forseti repo](https://github.com/forseti-security/forseti-security/tree/master/external-dependencies/config-validator). Checking in a binary is not best practice and [docker images are now published](https://pantheon.corp.google.com/gcr/images/forseti-containers/GLOBAL/config-validator?gcrImageListsize=30) when a commit is merged into the CV master branch.

## Proposed Solution
- Evaluate if this change would be easier/better if the initialize forseti script was moved to the Terraform repo. Forseti issue [3313](https://github.com/forseti-security/forseti-security/issues/3313) and Forseti Terraform issue 310. If so, then complete the script migrations first.
- Remove the CV binary from the Forseti repo.
- Add a Terraform variable to control the CV image commit tag that will be used by Forseti. For example, Forseti on GKE is currently using tag `572e207`, however newer versions of CV have been published.
- Instead of running the static binary, the [Forseti initialize services script](https://github.com/forseti-security/forseti-security/blob/master/install/gcp/scripts/initialize_forseti_services.sh#L42) will need to run a docker command to run CV instead. This will be similar to how [git-sync is run, which is also a docker container](https://github.com/forseti-security/forseti-security/blob/master/install/gcp/scripts/initialize_forseti_services.sh#L48).
- If the user is using git-sync, is there a way to automatically restart CV so that the newest policies are always used? Note: the cron job handles this by restarting the CV service, and we should investigate if there are ways to do this for ad-hoc use of Forseti.
- Consider adding some end-to-end tests for CV if needed.

## Acceptance Criteria
- Config Validator end-to-end tests pass.
- Forseti runs the CV image instead of the binary.
- Forseti release documentation is updated.

**Comment by kevensen** [comment]
The following is for reference.  A new CV container image is built with every merge into the "master" branch of the CV repo.  The only container image tag is :latest.  As of this moment, whenever someone deploys Forseti on-GKE they will always only ever get the **gcr.io/forseti-containers/config-validator** image.

**Comment by dekuhn** [comment]
If we can reuse the container I think that would be ideal.

We should ensure the CV tests provide the right test coverage for Forseti or add specific tests we feel are necessary.

**Comment by hshin-g** [comment]
As per @kevensen's comment, should be tagging these builds in order to target specific releases, instead of using the `latest` tag.

**Comment by kevensen** [comment]
Thinking a little more about this, absent a semver2 version, we could tag a new container image as both :latest and with the short SHA of the last commit.  Then there will be some traceability.

**Comment by blueandgold** [comment]
Related to #3314 let's make sure the proto mentioned in #3314 is considered.
