### ISSUE TITLE
Migrate: Legacy GCE Metadata Server endpoints will be shut down on January 15, 2020

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3252]
- [ ] Investigate if/where Legacy GCE Metatdata Server endpoints are being used in Forseti
- [ ] Remediate any code to the new endpoints
---
See where the legacy v1beta1 is used and migrate to the v1 endpoint.

![image](https://user-images.githubusercontent.com/6977544/65938705-93957f00-e3d8-11e9-885a-ad723f2c2763.png)

**Comment by kevensen** [comment]
It appears that we are using the **v1** endpoint.  A search for _computeMetadata_ and _metadata.compute.internal_ resulted in only the following file.

https://github.com/forseti-security/forseti-security/blob/master/google/cloud/forseti/common/util/metadata_server.py

A search for _meta-data_ returned no results.  Therefore I am certain this is the only file where the endpoints constructed/called and that we are calling the stable endpoints.
