### ISSUE TITLE
Teach Forseti Explainer about roles/iam.serviceAccountUser 

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#3256]
When listing who has access to e.g. a bucket, explain can:
- list users added directly
- list groups
- list groups of groups

but there is (at least) one further way to have access:

- Have yourself (or your group) assigned the role roles/iam.serviceAccountUser  on a serviceaccount with access to that bucket. 

Because with that role I can impersonate that SA, and access anyway.

**Comment by gkowalski-google** [comment]
We are not looking at adding new, non-critical features to Forseti Explain at this time.
