### ISSUE TITLE
Unable to enable required  API's

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/forseti-security#3272]
- [ ] Consider updating tutorial instructions if bug will not get fixed soon
- [ ] Follow up with CloudShell team to get ETA of known bug
---
Ref. https://forsetisecurity.org/docs/latest/setup/install.html#setting-up-forseti-security

When going through the Terraform based Forseti setup wizard, 

Step 2 Activate API's is blocked with error "Unable to enable required  API's"

This happens if prior step creates a new project or selects an existing project.

(Is the wizard setting the context to the correct project?)

**Comment by blueandgold** [comment]
I do see the problem.  Specifically:

#1: cloudresourcemanager api is indeed not enabled as reported
#2: serviceusage and compute apis are enabled, but reported as not enabled

![image](https://user-images.githubusercontent.com/6977544/66336465-f2d02380-e8f1-11e9-948e-c94ff53b3057.png)
