### ISSUE TITLE
Set password on MySql user for GKE

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3294]
- [ ] Forseti: Update Forseti docker entrypoint script
- [ ] Terraform: Pass the username/password to the on_gke module 
- [ ] Heml: Update templates to utilize username/password variables
---

### Story
This is a clone of #3217 to add the same feature for Forseti on GKE.

### Proposed Solution
See tasks above.

### Acceptance Criteria
- [ ] GIVEN: a new project
WHEN: Forseti GKE is installed
THEN: the MySQL root user has a password
- [ ] GIVEN: an existing Forseti installation on GKE
WHEN: Forseti is upgraded via Terraform
THEN: the MySQL root user has a password

**Comment by gkowalski-google** [comment]
Forseti + Terraform changes are done, we just need to support Helm. Move this ticket to helm repo.

**Comment by joecheuk** [comment]
Helm chart updated w/ sql user and password:
https://github.com/forseti-security/helm-charts/pull/52
