### ISSUE TITLE
Publish Recommendation on Why & How to Use Forseti with CSCC/SHA

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3295]
User feedback: it would be great to highlight and make recommendations on our website, why & how Forseti should be used with CSCC.

Items that we can highlight:
- customization (scanning for audit logging, required labels, gsuite groups, groups settings, location, project lien, bigquery retention)

- policy as code (write the rules once, and re-use them everywhere in your workflow, such as terraform deployment)

- real-time enforcement on cloudsql, bigquery, GCS buckets

**Comment by dekuhn** [comment]
@ryanismert is this something you can help document and get published?
