### ISSUE TITLE
Add git-secrets --scan on Travis to detect unencrypted private key.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3315]
We install `git-secrets` in our local environments to prevent someone from committing private keys in the local repo.  But we should also have a check on Travis (`--scan` option), in case this gets past the local check (i.e. if someone did not install or correctly configure git-secrets).

**Comment by dekuhn** [comment]
Will keep this in 2.25 release. The 2.25 sprint is being extended by 2 weeks

**Comment by gkowalski-google** [comment]
Re-open [PR#3553](https://github.com/forseti-security/forseti-security/pull/3553/files). Only change should be to remove the last 4 lines so that the git-secret exit code will fail the build if a secret is found. Show a failed test build with a fake secret to show this is working.
