### ISSUE TITLE
Investigate If OS Inventory Management Info Would Be Useful in Forseti

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3318]
https://cloud.google.com/compute/docs/instances/os-inventory-management

**Comment by yunus** [comment]
It is a crucial integration, thanks for adding this in the roadmap. It would be great to alert on:
- VMs that do not collect OS inventory at all,
- VMs that require updates
- VMs that have old packages (this is almost the same as above)

**Comment by dekuhn** [comment]
We do not currently have bandwidth to work on this feature. Closing it; We can revisit if there is a more customer interest for this feature in the future.
