### ISSUE TITLE
Update Forseti on GCE to use same GKE containers for the GCE runtime the environment

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3319]
- [ ] Configure Forseti on GCE deployments to use the containers we deploy with GKE. 
  - Config Validator
  - Forseti-Security
  - Real-Time-Enforce (maybe?)

Using the same containers with GCE that we build for GKE simplifies the configuration and changes we have to manage between the two types of deployments.

**Comment by kevensen** [comment]
That's only if we use the COS.  If we continue to use Ubuntu, we can run as many containers as we want.  Although I haven't done this in a while, it's fairly simple to start a container via systemd.

**Comment by gkowalski-google** [comment]
@dekuhn @ryanismert @kevensen This ticket along with #3314 and #3248 are all similar. We want to simplify the GCE environment and use the images that are already being created. Before any of this work gets done I think we should take a step back and discuss our long-term strategy for GCE and migrating completely over to GKE. Ideally we can develop and execute a plan to migrate our users over to Forseti on GKE. However, if this is going to take some time (likely will), then we should spend time sooner than later to simplify the GCE environment. With real-time scanner coming on board, things are only going to get more complex. My opinion is that if we are going to do any of this work, then we should run each app as a container within it's own GCE instance.

**Comment by dekuhn** [comment]
With the current GCE limits of deploy with one container on GCE VM I don't think the request here is viable.
