### ISSUE TITLE
Support DB username and password in GKE

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3321]
As a user of Forseti on-GKE, I would like to be able to access the SQL DB with a user name and password in order to assert authentication to the database.

- [x] Update [Docker Entrypoint](https://github.com/forseti-security/forseti-security/blob/master/install/scripts/docker_entrypoint.sh) script to support

Probably env vars

**Comment by gkowalski-google** [comment]
@kevensen Can this issue be closed?
