### ISSUE TITLE
Endpoint Config Check Fails When Private IP's are Used 

### ISSUE THREAD

**Issue by allisonis** [forseti-security/forseti-security#3324]
- [x] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).

`2.22.0`

 - [x] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.

`Config?  The error occurs after the scan is complete, or when initializing the services.`

`google.cloud.forseti.services.cli`, ` get_default_endpoint(self)`
https://forsetisecurity.org/docs/v2.22/develop/reference/_modules/google/cloud/forseti/services/cli.html

 - [x] Include errors, log output, and host operating system, including installed packages.

`Host OS: Ubuntu 18.04 `
```
 resource: {
  labels: {…}   
  type: "gce_instance"   
 }
 severity: "INFO"  
 textPayload: "[forseti-security][2.22.0] google.cloud.forseti.services.cli(get_default_endpoint): Unable to read environment variable: FORSETI_CLIENT_CONFIG, will use the default endpoint instead, endpoint: localhost:50051"  
 timestamp: "2019-10-16T16:29:35.205Z" 
```

 - [x] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

`Community Terraform modules, latest`

**Comment by dekuhn** [comment]
Hannah can you look into this if this has been resolved already or need to understand root cause.

**Comment by hshin-g** [comment]
@allisonis What is the result of this error? Does the Forseti application not run / the scanners do not work? The FORSETI_CLIENT_CONFIG variable is not set on the server, so having it default to localhost:50051 is expected behavior.

**Comment by gkowalski-google** [comment]
@allisonis Following up on this issue. The log message above can safely be ignored, it sounds like there is an error but just means that it's using the default endpoint, which should be fine. Was there any issues with Forseti that you think this was causing?

**Comment by blueandgold** [comment]
This is a real issue.  The server's endpoint changed, but the client config is not updated.  The issue will be addressed in Terraform side, and tracked in this issue, so will close this out.
https://github.com/forseti-security/terraform-google-forseti/issues/295
