### ISSUE TITLE
Automate manual integration test for inventory performance regression

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3327]
- [ ] Automated end2end test for the manual test documented as part of issue #3305 
  - [ ] Likely need to setup a new integration test deployment stage as this test takes ~10mins
  - [ ] Implement the execution of the manual test and test the time it takes - fail the test if the time variance is out of normal ranges.

**Comment by gkowalski-google** [comment]
Duplicate of https://github.com/forseti-security/forseti-security/issues/3078
