### ISSUE TITLE
Server Status after Terraform Deployment

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3330]
## Story
After terraform deployment completes, the Forseti server still need more time to finish starting up.  Any attempt to contact the server will have communication error.

But from a user experience point of view, it is not clear what is happening, or how long to wait.

## Proposed Solution
Update CLI error message to include a note to say "if the server was just deployed then you will need to wait a few more minutes".

**Comment by gkowalski-google** [comment]
Not sure if there is anything we can do here technically, other than an architecture change to move away from the lengthy startup script to a container. For this issue, consider updating documentation to note this.
