### ISSUE TITLE
Server Side Run Logic

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3342]
As a user of Forseti, I would like to invoke the inventory creation, model creation, scan and notify in one CLI command in order to simplify the invocation of a Forseti run.

As a maintainer of Forseti, I would like to remove the two run scripts (one for [GCE](https://github.com/forseti-security/forseti-security/blob/master/install/gcp/scripts/run_forseti.sh) and one for [GKE](https://github.com/forseti-security/forseti-security/blob/master/install/scripts/docker_entrypoint.sh) in order to simplify maintenance.

As a developer of Forseti, I would like to have a single server side API endpoint to invoke inventory creation, model creation, scan and notify in order to simplify eventing inputs (grpc and those not yet designed) and set Forseti up for future architectures.

**Comment by kevensen** [comment]
If we consider a serverless model, we would use Google Cloud Schedule to invoke the periodic run.  Since Cloud Schedule only allows the invocation of a single endpoint, we would have to do the inventory, model, scan, and notify under a single endpoint.

Cloud Schedule only allows for Pub Sub and HTTP invocations.  Cloud Endpoints can "translate" GRPC to REST endpoints.

I am thinking `forseti run` or `forseti server run` in the client CLI.

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
