### ISSUE TITLE
Verify CAI export file exists in GCS

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3347]
## Story
When an inventory is created with CAI enabled, Forseti saves the CAI export to GCS.

## Proposed Solution
Use the output from the forseti inventory create command to check if the file exists in the GCS bucket. The file name will be `gs://forseti-cai-export-{{SUFFIX}}/organizations/{{ORG_ID}}/resource/{{INVENTORY_ID}}.dump`.

## Acceptance Criteria
GIVEN: CAI is enabled
WHEN: Inventory is created
THEN: Test verifies the dump file was saved to GCS

**Comment by goofiva** [comment]
Started this branch: https://github.com/forseti-security/forseti-security/tree/feature/issues-3347

**Comment by goofiva** [comment]
Git Branch:
https://github.com/forseti-security/forseti-security/tree/feature/issues-3347

**Comment by goofiva** [comment]
@gkowalski-google Unable to confirm passing test until without test harness.

**Comment by goofiva** [comment]
@gkowalski-google Created PR here: https://github.com/forseti-security/forseti-security/pull/3407
