### ISSUE TITLE
Load Testing Takes Longer than Expected

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3351]
Expectation in test case is roughly 9 minutes in our test org.

But I'm getting 13 minutes, which is significantly longer (40-45%).
```
{
  "id": "1571636427265968",
  "startTimestamp": "2019-10-21T05:40:27Z",
  "completeTimestamp": "2019-10-21T05:53:12Z",
  "schemaVersion": 1,
  "countObjects": 296612,
  "status": "SUCCESS",
  "warnings": "Your inventory contains warning message(s), please run command `forseti inventory get 1571636427265968` for more information.",
  "errors": ""
}
```

**Comment by joecheuk** [comment]
I have looked into the issue and here are the findings:

1. The faster version (10mins) is installed through python installer (which is now deprecated).
2. I have verified/updated the following configurations to be the same for both projects and the performance diff remains the same

- Compute Instance Size (n1 standard 8 for both), for the compute power, utilization is at around 30-32% while running the inventory process.
- Compute instance Disk type (standard), after parsing the dump file to a local sqlite database, we will need to access the data from disk.
- Compute Instance Region (us-central1-c), can be anywhere, just need to make sure it's the same as the cloud sql region.
- Cloud SQL Region (us-central1), for querying the DB, same region as the VM will have a much better performance.
- GCS Region (us-central1), for fetching the dump files.

There is likely some configuration that we might've missed that slows down the process but we will need more time to find out the discrepancies.

**Comment by joecheuk** [comment]
Tested it against a larger dataset (with 1mil rows) and here is the updated result:

Terraform installer version:
```
{
  "id": "1572989886556301",
  "startTimestamp": "2019-11-05T21:38:07Z",
  "completeTimestamp": "2019-11-06T06:28:45Z",
  "schemaVersion": 1,
  "countObjects": 1156178,
  "status": "SUCCESS",
  "warnings": "Your inventory contains warning message(s), please run command `forseti inventory get 1572989886556301` for more information.",
  "errors": ""
}
~8h50mins
~
```
Python installer version:
```
{
  "id": "1572989851671807",
  "startTimestamp": "2019-11-05T21:37:32Z",
  "completeTimestamp": "2019-11-06T06:05:40Z",
  "schemaVersion": 1,
  "countObjects": 1156178,
  "status": "SUCCESS",
  "warnings": "Your inventory contains warning message(s), please run command `forseti inventory get 1572989851671807` for more information.",
  "errors": ""
}
~8h28mins
```
The differences is only 22 mins and from a percentage point of view it is roughly 4% (22mins/8h28mins).

**Comment by blueandgold** [comment]
Overall, the differences seem to be marginal, and within possible variances of the infrastructure.  So, will accept the findings here, and adjust the load test acceptance criteria.
