### ISSUE TITLE
Verify Explain resource count matches GCP resource count

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3354]
## Story
Forseti Explain uses the database model to provide helpful info about the GCP organization. We want to verify that the resources created by the model match what is in GCP. A good test of this is the projects.

## Proposed Solution
When the design for preventing violations for deleted resources is complete and implemented, compare the counts of the following commands and ensure they match.
```
forseti explainer list_resources | grep -c \"project
```
vs
```
gcloud projects list
```

## Acceptance Criteria
GIVEN: An inventory is created
WHEN: Explainer lists the resources
THEN: The number of projects match the output from gcloud CLI

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/tree/feature/issues-3354

**Comment by goofiva** [comment]
This ticket should be ready for review the moment the https://github.com/forseti-security/forseti-security/issues/2993 ticket is complete.

**Comment by goofiva** [comment]
@gkowalski-google bump.
