### ISSUE TITLE
Nightly integration tests builds broken

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3355]
Nightly integration tests have been broken for ~5 days..

The current build break is related to this PR: https://github.com/forseti-security/forseti-security/pull/3277

See Travis Build Details: https://travis-ci.org/forseti-security/forseti-security/builds/598845179

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [/workspace/integration_tests/tests/forseti/controls/explain.rb:460: syntax error, unexpected end-of-input, expecting end] on forseti-local
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by dekuhn** [comment]
@red2k18 You are missing the end blocks on line 75 https://github.com/forseti-security/forseti-security/blob/fae01fbf872e35a8a410f1114515a2eaae280f1e/integration_tests/tests/forseti/controls/explain.rb#L75

**Comment by red2k18** [comment]
Fix PR (https://github.com/forseti-security/forseti-security/pull/3332) has been submitted and `end` blocks have already been added.

**Comment by red2k18** [comment]
#3332 fixes this.
