### ISSUE TITLE
Update Test Descriptions to reflect what is being tested

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3361]
## Story
The test descriptions are identical in some cases and do not make it easy to understand what is being tested. For example, the many of the [Explain](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/explain.rb#L37) tests use it `should be visible from the command-line`.

## Proposed Solution
Update these descriptions to be more specific about what is being tested.

## Acceptance Criteria
Descriptions are directly accessible to domain experts, testers and developers, so as to improve communication.

**Comment by goofiva** [comment]
@gkowalski-google The PRs below should be merged in before I continue to work on this task.

https://github.com/forseti-security/forseti-security/pull/3332/files
https://github.com/forseti-security/forseti-security/pull/3328/files
https://github.com/forseti-security/forseti-security/pull/3320/files

**Comment by goofiva** [comment]
All blocking PRs has been merged, continuing this task.

**Comment by goofiva** [comment]
@gkowalski-google Getting this error...

`va@forseti-server-vm-a110fc59:~$ mysql -u root --host 127.0.0.1 --database forseti_security --execute "select state
 from model where name = 'bonk';"
ERROR 1045 (28000): Access denied for user 'root'@'cloudsqlproxy~35.239.82.64' (using password: NO)`

**Comment by goofiva** [comment]
@gkowalski-google Created this PR: https://github.com/forseti-security/forseti-security/pull/3412
