### ISSUE TITLE
Verify Firewall Enforcer remediates non-compliant FW rule

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3363]
## Story
The Firewall Enforcer remediates any violations immediately upon discovery. Add a scenario to test that a non-compliant Firewall rule is removed.

## Proposed Solution
As part of the test setup/fixture, add a non-compliant firewall rule to the GCP project where the test is being run. An example non-compliant firewall rule would have ingression direction, source 0.0.0.0/0 and allow all Ports/Protocols.

Instead of using the default allow policy file which requires creating a firewall rule that exposes resources to the public, create a policy file locally that targets a narrow source range. Sample policy content to dump to a JSON file (and delete at the end). Replace {RANDOM} with a random text string.
```
[
    {
        "sourceRanges": ["10.0.0.0/0"],
        "description": "Allow ICMP from private subnet",
        "allowed": [
            {
                "IPProtocol": "icmp"
            }
        ],
        "name": "forseti-test-allow-icmp-{RANDOM}"
    }
]
```

After creating the FW rule run Real-Time Enforcer
```
forseti_enforcer --enforce_project PROJECT_ID --policy_file {TEST_CREATED_POLICY_FILE_PATH}
```
Then verify that the FW rule has been deleted with GCP API.

## Acceptance Criteria
- Can be run in any GCP org/project (no hard-coding)
- FW rule created in test setup is removed

**Comment by goofiva** [comment]
@gkowalski-google Trying to run this manually. It does not appear to be working. No errors either.

`va@forseti-client-vm-95362759:~$ forseti_enforcer --enforce_project va-test-project-256619 --policy_file /i/dont/exist.json
va@forseti-client-vm-95362759:~$ echo $?
0`

**Comment by goofiva** [comment]
@gkowalski-google I need to properly dump the current firewall rule json before adding a firewall rule that is to be deleted.

`gcloud compute firewall-rules list --format=json > current_fw_rule.json`

Using this command. The format looks similar to...

/home/ubuntu/forseti-security/samples/enforcer/default_allow_policy.json 

Upon doing a dry-run though...

`results {
  project_id: "va-test-project-256619"
  timestamp_sec: 1572987585268253
  batch_id: 1572987584508223
  run_context: ENFORCER_ONE_PROJECT
  status: ERROR
  status_reason: "error adding the expected firewall rules from the policy: An unexpected entry exists in a firewall rule dict: \"kind,selfLi
nk,id,creationTimestamp\"."
  gce_firewall_enforcement {
    policy_path: "./current_fw_rule.json"
  }
}
summary {
  batch_id: 1572987584508223
  timestamp_start_msec: 1572987584507809
  timestamp_end_msec: 1572987585519303
  projects_total: 1
  projects_error: 1
  projects_unchanged: 1
}`

How can we get forseti_enforcer to respect the gcloud firewall rule listing command?

**Comment by gkowalski-google** [comment]
Let's hold off on this test for now, I think we might need to add a new Terraform fixture for this.

**Comment by goofiva** [comment]
--dry_run shouldn't expect a variable. Should probably just be a flag.

va@forseti-server-vm-a110fc59:~$ forseti_enforcer --enforce_project va-test-project-###### --policy_file ./allow.json --dry_run
usage: forseti_enforcer [-h] [--forseti_config FORSETI_CONFIG]
                        [--enforce_project ENFORCE_PROJECT]
                        [--policy_file POLICY_FILE] [--dry_run DRY_RUN]
                        [--concurrent_threads CONCURRENT_THREADS]
                        [--maximum_firewall_write_operations MAXIMUM_FIREWALL_WRITE_OPERATIONS]
                        [--maximum_project_writer_threads MAXIMUM_PROJECT_WRITER_THREADS]
forseti_enforcer: error: argument --dry_run: expected one argument
va@forseti-server-vm-a110fc59:~$ forseti_enforcer --enforce_project va-test-project-###### --policy_file ./allow.json --dry_run yes
results {
  project_id: "va-test-project-256619"
  timestamp_sec: 1573197042111721
  batch_id: 1573197041991873
  run_context: ENFORCER_ONE_PROJECT
  status: ERROR
  status_reason: "error adding the expected firewall rules from the policy: Rule name does not match valid GCP resource name regex \"(?:^[a-z](?:[-a-z0-9]{0,
61}[a-z0-9])?)\": \"default-forseti-test-allow-icmp-{RANDOM}\"."
  gce_firewall_enforcement {
    policy_path: "./allow.json"
  }
}
summary {
  batch_id: 1573197041991873
  timestamp_start_msec: 1573197041991508
  timestamp_end_msec: 1573197042358022
  projects_total: 1
  projects_error: 1
  projects_unchanged: 1
}

**Comment by goofiva** [comment]
I'm a bit confused as to how this command works. My assumption is the policy_file json is the "default" state of firewall rules. A source of truth. Any firewall rule outside of the whats in the policy_file json file is marked for deletion. Any firewall rule inside the policy_file json file that does not exist in gcloud is set for addition. Am I wrong? 🤔

**Comment by gkowalski-google** [comment]
> @gkowalski-google I'm a bit confused as to how this command works. My assumption is the policy_file json is the "default" state of firewall rules. A source of truth. Any firewall rule outside of the whats in the policy_file json file is marked for deletion. Any firewall rule inside the policy_file json file that does not exist in gcloud is set for addition. Any rule that is different (json vs existing) is marked for modification. Am I wrong? 🤔

@goofiva The policy file is not a list of allowed rules, it is a list of policies/constraints that tells Forseti if any rule matches the parameters defined in a constraint then it should be removed. The schema of the policy looks similar to actual rule schema. It is not enforcing that the "rules" (policy) in the provided file actually exist, it goes through each rule that it finds in GCP, and checks to see if the rule matches any of the policies. If it does, then it means the rule is not allowed and removes it. It does not add any rules. Does that help? Also, I agree on the --dry_run parameter.

**Comment by goofiva** [comment]
Using this branch: https://github.com/forseti-security/forseti-security/tree/feature/issues-3363

**Comment by goofiva** [comment]
@gkowalski-google 
PR: https://github.com/forseti-security/forseti-security/pull/3424
