### ISSUE TITLE
Verify Inventory Summary uploaded to GCS

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3364]
## Story
One of the Notifiers is to upload the inventory summary to GCS. A model has to be specified before running the command, so an inventory needs to be created.

## Proposed Solution
- Create an inventory/model `forseti inventory create --import_as {RANDOM}`
- Run `forseti notifier run`
- Parse the result of the command line to get the path of the GCS file created, example output:
```
...
{
  "serverMessage": "Inventory Summary file saved to GCS path: gs://forseti-server-6c8c0d1b/inventory_summary/inventory_summary.1572963191379351.20191107T042434Z.csv"
}
...
```

## Acceptance Criteria
- Terraform config applied within the Inspec control

**Comment by goofiva** [comment]
PR: https://github.com/forseti-security/forseti-security/pull/3438
