### ISSUE TITLE
Verify External Project Access Scanner is working

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3366]
## Story
The [External Project Access Scanner](https://forsetisecurity.org/docs/latest/configure/scanner/descriptions.html#external-project-access-scanner) identifies users who have access to projects outside the org. Execute this scanner to verify there are no errors.

## Proposed Solution
Create an inventory, set the model, and run the scanner `forseti scanner run --scanner external_project_access_scanner`.

## Acceptance Criteria
GIVEN: An inventory is created
WHEN: The external project access scanner is run
THEN: No errors are generated

**Comment by kevensen** [comment]
@gkowalski-google Is it possible to have multiple acceptance criteria?  If so, can we add 

THEN: Users not in the org under test appear as violations.

**Comment by gkowalski-google** [comment]
> @gkowalski-google Is it possible to have multiple acceptance criteria? If so, can we add
> 
> THEN: Users not in the org under test appear as violations.

Definitely possible to have multiple acceptance criteria. I agree that type of violation should be tested, but that is not how we currently test this scanner. I think it would be difficult to automate adding a user to a project in another org. I will create a separate ticket for this.

**Comment by gkowalski-google** [comment]
Created a separate ticket to ensure that violations are found #3369.

**Comment by kevensen** [comment]
Cool, thanks @gkowalski-google !

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/tree/feature/issues-3366

**Comment by goofiva** [comment]
@gkowalski-google PR Created: https://github.com/forseti-security/forseti-security/pull/3389
