### ISSUE TITLE
[v2.23.0] Unclear error message on absent config-validator policies

### ISSUE THREAD

**Issue by paskal** [forseti-security/forseti-security#3383]
## Story
Terraform module v5.0.0 + Forseti v2.23.0 on GCE.

Manual `forseti client run` command issue on forseti-vm-client finishes successfully but produces single error, `\n` replaced with line breaks (originally it's single-line), `\"` replaced with `"`  for readability:

```python
  "serverMessage": "Error running scanner: ConfigValidatorScanner: 'Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 199, in reset
    self.stub.Reset(validator_pb2.ResetRequest())
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
\tstatus = StatusCode.UNAVAILABLE
\tdetails = "failed to connect to all addresses"
\tdebug_error_string = "{"created":"@1572268821.347645953","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3528,"referenced_errors":[{"created":"@1572268821.347630964","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":399,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py", line 119, in run
    scanner.run()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 183, in run
    for flattened_violations in self._retrieve_flattened_violations():
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 159, in _retrieve_flattened_violations
    self.validator_client.reset()
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 204, in reset
    e.message)
AttributeError: '_Rendezvous' object has no attribute 'message'
'"
```

I'm having various problems with my installation and don't know which is contributing to the problems I have (SCC notifier doesn't work, inventory gathering takes very long time to finish) and want to report all anomalies I see in log at the moment.

## Proposed Solution
If there are no policies provided to Config Validator via GCS or git-sync, then it will fail and not start. Forseti is calling Config Validator and does not know why it isn't running.

One option is to update Forseti to check if there are any policies available for CV locally (since they run on the same server) and log an error without calling CV. Look into better error handling/logging.

**Comment by hshin-g** [comment]
Thanks for filing this issue, @paskal!

In the Forseti Server VM under /home/ubuntu/forseti-security, can you run: `git branch -l`and let us know what version is outputted?

If it is not v2.23.0, we'd like to reinstall a fresh version of Forseti on the Server VM:

1. Delete your `home/ubuntu/forseti-security` directory: `rm -rf forseti-security`
2. Clone the forseti-security repo: `git clone https://github.com/forseti-security/forseti-security.git`
3. Check out tags/v2.23.0: `git checkout tags/v2.23.0`
4. Reinstall Forseti:
`pip install -r requirements.txt`
`python3 setup.py install`
5. Restart Forseti: `systemctl restart forseti`

And then rerun Forseti inventory, scanner, notifier, etc. to see if this error still persists.

**Comment by paskal** [comment]
I believe I already have 0.23.0 deployed, I haven't done anything at the machine manually and re-created it multiple times via Terraform already:
```bash
ubuntu@forseti-server-vm-xxxxxxx:~/forseti-security$ git branch -l
* (no branch)
ubuntu@forseti-server-vm-xxxxxxx:~/forseti-security$ git log
commit 97be856402a32030144091d49eabeb955ff0db5f (grafted, HEAD, tag: v2.23.0)
Author: Marquis <40628686+jf-marquis-Adeo@users.noreply.github.com>
Date:   Wed Oct 23 21:53:50 2019 +0200

    feat: send mailjet email with HTML content (#3326)
ubuntu@forseti-server-vm-xxxxxxx:~/forseti-security$ sudo git checkout tags/v2.23.0
HEAD is now at 97be856 feat: send mailjet email with HTML content (#3326)
ubuntu@forseti-server-vm-xxxxxxx:~/forseti-security$ git branch -l
* (no branch)
ubuntu@forseti-server-vm-xxxxxxx:~/forseti-security$ git log
commit 97be856402a32030144091d49eabeb955ff0db5f (grafted, HEAD, tag: v2.23.0)
Author: Marquis <40628686+jf-marquis-Adeo@users.noreply.github.com>
Date:   Wed Oct 23 21:53:50 2019 +0200

    feat: send mailjet email with HTML content (#3326)
```

**Comment by kevensen** [comment]
@hshin-g and @paskal  I inadvertently recreated this issue with 2.22.  It looks like the `config-validator` service failed to start due to a missing path. Investigating.

**Comment by kevensen** [comment]
For me, it was the fact that I had forgotten to add my public SSH key to my hosted Git repository.  @paskal Can you confirm that you've added your your public SSH key to your repository?

**Comment by kevensen** [comment]
@paskal I understand you are syncing from GCS.  I ran into this error there as well.  Can you please confirm your policy library is stored in your server GCS bucket as follows?

```
gs://forseti-server-SUFFIX/policy-library
```

**Comment by paskal** [comment]
I have no policy-library folder in my Storage bucket and here is command output:
```bash
user@forseti-server-vm-xxxxxxx:~$ sudo systemctl status config-validator
● config-validator.service - Config Validator API Server
   Loaded: loaded (/lib/systemd/system/config-validator.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-10-29 18:59:06 UTC; 2h 7min ago
 Main PID: 20126 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
If absent policies are the reason of the failure, I would expect error message with this information instead of exception.

**Comment by kevensen** [comment]
Hi @paskal .  The error messaging here can be improved.  Were you able to add your policy-library to your GCS bucket?

**Comment by paskal** [comment]
Forseti is unusable for me because of https://github.com/forseti-security/terraform-google-forseti/issues/360 (which could be moved to this project by the way), I've disabled this option to prevent errors from appearing in logs.

**Comment by red2k18** [comment]
Hi @paskal, Please reply to @kevensen's comment when you get a chance so we can investigate further.

**Comment by paskal** [comment]
Sorry if I was not clear: I did not upload any policies but instead disabled `config-validator` altogether.

**Comment by gkowalski-google** [comment]
Hi @paskal, thanks for this issue. Agree that this error message is not helpful and there are a couple of ways we could let users know that there are no policies for Config Validator to use.

**Comment by gkowalski-google** [comment]
Removing the interrupts label. I have proposed a couple of solutions above in the original comment.
