### ISSUE TITLE
Fix Broken Link in Google Cloud Blog (Serverless Forseti)

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3390]
As reported by user for [this blog](https://cloud.google.com/blog/products/identity-security/cleardata-running-forseti-the-serverless-way)

Should change to: 
```
https://github.com/forseti-security/forseti-security/blob/master/Dockerfile
```
![image](https://user-images.githubusercontent.com/6977544/67831294-0eff5480-fa9b-11e9-91b8-5625bb208920.png)

**Comment by hshin-g** [comment]
The blog post has been updated: https://cloud.google.com/blog/products/identity-security/cleardata-running-forseti-the-serverless-way.
