### ISSUE TITLE
Analyze alternatives to User Agent string for usage metrics

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3413]
## Story
Forseti version, platform, and optional suffix are set in the UA string to allow the Forseti team to understand high-level usage. In order to determine which scanners are in use and plan for deprecation, we would like to collect this configuration. It seems likely that we will need to find a new way to collect this data instead of the UA string. Research alternatives.

**Comment by dekuhn** [comment]
Not proceeding this this work; closing.
