### ISSUE TITLE
Cloud Shell Tutorials Button Links Broken

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3415]
## Story
The Cloud Shell tutorial buttons in the website as well as the README.md in the terraform-google-forseti repo fail to open the tutorial.md file when the branch name has special characters.

The "master" branch works with https://console.cloud.google.com/cloudshell/open?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fforseti-security%2Fterraform-google-forseti.git&cloudshell_git_branch=master&cloudshell_working_dir=examples/install_simple&cloudshell_image=gcr.io%2Fgraphite-cloud-shell-images%2Fterraform%3Alatest&cloudshell_tutorial=.%2Ftutorial.md

However "module-release-5.0.0" does not, with https://console.cloud.google.com/cloudshell/open?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fforseti-security%2Fterraform-google-forseti.git&cloudshell_git_branch=module-release-5.0.0&cloudshell_working_dir=examples/install_simple&cloudshell_image=gcr.io%2Fgraphite-cloud-shell-images%2Fterraform%3Alatest&cloudshell_tutorial=.%2Ftutorial.md

## Acceptance Criteria
Cloud shell tutorials open correctly

**Comment by blueandgold** [comment]
Has any change happened here yet?  The `master` branch of `forseti-security` repo was broken on Thursday morning, where the cloud shell terminal can not find the right directory.  Although this is working fine now, I do not see the right sidebar with the walk-through.  Here is a screenshot I took just now.

![image](https://user-images.githubusercontent.com/6977544/68603014-581cb480-045c-11ea-8b11-68409e78b699.png)

**Comment by kevensen** [comment]
@blueandgold Not yet.  Still investigating.  The right branch gets cloned, but it appears the underlying code in the Cloud Shell button command code.  I think the link is correct.

The workaround is to
```
cd examples/install_simple
teachme tutorial.md
```

**Comment by kevensen** [comment]
This was resolved via #3429
