### ISSUE TITLE
Update Inventory CAI export GCS test

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3419]
## Story
The [Inventory CAI export GCS test](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/inventory-cai_gcs_export_file.rb) checks that the CAI export is saved as part of the inventory process. The GCS bucket this checks in is hard-coded.

## Proposed Solution
Use the [newly added output](https://github.com/forseti-security/terraform-google-forseti/pull/374) instead of hard-coding `gs://forseti-cai-export-#{suffix}`.

## Acceptance Criteria
Existing test passes.

**Comment by goofiva** [comment]
PR: https://github.com/forseti-security/forseti-security/pull/3446
