### ISSUE TITLE
Website Docs: Add developer info for Real-Time Enforcer

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3423]
## Story
[Allison on Slack](https://forsetisecurity.slack.com/archives/CAZCH95EF/p1573261631193200) wants to know how to contribute to the [Real-time Enforcer](https://forsetisecurity.org/docs/latest/configure/real-time-enforcer/index.html). The website docs can be improved.
```
Has anyone used config validator what are your thoughts? The documentation for OPA under the enforcer is kind of confusing. Do I need to deploy anything to my instances to use the config validator/opa based enforcement? Is the config validator just for Terraform configs?
I would like to enforce specific memeber IAM configurations which is not currently supported. Would I need to create an enforcer module for the specific resource? I am not sure why OPA is listed under the real time enforcer in the docs.
```

## Solution
Add a page on the [develop section](https://forsetisecurity.org/docs/latest/develop/) for Real-Time Enforcer.

**Comment by gkowalski-google** [comment]
@hshin-g Has this been completed?

**Comment by hshin-g** [comment]
Yes- PR referenced above.
