### ISSUE TITLE
Verify temp files deleted after notifier run

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3430]
## Story
Forseti creates temp files during notifier run that should be deleted.

## Proposed Solution
Create inventory/model, and run `forseti notifier run`. Then verify that no temp CSV files exist in temp: `find /tmp -maxdepth 1 -name "*.csv" -printf '.' | wc -m`.

## Acceptance Criteria
The find command should return `0`.

**Comment by goofiva** [comment]
PR: https://github.com/forseti-security/forseti-security/pull/3439
