### ISSUE TITLE
Verify notifier inventory summary email is sent

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3431]
## Story
Forseti notifier can send an inventory summary as part of the notifier process.

## Proposed Solution
There are several terraform inputs that will need to be specified, including:

- inventory_email_summary_enabled
- sendgrid_api_key
- forseti_email_sender = forseti-notify@localhost.domain
- forseti_email_recipient

An email will be sent to the recipient with subject `Inventory Summary: {INVENTORY_ID}` from `forseti-notify@localhost.domain`.

Run `forseti notifier run` to test.

## Acceptance Criteria
Verify the email is received.

**Comment by goofiva** [comment]
Using this branch: https://github.com/forseti-security/forseti-security/tree/feature/issues-3431
