### ISSUE TITLE
Verify notifier sends violation info to Slack

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3433]
## Story
Notifier can send violation info to Slack webhook.

## Proposed Solution
Setup a new webhook with Slack and encrypt this within Travis. Update forseti fixture to include this in the Terraform configuration. Investigate how hard it would be to setup a service account with Slack that can use Slack API to get messages.

## Accepted Solution
Similar to #3432 for CSCC integration, it may be too difficult to integrate with Slack API. If the effort is too high, then it's acceptable to use CLI/logs to verify Slack integration is successful.

**Comment by goofiva** [comment]
Using this branch https://github.com/forseti-security/forseti-security/tree/feature/issues-3433
