### ISSUE TITLE
Verify Explain check policy

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3435]
## Story
Forseti can check if a permission is granted to a user on a resource.

## Proposed Solution
Verify the Forseti Server GCP service account has the storage.objects.get permission on the project.

Command to run:
```
forseti explainer check_policy project/{PROJECT_ID} storage.objects.get user/{forseti-server-service-account}
```

## Acceptance Criteria
Output should match
```
{
  "result": true
}
```

**Comment by goofiva** [comment]
PR: https://github.com/forseti-security/forseti-security/pull/3463
