### ISSUE TITLE
Update the Resource Coverage to Show API / CAI Data

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3465]
User feedback: it would be great to clarify the resource coverage by API vs CAI data.

So, in this FAQ, perhaps we can consider to add 2 columns: `CAI` and `API`.

https://forsetisecurity.org/docs/latest/faq/#resource-coverage

**Comment by red2k18** [comment]
Resources that are not supported by CAI/not currently added to Forseti inventory will be the only ones we get by API polling. All the other resources will be fetched from the dump we get from CAI.

Wanted to reiterate before I start working on this one. Correct me if I'm wrong.
