### ISSUE TITLE
Re-Visit If Marketplace Can Be Used to Make Forseti Installation Easier

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3467]
This was investigated a couple of years ago, but challenge was found to grant the installation process in marketplace / cloud launcher the initial permission that's necessary to install / permission forseti.  But we shoud re-visit this again, to see if there has been improvements to Marketplace that this is easier now.

**Comment by dekuhn** [comment]
Adding link to some internal background on previous challenges with Forseti via Market Place: https://b/65445723

**Comment by dekuhn** [comment]
We are no longer considering a marketplace path.
