### ISSUE TITLE
Add functionality to define exception criteria in Firewall Rules Scanner

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#3481]
Use Case: Want to be able to define rules that says teams cannot have firewall rules open on any port to the internet except certain teams. Firewall rules scanner should notify when certain teams actually have those ports open. 

User wants to avoid adding new rules to new projects on an ongoing basis and are looking for a default rule that whitelists specific IP addresses and/or define projects that they want to authorize to expose HTTP/HTTPS to the internet with the capability of building more advanced rules on top of this when needed.

**Comment by hanan-herz** [comment]
I agree this necessary and **not** just for Firewall Rules but for other rules as well.

**Comment by dekuhn** [comment]
@hanan-herz I wonder if you could use config validator rules to accomplish this. However I think the first issue you have to solve for is how to identify the team? Maybe this can be done with labels on projects and you can target different scanning based on these team labels?

I know in some companies they have put these projects in specific folders and have scanning target different folders. Each business is unique and likely will organize themselves in different ways.

**Comment by hanan-herz** [comment]
I’ve been meaning to look into Config Validator. I’ll take a deeper dive now.

Thanks for the suggestion!

Hanan

**Comment by dekuhn** [comment]
@hanan-herz feel free to reopen once you have had a chance to take a deep dive into this. We are moving to Rego for firewall rules scanner so that might be another area to consider related to this issue.
