### ISSUE TITLE
KMS Scanner rules work on organization level. Add support for project level

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#3482]
Today, KMS scanner rules are supported on org level only. Support needs to be added for the rules to work on project level.

**Comment by dekuhn** [comment]
@red2k18 Can you do an analysis for the work required here to support this change?

Would using the Config Validator scanner solve this? Or is the problem with that version of the scanner?

**Comment by red2k18** [comment]
Adding support for `project` level would be similar to adding support for `organization` level which is already done. Using Config Validator scanner wouldn't solve this.

**Comment by red2k18** [comment]
However, users can scope their policy to a specific project using Config Validator scanner.

**Comment by dekuhn** [comment]
@red2k18 I think you can close this issue?

I think you can scope the scanner by setting the target: e.g. target: ["organization/org_id/folder/folder_id/project/project_id"]

**Comment by red2k18** [comment]
Yes, I think this can be closed as Config Validator scanner allows to scope policies on org/project/folder. This way users can get violations on project level.
