### ISSUE TITLE
When resource_ids is set to '*' in bigquery_rules, renders rule useless.

### ISSUE THREAD

**Issue by marmolejo** [forseti-security/forseti-security#3484]
In a Bigquery rule, when resource_ids is set to the project id, the rule gets activated. However if you subsitute the project id by an asterisk (*), like this:

    resource:
      - type: project
        resource_ids:
          - '*'

The rule never gets activated, contrary of what the documentation states: 
https://forsetisecurity.org/docs/latest/configure/scanner/rules.html

resource_ids
Valid values: String, you can use * to match for all.

By debugging the server app, the literal * doesn't get expanded and is treated as a regular id.

Forseti version: v2.24.0
module: scanner
installed via Terraform

**Comment by joecheuk** [comment]
Hi @marmolejo , thanks for opening the issue, while we are troubleshooting the problem, we would like to recommend you using the config validator to scan for violations, as for the BQ rule, this template should be able to address the public BQ dataset problem.

https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_bigquery_dataset_world_readable_v1.yaml

Here is the instruction on how to use the template & config validator scanner in Forseti:
https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-forseti-config-validator

Let us know if you have any questions, we are happy to work with you on getting this set up if needed.

**Comment by marmolejo** [comment]
Yes, I'm evaluating the config validator. Thanks for the suggestion.

**Comment by joecheuk** [comment]
Thanks @marmolejo , please keep up updated if config validator can resolve your use case!

**Comment by blueandgold** [comment]
@marmolejo hope the Config Validator version is able to meet your need, which is the recommended way for scanning for BQ.  I'm going to close this issue, but if you still have questions, please let us know.
