### ISSUE TITLE
Verify debug log level is working

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3489]
## Story
Forseti log level can be controlled by the user to include extra debug info helpful for troubleshooting.

## Solution
- Get the GCE instance id
    - Run `gcloud compute instances describe {forseti-server-vm-name} --zone us-central1-c` and parse the instance id `id: '1260367677159574118'`, save for later
- Set the log level to debug `forseti server log_level set debug`
- Get the current timestamp in format `YYYY-HH-MMTHH:mm:ssZ`
- Create an inventory (no model needed)
- Get count of GCE debug level logs
    - Run `gcloud logging read 'resource.type=gce_instance AND resource.labels.instance_id={GCE_INSTANCE_ID} AND logName=projects/forseti-gce-fanta/logs/forseti AND severity=DEBUG AND timestamp>="{TIMESTAMP}"' --limit=10 | grep -c "severity: DEBUG"`
- Reset log level to info `forseti server log_level set info`

## Acceptance Criteria
Ensure the count of debug level logs is greater than 0.

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/pull/3499
