### ISSUE TITLE
Fix notifier inventory summary export test

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3496]
## Story
The [notifier-inventory-summary-export](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/notifier-inventory_summary_export.rb) is failing with the following error:

```
×  notifier-inventory-summary-export: Command: `forseti notifier run` (2 failed)
     ✔  Command: `forseti notifier run` exit_status should eq 0
     ✔  Command: `forseti notifier run` stdout should match /Notification completed!/
     ×  Command: `gsutil ls gs://forseti-server-65eb14d9/inventory_summary/|grep 1574705947866157` exit_status should eq 0
     
     expected: 0
          got: 1
     
     (compared using ==)

     ×  Command: `gsutil ls gs://forseti-server-65eb14d9/inventory_summary/|grep 1574705947866157` stdout should match "gs://forseti-server-65eb14d9/inventory_summary/inventory_summary.1574705947866157.[0-9TZ]*.csv"
     expected "" to match "gs://forseti-server-65eb14d9/inventory_summary/inventory_summary.1574705947866157.[0-9TZ]*.csv"
     ✔  Command: `forseti inventory delete 1574705947866157` exit_status should eq 0
     ✔  Command: `forseti model delete 7d81364e3e1` exit_status should eq 0
```

## Proposed Solution
The Forseti notifier will output the GCS path of the inventory summary export file as part of the CLI streamed output:

```
{
  "serverMessage": "Inventory Summary file saved to GCS path: gs://#{forseti-server-storage-bucket}/inventory_summary/inventory_summary.1574705590444937.20191125T195157Z.csv"
}
```

Parse this filename and verify this file exists. The current test is looking for any export for the given inventory ID. Fix any issues in this test.

## Acceptance Criteria
- Verify the GCS file included in the CLI output exists
- The test is stable

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/pull/3504

**Comment by goofiva** [comment]
Select a model and create a scanner run before the notifier run.
