### ISSUE TITLE
Fix scanner tests

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3497]
## Story
There are 2 scanner tests that fail for the same reason.

[bucket acl scanner](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-bucket_acl_scanner.rb)
```
 ×  scanner-bucket-acl-scanner: Command: `forseti model use b8eb9197bd7` (1 failed)
     ✔  Command: `forseti model use b8eb9197bd7` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ×  Control Source Code Error /workspace/integration_tests/tests/forseti/controls/scanner-bucket_acl_scanner.rb:27 
     undefined method `[]' for nil:NilClass
```

[scanner-run](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-run.rb)
```
×  scanner-run: Command: `forseti model use 091bbcfb2ff` (1 failed)
     ✔  Command: `forseti model use 091bbcfb2ff` exit_status should eq 0
     ×  Control Source Code Error /workspace/integration_tests/tests/forseti/controls/scanner-run.rb:24 
     undefined method `[]' for nil:NilClass
```

## Proposed Solution
Sometimes these tests fails to get the scanner id [here](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-bucket_acl_scanner.rb#L40), figure out how to make this stable.

## Acceptance Criteria
- These tests work every time.

**Comment by goofiva** [comment]
@gkowalski-google Modified the tests to give us better logs. The tests are indeed failing but inconsistently.

[root@6d412b9b1b30 workspace]# kitchen verify --test-base-path="integration_tests/tests"
-----> Starting Kitchen (v1.24.0)
-----> Verifying <forseti-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-forseti-local` in directory /workspace/integration_tests/fixtures/forseti
$$$$$$ Running command `terraform output -json` in directory /workspace/integration_tests/fixtures/forseti
forseti-server: Verifying host 10.128.0.13
Skipping profile: 'inspec-gcp' on unsupported platform: 'ubuntu/18.04'.
....FF....FF

Profile: forseti_integration_testing
Version: (not specified)
Target:  ssh://ubuntu@10.128.0.13:22

  ×  scanner-bucket-acl-scanner: Command: `forseti inventory create --import_as 0a50ebe4dc0` (2 failed)
     ✔  Command: `forseti inventory create --import_as 0a50ebe4dc0` exit_status should eq 0
     ✔  Command: `forseti inventory create --import_as 0a50ebe4dc0` stdout should match /"id": "([0-9]*)"/
     ✔  Command: `forseti model use 0a50ebe4dc0` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ×  Command: `forseti scanner run` stdout should match /Scanner Index ID: ([0-9]*) is created/
     expected "{\n  \"serverMessage\": \"Error occurred during the scanning process.\"\n}\n" to match /Scanner Index ID: ([0-9]*) is created/
     Diff:
     @@ -1,2 +1,4 @@
     -/Scanner Index ID: ([0-9]*) is created/
     +{
     +  "serverMessage": "Error occurred during the scanning process."
     +}

     ×  Control Source Code Error /workspace/integration_tests/tests/forseti/controls/scanner-bucket_acl_scanner.rb:27
     undefined method `[]' for nil:NilClass
  ×  scanner-run: Command: `forseti inventory create --import_as 0a6871459ea` (2 failed)
     ✔  Command: `forseti inventory create --import_as 0a6871459ea` exit_status should eq 0
     ✔  Command: `forseti inventory create --import_as 0a6871459ea` stdout should match /"id": "([0-9]*)"/
     ✔  Command: `forseti model use 0a6871459ea` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ×  Command: `forseti scanner run` stdout should match /Scanner Index ID: ([0-9]*) is created/
     expected "{\n  \"serverMessage\": \"Error occurred during the scanning process.\"\n}\n" to match /Scanner Index ID: ([0-9]*) is created/
     Diff:
     @@ -1,2 +1,4 @@
     -/Scanner Index ID: ([0-9]*) is created/
     +{
     +  "serverMessage": "Error occurred during the scanning process."
     +}

     ×  Control Source Code Error /workspace/integration_tests/tests/forseti/controls/scanner-run.rb:24
     undefined method `[]' for nil:NilClass


Profile Summary: 0 successful controls, 2 control failures, 0 controls skipped
Test Summary: 8 successful, 4 failures, 0 skipped

**Comment by goofiva** [comment]
Using this branch: https://github.com/forseti-security/forseti-security/tree/feature/issues-3497

**Comment by goofiva** [comment]
@gkowalski-google One passing... one failing. No difference in code.

forseti-server: Verifying host 10.128.0.13
Skipping profile: 'inspec-gcp' on unsupported platform: 'ubuntu/18.04'.
..............FF..

Profile: forseti_integration_testing
Version: (not specified)
Target:  ssh://ubuntu@10.128.0.13:22

  ✔  scanner-bucket-acl-scanner: Command: `forseti inventory create --import_as 8455c766655`
     ✔  Command: `forseti inventory create --import_as 8455c766655` exit_status should eq 0
     ✔  Command: `forseti inventory create --import_as 8455c766655` stdout should match /"id": "([0-9]*)"/
     ✔  Command: `forseti model use 8455c766655` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ✔  Command: `forseti scanner run` stdout should match /Scanner Index ID: ([0-9]*) is created/
     ✔  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT COUNT(*) FROM violations V WHERE V.scanner_index_id = 1574826346765420 AND V.violation_type = 'BUCKET_VIOLATION' AND V.resource_id = 'foresti-test-bucket-beloved-worm' AND V.rule_name = 'Bucket acls rule to search for exposed buckets';"` exit_status should eq 0
     ✔  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT COUNT(*) FROM violations V WHERE V.scanner_index_id = 1574826346765420 AND V.violation_type = 'BUCKET_VIOLATION' AND V.resource_id = 'foresti-test-bucket-beloved-worm' AND V.rule_name = 'Bucket acls rule to search for exposed buckets';"` stdout should match /1/
     ✔  Command: `forseti inventory delete 1574826307404899` exit_status should eq 0
     ✔  Command: `forseti model delete 8455c766655` exit_status should eq 0
  ×  scanner-run: Command: `forseti inventory create --import_as ff5bfa5d466` (2 failed)
     ✔  Command: `forseti inventory create --import_as ff5bfa5d466` exit_status should eq 0
     ✔  Command: `forseti inventory create --import_as ff5bfa5d466` stdout should match /"id": "([0-9]*)"/
     ✔  Command: `forseti model use ff5bfa5d466` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ✔  Command: `forseti scanner run` stdout should match /Scanner Index ID: ([0-9]*) is created/
     ×  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;"` exit_status should eq 0

     expected: 0
          got: 1

     (compared using ==)

     ×  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;"` stdout should match /SUCCESS/
     expected "" to match /SUCCESS/
     Diff:
     @@ -1,2 +1,2 @@
     -/SUCCESS/
     +""

     ✔  Command: `forseti inventory delete 1574826349468571` exit_status should eq 0
     ✔  Command: `forseti model delete ff5bfa5d466` exit_status should eq 0


Profile Summary: 1 successful control, 1 control failure, 0 controls skipped
Test Summary: 16 successful, 2 failures, 0 skipped
>>>>>> forseti-server: InSpec Runner exited with 1

**Comment by gkowalski-google** [comment]
@goofiva In the failing case, I'm not sure why, but you can see that it does not have a scanner id. The last part of the query should have a scanner id listed, but there is nothing which is invalid SQL. I'm not sure why there is no id, when the command above it shows the actual output matches the expected output. Perhaps that is where we need to look into.

```
× Command: mysql -u root --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;" exit_status should eq 0

 expected: 0
      got: 1

 (compared using ==)

 ×  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;"` stdout should match /SUCCESS/
 expected "" to match /SUCCESS/
 Diff:
 @@ -1,2 +1,2 @@
 -/SUCCESS/
 +""

```

**Comment by goofiva** [comment]
[root@d11b8c6fcc5f workspace]# kitchen verify --test-base-path="integration_tests/tests"
-----> Starting Kitchen (v1.24.0)
-----> Verifying <forseti-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-forseti-local` in directory /workspace/integration_tests/fixtures/forseti
$$$$$$ Running command `terraform output -json` in directory /workspace/integration_tests/fixtures/forseti
forseti-server: Verifying host 10.128.0.50
Skipping profile: 'inspec-gcp' on unsupported platform: 'ubuntu/18.04'.
.....

Profile: forseti_integration_testing
Version: (not specified)
Target:  ssh://ubuntu@10.128.0.50:22

  ✔  scanner-run: Command: `forseti model use 394f7a3b603`
     ✔  Command: `forseti model use 394f7a3b603` exit_status should eq 0
     ✔  Command: `mysql -u forseti_security_user -prKisUPz6xpyvGx0N --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = 1576387644195202;"` exit_status should eq 0
     ✔  Command: `mysql -u forseti_security_user -prKisUPz6xpyvGx0N --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = 1576387644195202;"` stdout should match /SUCCESS/
     ✔  Command: `forseti inventory delete 1576387589550832` exit_status should eq 0
     ✔  Command: `forseti model delete 394f7a3b603` exit_status should eq 0


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 5 successful, 0 failures, 0 skipped
       Finished verifying <forseti-local> (17m41.34s).
-----> Kitchen is finished. (17m44.01s)

> @goofiva In the failing case, I'm not sure why, but you can see that it does not have a scanner id. The last part of the query should have a scanner id listed, but there is nothing which is invalid SQL. I'm not sure why there is no id, when the command above it shows the actual output matches the expected output. Perhaps that is where we need to look into.
> 
> ```
> × Command: mysql -u root --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;" exit_status should eq 0
> 
>  expected: 0
>       got: 1
> 
>  (compared using ==)
> 
>  ×  Command: `mysql -u root  --host 127.0.0.1 --database forseti_security --execute "SELECT SI.* FROM scanner_index SI WHERE id = ;"` stdout should match /SUCCESS/
>  expected "" to match /SUCCESS/
>  Diff:
>  @@ -1,2 +1,2 @@
>  -/SUCCESS/
>  +""
> ```

I imagine that forseti is returning an empty id. It should have failed here...

https://github.com/forseti-security/forseti-security/commit/87e1cd5b5adfe70e52b3cab49a0799b1645d07ae#diff-9215742039a83d82603e5bfed589ac15R39

In the next commit, I'll edit the regex id search to require at least one digit. If forseti is indeed returning an empty id, I think that would be a bug we need to know about.
