### ISSUE TITLE
Forseti instances deployed using Terraform run for a couple days before they stop functioning

### ISSUE THREAD

**Issue by red2k18** [forseti-security/forseti-security#3500]
This is a recurring issue with at least 2 customers.

**Comment by red2k18** [comment]
@blueandgold @kevensen @garrettwong Is this issue being investigated?

**Comment by red2k18** [comment]
Deployed Forseti, v2.24.0 using Terraform in a project dedicated to reproduce this issue, and reached out to the user for further details such as version and to see if they have the affected instance.

**Comment by dekuhn** [comment]
Adding back the interrupts follow-up to make sure we don't lose sight of this issue.

Can someone provide an update on root cause analysis?

**Comment by red2k18** [comment]
Forseti commands works as expected on the instance I spun up last week to reproduce this issue. Haven't heard back from the user on the version they are using and other information that has been requested. 

Another user reported similar issue. Will update here when I get more info from any of them.

**Comment by blueandgold** [comment]
As another data point: my test instance (v2.24) has been running fine since 11/26, on an hourly cron job.
