### ISSUE TITLE
Create a container image specifically for the forseti-client/forseti-orchestrator

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3511]
## Story
Today, the [cloudbuild-release.yaml](https://github.com/forseti-security/forseti-security/blob/master/build/cloudbuild-release.yaml) and [cloudbuild-master.yaml](https://github.com/forseti-security/forseti-security/blob/master/build/cloudbuild-master.yaml) files create a generic `forseti` container image that uses the [docker_entrypoint.sh](https://github.com/forseti-security/forseti-security/blob/master/install/scripts/docker_entrypoint.sh) script as the `ENTRYPOINT`.  Depending on the options passed to the container image, either by the CLI or by Kubernetes, the server or client (orchestrator) will start.

## Proposal
In support of #3093, creating a distinct container image for the client will simplify and make explicit the container behavior.

- [ ] Create a container image with the `ENTRYPOINT` set to `forseti`.

## Validation
- [ ] GIVEN a forseti-orchestrator container and no import
- [ ] WHEN the container is run
- [ ] THEN the client process is executed without the `docker_entrypoint.sh` script.

**Comment by gkowalski-google** [comment]
Keep open

**Comment by kevensen** [comment]
This depends on #3544

**Comment by gkowalski-google** [comment]
@kevensen There is an image for the orchestrator now, is there still work to be done for the client image?

**Comment by kevensen** [comment]
@gkowalski-google yes.  This is addressed
