### ISSUE TITLE
Verify Bigquery Scanner is working

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3538]
## Story
The [Bigquery Scanner](https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html) checks for exposed datasets.

## Solution
Create [bigquery dataset](https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html) with access for role = `READER` and special_group = `allAuthenticatedUsers` with the [test_resources module](https://github.com/forseti-security/forseti-security/tree/master/integration_tests/fixtures/forseti/modules/test_resources).

The Bigquery Scanner is enabled by default so it will not need to be enabled/disabled like the enabled apis scanner.

The default Bigquery rules no not need to be modified like the enabled apis scanner.

## Acceptance Criteria
Verify a violation is created with violation_type = `BIGQUERY_VIOLATION`, scanner id matching the one created from the test, resource_id should match the dataset id created.

**Comment by goofiva** [comment]
Using this branch.

https://github.com/forseti-security/forseti-security/tree/feature/issues-3538
