### ISSUE TITLE
Verify Firewall Scanner is working

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3539]
## Story
The [Firewall Scanner](https://forsetisecurity.org/docs/latest/configure/scanner/descriptions.html#firewall-rules-scanner) checks for Firewall Rules that expose GCP resources.

## Solution
Create an allow [firewall rule](https://www.terraform.io/docs/providers/google/r/compute_firewall.html) with:

- description: `Forseti test firewall rule`
- disabled: `true` (Let's see if this will still trigger a Forseti violation, if not leave to default)
- network: forseti network name (will need to take this from output from core forseti module)
- protocol: `all`
- source_tags: `forseti_fake_tags`
- target_tags: `forseti_fake_tags`

The Firewall Scanner is enabled by default so it will not need to be enabled/disabled like the enabled apis scanner.

The default Firewall rules do not need to be modified like the enabled apis scanner.

## Acceptance Criteria
Verify a violation is created with violation_type = `FIREWALL_BLACKLIST_VIOLATION`, scanner id matching the one created from the test, resource_id should match the firewall rule id created.

**Comment by goofiva** [comment]
This test will require network output in the file below.

https://github.com/forseti-security/terraform-google-forseti/blob/master/outputs.tf

**Comment by gkowalski-google** [comment]
@hshin-g Test is passing from the GCB build:

```
  ✔  scanner-firewall-scanner: Command: `forseti model use 7163dd47f65`
     ✔  Command: `forseti model use 7163dd47f65` exit_status should eq 0
     ✔  Command: `forseti scanner run` exit_status should eq 0
     ✔  Command: `forseti scanner run` stdout should match /Scanner Index ID: (.*[0-9].*) is created/
     ✔  Command: `mysql -u forseti_security_user -p28thFl0N7R6GE@fK --host 127.0.0.1 --execute "SELECT COUNT(*) FROM forseti_security.violations V JOIN forseti_security.scanner_index SI ON SI.id = V.scanner_index_id WHERE SI.inventory_index_id = 1578419095998047 AND V.violation_type = 'FIREWALL_BLACKLIST_VIOLATION' AND V.resource_name = 'forseti-allow-all-ingress-c51565e05d76d146' AND V.rule_name = 'prevent_allow_all_ingress';"` exit_status should eq 0
     ✔  Command: `mysql -u forseti_security_user -p28thFl0N7R6GE@fK --host 127.0.0.1 --execute "SELECT COUNT(*) FROM forseti_security.violations V JOIN forseti_security.scanner_index SI ON SI.id = V.scanner_index_id WHERE SI.inventory_index_id = 1578419095998047 AND V.violation_type = 'FIREWALL_BLACKLIST_VIOLATION' AND V.resource_name = 'forseti-allow-all-ingress-c51565e05d76d146' AND V.rule_name = 'prevent_allow_all_ingress';"` stdout should match /1/
```
