### ISSUE TITLE
Forseti process stopped after running for a while

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#3557]
This issue was reported by a few users, their forseti instance was running well for awhile before it stopped (or stuck).

Related to the discussion in this issue, with regards to the ulimit: https://github.com/forseti-security/forseti-security/issues/3425

**Comment by blueandgold** [comment]
A memory issue reported in #3576 [in this comment](https://github.com/forseti-security/forseti-security/issues/3576#issuecomment-574450929) might be an issue.

**Comment by gkowalski-google** [comment]
Closing this for now as short-term fix has been released. Long-term fix will be addressed by [#3622](https://github.com/forseti-security/forseti-security/issues/3622)
