### ISSUE TITLE
Cloud Spanner instance not showing in CAI export

### ISSUE THREAD

**Issue by pdutch** [forseti-security/forseti-security#3572]
2.24.0
Config Validator, all other scanners/api's are disabled.
No errors, not sure about MODEL_STATUS=PARTIAL_SUCCESS if that's relevant?
Terraform Module deployment then subsequent upgrade via updating startup script.

Checking the dump file in the cai export bucket, there are no spanner resources. Forseti has no filter on the CAI export resource types. Inventory summary also shows no spanner resources.

**Comment by hshin-g** [comment]
Thanks for submitting this issue, @pdutch. Can you verify that the Cloud Spanner API is enabled in your Forseti project? (In the GCP Console side bar, navigate to **APIs & Services** --> **API Library** --> Type `Cloud Spanner API`)

If it is not enabled, please enable the API, and rerun inventory. Cloud Spanner instances should show up in your CAI dump and the Forseti inventory.

Please let me know if this issue still persists!

**Comment by pdutch** [comment]
Thanks @hshin-g that has solved it :)
