### ISSUE TITLE
resource_type and full_name not populating in scanner_violations_x_.csv

### ISSUE THREAD

**Issue by pdutch** [forseti-security/forseti-security#3576]
- [ ] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
v2.24.0
 - [ ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
Config Validator
 - [ ] Include errors, log output, and host operating system, including installed packages.
No specific errors
 - [ ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).
Terraform (Custom).

When running config validator, there are no errors and the CAI exports look good. The CSV file has 2 blank columns, resource_type and full_name.

We have possibly a very large number of violations (450,000) so not sure if that is affecting the output. This is across approx ~400 projects.

Missing these fields in the violation.csv makes it more difficult to match up violations with projects, which we then extract owners from the projects for remediation activities.

**Comment by pdutch** [comment]
I've done some more testing, and I've found if I remove 2 constraints that were responsible for around 440k violations, the scanner_violations.csv is generated properly. Over the next week or so I'll do some more tests and try and figure out if its a specific constraint that is causing the issue, or if it's the sheer number of violations.

**Comment by pdutch** [comment]
Latest test is I've produced a scannerviolations.csv with 118,000 violations, and it looks good. The only constraint I haven't put back in play is the Bigquery Required Labels policy. I'll carry on my testing and see if it's this specific constraint or if it's the number of violations.

**Comment by pdutch** [comment]
Running some more tests seem to indicate large memory usage during the notifier run when there are a large number (150,000+ ?) violations. With the original instance size, with 8gb of memory, I wasn't seeing crashes, just the malformed scannerviolations.csv.

I've upped the memory for the instance to the n1-highmem-4, with 26gb of memory, but still during the notifier run it maxs out and kills the forseti-service:

```
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.408820] Killed process 686 (forseti_server) total-vm:27435968kB, anon-rss:25766140kB, file-rss:0kB, shmem-rss:0kB 
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.400385] Out of memory: Kill process 686 (forseti_server) score 965 or sacrifice child 
...
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.400090] forseti_server invoked oom-killer: gfp_mask=0x6280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0 
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx systemd[1]: snapd.service: Watchdog timeout (limit 5min)! 
A 2020-01-15T01:03:18Z Jan 15 01:03:18 forseti-server-xxx kernel: [10043.077619] Core dump to |/usr/share/apport/apport 1988 11 0 1 1988 pipe failed 
A 2020-01-15T01:00:50Z Jan 15 01:00:50 forseti-server-xxx google-ip-forwarding: WARNING Exception running ['ip', 'route', 'ls', 'table', 'local', 'type', 'local', 'proto', '66', 'scope', 'host', 'dev', 'ens4']. [Errno 12] Cannot allocate memory. 
```

**Comment by pdutch** [comment]
Running some more tests seem to indicate large memory usage during the notifier run when there are a large number (150,000+ ?) violations. With the original instance size, with 8gb of memory, I wasn't seeing crashes, just the malformed scannerviolations.csv.

I've upped the memory for the instance to the n1-highmem-4, with 26gb of memory, but still during the notifier run it maxs out and kills the forseti-service:

```
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.408820] Killed process 686 (forseti_server) total-vm:27435968kB, anon-rss:25766140kB, file-rss:0kB, shmem-rss:0kB 
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.400385] Out of memory: Kill process 686 (forseti_server) score 965 or sacrifice child 
...
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx kernel: [10045.400090] forseti_server invoked oom-killer: gfp_mask=0x6280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0 
A 2020-01-15T01:03:20Z Jan 15 01:03:20 forseti-server-xxx systemd[1]: snapd.service: Watchdog timeout (limit 5min)! 
A 2020-01-15T01:03:18Z Jan 15 01:03:18 forseti-server-xxx kernel: [10043.077619] Core dump to |/usr/share/apport/apport 1988 11 0 1 1988 pipe failed 
A 2020-01-15T01:00:50Z Jan 15 01:00:50 forseti-server-xxx google-ip-forwarding: WARNING Exception running ['ip', 'route', 'ls', 'table', 'local', 'type', 'local', 'proto', '66', 'scope', 'host', 'dev', 'ens4']. [Errno 12] Cannot allocate memory. 
```

I've done some more testing and used the n1-highmem-8 machine (8cpu, 52gb memory), and this machine was able to complete the full 450k violations.csv with all fields completed correctly. 

Either this many violations just requires a huge amount of memory, or there's a memory leak somewhere. Happy to help with any troubleshooting if you like, or we can close this ticket and I'll just accept the memory requirements.

**Comment by pdutch** [comment]
Further testing may indicate a memory leak somewhere. First run, peaked at 32gb memory usage during the notifier run, and when finished running landed on 7-8gb still in use. I ran the crontab trigger script again directly after, this time peaking at 46gb usage and when finished sat at 23gb. 

Without a reboot between runs quite likely I would hit the memory limits and cause a crash in the forseti-service at least.

**Comment by pdutch** [comment]
Running
`sudo systemctl restart forseti.service`
and
`sudo systemctl restart config-validator`
cleans out the memory after running a full scan and report. Maybe could include as the last step after the forseti run?

**Comment by gkowalski-google** [comment]
Hi @pdutch, thanks for reporting this issue. Can you let us know what is the size of the CAI export for your organization?

**Comment by gkowalski-google** [comment]
@pdutch Can you also let me know which bigquery required labels template you are using? Are you using [this one](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_enforce_labels_v1.yaml)? If so, there was a [recent change](https://github.com/forseti-security/policy-library/pull/252) made to this template which may or may not be related to the issue you are seeing.

**Comment by pdutch** [comment]
Hi @gkowalski-google ,

The CAI Exports are:
Resource: 1019.54mb
IAM: 2.99mb

We are using that constraint, but I don't feel like the specific constraint is the problem as the issue only appeared once the number of violations exceeded 200,000 or thereabouts. Also we have a slightly edited version of that enforce labels template that includes:
 - bigquery.googleapis.com/Table
 - bigquery.googleapis.com/Dataset

In the resources to scan. Otherwise there are very similar.

Cheers,
Pete.

**Comment by blueandgold** [comment]
Hi @pdutch we are going to restart the forseti cron job between each run as an interim step, while we troubleshoot the root cause of this.

**Comment by red2k18** [comment]
@pdutch Thanks for reporting this issue! We're going patch releases v2.23.0 and v2.24.0 to restart Forseti as an immediate fix. I have opened an [issue](https://github.com/forseti-security/forseti-security/issues/3622) to examine the root cause. Patch announcement will be sent via email and Slack. 

Please reach out if you run into any other issues.

Thanks,
Rehana
