### ISSUE TITLE
Verify Location Scanner is working correctly

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3579]
## Story
Test the Location Scanner is working correctly.

## Proposed Solution
- Create test resources as part of test_resources fixture:
  - Create bucket in EU (similar to [this](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/fixtures/forseti/modules/test_resources/main.tf#L34) but don't need to modify ACL)
- Add a [rule to the rules module that's the same as the one shipped by default](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/rules/templates/rules/location_rules.yaml), but uncomment the rules to enable them.

## Acceptance Criteria
- Assert two violations are found for the test resource that are found for each rule name.

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/pull/3585
