### ISSUE TITLE
Update server config script to be able to enable a scanner

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3580]
## Story
Scanners are currently enabled from within Inspec controls using tee, which outputs lots of info to the log and makes things harder to read.

## Proposed Solution
Add a new method to the [update server config script](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/scripts/update_server_config.py) to enable/disable a particular scanner and update [audit logging control](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-enable_audit_logging_scanner.rb) and [enabled apis control](https://github.com/forseti-security/forseti-security/blob/master/integration_tests/tests/forseti/controls/scanner-enabled_apis_scanner.rb) to use this.

## Acceptance Criteria
Audit_logging and enabled APIs scanner tests still pass.

**Comment by goofiva** [comment]
https://github.com/forseti-security/forseti-security/pull/3600
