### ISSUE TITLE
● forseti.service is not starting on the server.

### ISSUE THREAD

**Issue by deepakmahajan-23** [forseti-security/forseti-security#3598]
First, help us help you by providing the following information when opening an issue.

 - [ ] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
 - [ ] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ ] Include errors, log output, and host operating system, including installed packages.
 - [ ] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

Secondly, if the issue is a feature request, be descriptive regarding what needs to be
changed and why, e.g. what to scan for, what would be a 'good' state and what would be
a 'violation' etc.

Finally, be sure to see the [FAQ](https://forsetisecurity.org/docs/latest/faq/) and [Get Help](https://forsetisecurity.org/docs/latest/develop/get-help.html)
for assistance.

Thanks!

**Comment by gkowalski-google** [comment]
@deepakmahajan-23 Can you let us know what issue you are seeing? It appears that the Forseti service is not starting, is that correct? If so, can you take a look at the Stackdriver/Console logs of the server VM and look for any errors.

**Comment by deepakmahajan-23** [comment]
forseti service is not starting. I checked the log also no error is coming.

**Comment by blueandgold** [comment]
@deepakmahajan-23 it would be helpful if we can take a look at the Forseti server log to see more of what is happening (please DM me).  You can find the logs like the screenshot below.
![image](https://user-images.githubusercontent.com/6977544/73207370-75772b80-40f9-11ea-8581-09402b19aa2b.png)

**Comment by red2k18** [comment]
@deepakmahajan-23 Did you have a chance to look at the logs? We can also look at the logs together if you're still seeing this issue. 

Thanks,
Rehana

**Comment by red2k18** [comment]
@deepakmahajan-23 I'm closing this issue as we do not have enough information to look into this. Please feel free to reopen this issue with more details. Thank you!
