### ISSUE TITLE
Update Scanner Rule Links on Website

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#3611]
## Story

[Links to the rule files](https://forsetisecurity.org/docs/latest/configure/scanner/descriptions.html) are 404 on the website.

## Solution
Update the links for the rule files to [their new location in the Terraform repo](https://github.com/forseti-security/terraform-google-forseti/tree/master/modules/rules/templates/rules).

**Comment by gkowalski-google** [comment]
This change has been completed by this [PR](https://github.com/forseti-security/forseti-security/pull/3531), but has not been deployed to production due to the delay of the v2.25.0 release.
