### ISSUE TITLE
Error communicating to the Forseti server

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/forseti-security#3615]
**Forseti version:** v2.24.0
**Terraform module:** modulerelease511 (v5.1.1)

Error:
```
Error communicating to the Forseti server.
Please check the status of the server and make sure it's running.
If you are accessing from a client VM, make sure the `server_ip` field inside the client configuration file in the Forseti client GCS bucket contains the right IP address.
```
After deploying Forseti through both the Cloudshell tutorial walkthrough and locally, the correct resources are successfully created, but the actual Forseti application does not run. This seems like it is due to a db connection issue, from the logs:

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'cloudsqlproxy~35.186.186.42' (using password: NO)") (Background on this error at: http://sqlalche.me/e/e3q8)
```

The module seems to be using user: `forseti_security_user` while Forseti v2.24.0 is still using root when being initialized [here](https://github.com/forseti-security/forseti-security/blob/d2c177a92c610bf8cadb1970265b70af05315303/install/gcp/scripts/initialize_forseti_services.sh#L35) vs. in [master](https://github.com/forseti-security/forseti-security/blob/e4ffb1bb229d7abe13212d4162270f88c5923cfd/install/gcp/scripts/initialize_forseti_services.sh#L34). Should change so they are compatible.

**Comment by xingao267** [comment]
Is this issue fixed by https://github.com/forseti-security/forseti-security/pull/3616. I'm still having the same issue for new Forseti instance.

**Comment by hshin-g** [comment]
@xingao267 We discovered that there were some backwards incompatible changes from the master branch that were merged into the v5.1.1 release of the Terraform module. We have deleted and recreated the right v5.1.1 release- can you try running terraform init with version = "~>5.1" (and forseti_version="v2.24.0" i.e. the default) to pull down the correct changes and run terraform apply and see if that solves the issue?

**Comment by red2k18** [comment]
@xingao267 Did the resolution work for you?

**Comment by xingao267** [comment]
@red2k18 Thanks for following up. Yes It's addressed but due to a different issue than this one.

**Comment by red2k18** [comment]
@hshin-g Can this be closed?
