### ISSUE TITLE
config_file_path should be read from ENV

### ISSUE THREAD

**Issue by diegosucaria** [forseti-security/forseti-security#3620]
Hello!

I'm trying v2.25  on GKE.

config_file_path variable is hardcoded in docker_entrypoint.sh script.

Should be read from arguments, or ENV.

Thank you!

**Comment by red2k18** [comment]
@diegosucaria, thanks for reaching out! Will discuss with the team about making `config_file_path` public and will circle back. 

Thanks,
Rehana

**Comment by red2k18** [comment]
Hi @diegosucaria, unfortunately, we will not be able to take this on at this time. Is this something you are interested in contributing?

**Comment by diegosucaria** [comment]
Yes, for sure. it is a few lines change. But I haven't had the opportunity to review the contributing guide just yet.
Will do!

**Comment by dinigo** [comment]
If you are using the latest Dockerfile you can override [`CONFIG_FILE_PATH`](https://github.com/forseti-security/forseti-security/blob/82587803807346bd1e612b9059c26930470f1c4e/Dockerfile#L105) with yours. It is set in the last stage
