### ISSUE TITLE
Config Validator Scanner library path check doesn't work on GKE

### ISSUE THREAD

**Issue by diegosucaria** [forseti-security/forseti-security#3630]
Testing latest master image on GKE

the code here google/cloud/forseti/scanner/scanners/config_validator_scanner.py  : 

`
       def verify_policy_library():
        """Verify the Config Validator Policy Library exists and is populated
        with constraints and that the lib directory exists.
        Returns: Nothing
        Raises:
            ConfigValidatorPolicyLibraryError: if the Policy Library is not
             configured correctly.
        """
        if not os.path.isdir(POLICY_LIBRARY_PATH):
            raise errors.ConfigValidatorPolicyLibraryError(
                f'The Policy Library directory is missing: '
                f'{POLICY_LIBRARY_PATH}')

        # Verify constraints
        if not os.path.isdir(POLICY_LIBRARY_CONSTRAINTS_PATH):
            raise errors.ConfigValidatorPolicyLibraryError(
                f'The Policy Library constraints directory is '
                f'missing: {POLICY_LIBRARY_CONSTRAINTS_PATH}')

        if not os.listdir(POLICY_LIBRARY_CONSTRAINTS_PATH):
            raise errors.ConfigValidatorPolicyLibraryError(
                f'The Policy Library constraints directory is '
                f'empty: {POLICY_LIBRARY_CONSTRAINTS_PATH}')
`

Is not compatible with running Forseti on GKE...

I get this error:

 "serverMessage": "Error running scanner: ConfigValidatorScanner: 'Traceback (most recent call last):\n  File \"/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\", line 190, in run\n    ConfigValidatorScanner.verify_policy_library()\n  File \"/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\", line 215, in verify_policy_library\n    f'The Policy Library directory is missing: '\ngoogle.cloud.forseti.scanner.scanners.config_validator_util.errors.ConfigValidatorPolicyLibraryError: The Policy Library directory is missing: /home/ubuntu/forseti-security\n'"

This is bc forseti is looking for the library path to be on the same machine, and that won't work at all.

**Comment by dekuhn** [comment]
PR Pending - moving to next sprint
