### ISSUE TITLE
[WEBSITE] Compute Engine License resource documentation missing

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/forseti-security#3633]
Documentation for Compute Engine License resource (https://cloud.google.com/compute/docs/reference/rest/v1/licenses/get) is currently a dead link, which is causing the website builds to fail.

The documentation has existed in the past before: https://web.archive.org/web/20190702001707/https://cloud.google.com/compute/docs/reference/rest/v1/licenses/get

**Comment by hshin-g** [comment]
Update: checked in with the Compute Engine team. The API is not changing, but they are removing the public documentation because it is not useful for end users and has caused confusion.

**Comment by gkowalski-google** [comment]
@hshin-g Has this been resolved?

**Comment by hshin-g** [comment]
Yes- we took out the link in the website to address.
