### ISSUE TITLE
Forseti deletes default firewall rules on already existing project.

### ISSUE THREAD

**Issue by 1azunna** [forseti-security/forseti-security#3643]
I am using forsti version 2.17.0 and i discovered that after installation and running a scan, the following default firewall rules are deleted.

<img width="1152" alt="Screenshot 2020-02-05 at 21 45 15" src="https://user-images.githubusercontent.com/26540897/74231581-30d9bb80-4cc7-11ea-8787-4d5d1eb611fc.png">

Please why is this so? these are the rules that are added. What are the implications of using this to run a scan on a production project with already existing firewall rules.

![Screenshot 2020-02-11 at 11 57 13](https://user-images.githubusercontent.com/26540897/74232025-34ba0d80-4cc8-11ea-9a3e-c34bf18b5f72.png)

Thanks!

**Comment by red2k18** [comment]
Hi @1azunna , thanks for the question! Ideally, default firewall rules should be deleted and instead customized firewall rules should be added. I have verified that this is not the behavior and default rules are not being deleted. Thanks for reporting the issue. We will ensure that this is fixed.

Thanks,
Rehana

**Comment by gkowalski-google** [comment]
@1azunna Can you provide the terraform config that was used?

**Comment by nycnewman** [comment]
Please can we also have the option to not set these default rules for Forseti. I do not want to have SSH exposed to the Internet by default and would prefer to rely on custom access rules that I set. I use a peered shared VPC and do not want these rules added in that scenario.

**Comment by gkowalski-google** [comment]
Hi @nycnewman, this is a change that will be part of the upcoming v2.25 release for Forseti. It is currently on the master branch of the Forseti Terraform repo. You can set the variable `manage_rules_enabled = false` and the Forseti module will not create any firewall rules.

If you use the master branch of the Terraform repo, then you should also use `forseti_version = "master"` in your Terraform config. While we have tests for both repos that run for PRs and for commits to master, the master branches are not as stable as the releases.

**Comment by gkowalski-google** [comment]
@1azunna Forseti v2.25.0 release is available now, and you can use the new Terraform input to not create the default firewall rules for Forseti. Instead you can manage the rules. I'm going to close this, please re-open if you still need help.
