### ISSUE TITLE
error: idna 2.9 is installed but idna<2.9,>=2.5 is required by {'requests'}

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/forseti-security#3655]
I'm starting to see this error in the log on VM startup this afternoon:-

```
Feb 19 21:42:41 forseti-server-vm-7baf8bf9 startup-script: INFO startup-script: Processing dependencies for forseti-security==2.24.1
Feb 19 21:42:41 forseti-server-vm-7baf8bf9 startup-script: INFO startup-script: error: idna 2.9 is installed but idna<2.9,>=2.5 is required by {'requests'}
Feb 19 21:42:41 forseti-server-vm-7baf8bf9 startup-script: INFO startup-script: Return code 1.
```

`idna v2.9` was released a few days ago after one+ year hiatus: https://pypi.org/project/idna/#history

It causes the startup script to halt abruptly and Forseti service stops running. 

It was working fine this morning.

Is there a way to pin this transitive dependency?

CC'd @xingao267 for awareness.

**Comment by xingao267** [comment]
@gkowalski-google thanks for the fix!! Can we do a release for forseti-security so we can modify our fork of module to use that release?

**Comment by choonchernlim** [comment]
Agreed. I pinned `forseti_version` to `master`... and it works.

Can we tag `forseti-security` version to `v2.24.2`?

**Comment by gkowalski-google** [comment]
@xingao267 @choonchernlim Yes we will be releasing a patch for 2.23 and 2.24, including updates for the Terraform modules.

**Comment by xingao267** [comment]
@gkowalski-google Is it possible to cut the new patch release early next week? Currently, we are not able install new forseti instance because of this bug.

**Comment by gkowalski-google** [comment]
@xingao267 Yes, ETA for patches 2.23.2 and 2.24.2 is Tuesday.
