### ISSUE TITLE
CNCF, Forseti & Cloud Custodian?

### ISSUE THREAD

**Issue by ultrasaurus** [forseti-security/forseti-security#3670]
Reaching out to connect with Forseti, since [CNCF SIG-Security](https://github.com/cncf/sig-security) has an interest in policy monitoring and enforcement across the cloud native ecosystem  https://github.com/cncf/sig-security/issues/46 

Cloud Custodian presented to our group in Dec (video available here https://github.com/cncf/sig-security/issues/300#issuecomment-590405807). It now has support for AWS, GCP and Azure and has been approved by Capitol One for full open source governance and it has been proposed as a CNCF project. 

Since Forseti also has a long track record in this area, we wanted to check in and see if there's potential for convergence or interoperability or if Forseti sees itself as having a different focus.

FYI: I attempted to join your office hours this morning, but no one was there.  Not sure if a github issue is the right place for this, yet it does help for cross-org linking!

**Comment by ryanismert** [comment]
Hi Sarah. I'm the Google PM working with Forseti. Going forward I expect to see Forseti more aligned with Open Policy Agent, and less reliant on customer Python-based scanners. If you'd like to chat in depth, feel free to reach out to me at firstnamelastname@google.com.

**Comment by blueandgold** [comment]
@ultrasaurus we do not hold office hours anymore, due to low attendance.  Where did you see the office hour information so that we can remove it?

**Comment by ultrasaurus** [comment]
The office hours were listed here: https://forsetisecurity.org/community/

**Comment by ultrasaurus** [comment]
by the way, @ryanismert was kind enough to get together with us and answer our questions about Forseti -- feel free to close this (unless you want to leave open to address the office hours website update)

**Comment by blueandgold** [comment]
Thanks!
