### ISSUE TITLE
Findings dissappear from SCC if root_resource_id is a folder

### ISSUE THREAD

**Issue by diegosucaria** [forseti-security/forseti-security#3676]
Using Forseti 2.24.1 on GKE.

The scenario is the following: 

1. Run Forseti with root_resource_id = organizations/123123123
result: everything works ok, violations are sent to the SCC

2. Change root_resource_id to folders/123123  and run Forseti again. (there were violations inside that folder)
result: violations disappear from SCC.

~~If I uncheck the "display only active findings" button, I see all the violations there (not only from that folder but for the entire org), in inactive state.~~ Update: after more testing we confirmed that was not the case. there were no violations at all

What could be happening here?  thanks!

**Comment by gkowalski-google** [comment]
@diegosucaria did some more testing and set the Org Id as the root resource, and the Folder Id on all the constraints. This works, but ultimately is not a good solution. His goal is to have multiple instances of Forseti scanning various folders. We need to investigate why CV is not producing violations if the Folder Id is used as the root resource.

**Comment by blueandgold** [comment]
The issue here is that the constraint has to be `folder/123` without the `s`.
```
spec:
  severity: high
  match:
    target: ["folder/393216968527"]
```

**Comment by diegosucaria** [comment]
Actually, after several attempts, I found that Forseti `root_resource_id` needs to be with `s`, `folders/12123123`

Then, on the constraints, you can use `folder/*` without the `s`.
