### ISSUE TITLE
Inventories look for sub-organizations or API warnings are confusing (Error 400: Request contains an invalid argument)

### ISSUE THREAD

**Issue by dinigo** [forseti-security/forseti-security#3704]
I'm using `master` Forseti branch. 

When I start an inventory a receive three warnings for three projects (tough I have many more). For those projects I have the following warning

| inventory_index_id | resource_full_name | waning_message |
|-------------------|--------------------|------------------|
| 1337                      | organization/1234/project/quickstart-5678/ | GCP API Error: unable to get organizations/Quickstart from GCP ... |

Extending the warning I find the following:

```error
GCP API Error: unable to get organizations/Quickstart from GCP:
<HttpError 400 when requesting https://cloudresourcemanager.googleapis.com/v1/organizations/Quickstart:listOrgPolicies?alt=json returned "Request contains an invalid argument.">
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```

It looks like Forseti is requesting the wrong API for a project. How can I fix this?

**Comment by kevensen** [comment]
Hi @dinigo Thanks for reporting this.  If you are using Terraform to deploy, can you please tell me the value of the `org_id` variable?

**Comment by dinigo** [comment]
I'm using docker (compose) on local

**Comment by dinigo** [comment]
Can I provide further logs or information to help debug this?

**Comment by kevensen** [comment]
I apologize for the delay in responding.  

1. Are you using composite_root_resources?
2. Are you using the config validator scanner?  If so, what policy-library policies do you have in place?

I have recently seen similar behavior and am still investigating the root cause.

**Comment by dinigo** [comment]
> 1. Are you using composite_root_resources?
No, single organization ID
> 2. Do you have CAI enabled?
Yes

Do you have any suspicions? I'd be difficult for me to get up to date with the codebase, but I'd like to give it a look, just out of curiosity :)

**Comment by red2k18** [comment]
@dinigo Checking in to see if you're still seeing the error that you've reported?

**Comment by dinigo** [comment]
Yes, still have it @Red-Five . Any clue?

**Comment by red2k18** [comment]
@dinigo , can you let us know on a high level the steps you took to install Forseti if you did not use Terraform to deploy Forseti? Was the installation successful? What version are you running? Were you able to successfully create an inventory before?

Note: Terraform is the official and only supported method of installing and upgrading Forseti.

**Comment by dinigo** [comment]
I used the docker image bult by the docker-compose. Also tryied the 0.24 and 0.25 versions. Always from docker images. With this setup: https://github.com/forseti-security/forseti-security/issues/3694#issuecomment-614525032

I just want an inventory of our organization

**Comment by red2k18** [comment]
@dinigo It is not clear to me what you're trying to do. Can you share your use case with us? Also, [we're planning on deprecating docker_entrypoint.sh](https://github.com/forseti-security/forseti-security/issues/3093). Happy to review a PR though. Terraform is the official and only supported method to deploy Forseti, and we recommend using Terraform for installing and upgrading.

**Comment by gkowalski-google** [comment]
Hi @dinigo, following up here as well, let us know if there is anything we can help with.

**Comment by dinigo** [comment]
As we only wanted a resources inventory, and we can get this with google cloud sdk now we are moving away from forseti on this matter.

Thanks for the support
