### ISSUE TITLE
composite_root_resource accept no project-id only project number 

### ISSUE THREAD

**Issue by aweberlopes** [forseti-security/forseti-security#3740]
First, help us help you by providing the following information when opening an issue.

 - [ 2.25] Which version of Forseti Security you're using (look in `/home/ubuntu/forseti-security/google/cloud/forseti/init.py` 
 on the client).
 - [inventory] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
 - [ ] Include errors, log output, and host operating system, including installed packages.
 - [Terraform] Note how you deployed (via Deployment Manager, Terraform, local system, etc.).

Please add to the documentation if forseti scans nonorganisation that composite_root_resource should be project_number and not projectid.

Thanks
Alex Weber Lopes

**Comment by blueandgold** [comment]
Below screenshot is an example.  Although we give examples of what the actually `id` is, there is the potential of confusion with GCP `id`.
https://forsetisecurity.org/docs/latest/configure/inventory/
![image](https://user-images.githubusercontent.com/6977544/80519268-90e21480-893c-11ea-8166-f8136e28c737.png)

**Comment by aweberlopes** [comment]
yeah but id is confusion. you want a project-number and not a project-id
