### ISSUE TITLE
'latin-1' codec can't encode character '“' in position 0: ordinal not in range(256)

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3750]
Hi,

We are seeing following error in Forseti execution in our environment. We are using Forseti version: `2.18.0`.

```
details = "Exception calling application: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'latin-1' codec can't encode character '\u201c' in position 0: ordinal not in range(256)"
	debug_error_string = "
{
    "created": "@1589951683.308503980",
    "description": "Error received from peer",
    "file": "src/core/lib/surface/call.cc",
    "file_line": 1036,
    "grpc_message": "Exception calling application: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'latin-1' codec can't encode character '“' in position 0: ordinal not in range(256)",
    "grpc_status": 2
}
```

Due to this, none of the rules are getting executed, hence there is no scanner output.

Could you please help us resolve this issue? We are facing this in our production env, so its a high severity issue for us.

**Note:** This looks similar to https://github.com/forseti-security/forseti-security/issues/1930#issue-353017033. I couldn't figure out how that issue was resolved, so created a new one for error on our environment.

Thank you,
Abhishek

**Comment by hshin-g** [comment]
Hi Abhishek, unfortunately we do not support older versions of Forseti like 2.18.0. Can you let me know if you're still experiencing the same issues in 2.25.1? Will close this issue for now- thanks.
