### ISSUE TITLE
Docker run_server resulting in AttributeError: module 'googleapiclient' has no attribute '__version__'

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3751]
Hi, 

While executing docker command to run server, we are getting following error. This is in Forseti version: **2.25.1**

```
forseti-security % docker run  -i -t forseti/forseti --run_server
+ true
+ start_server
+ forseti_server --endpoint 127.0.0.1:50051 --forseti_db mysql+pymysql://:@127.0.0.1:3306/forseti_security --services scanner model inventory explain notifier --config_file_path /forseti-security/forseti_conf_server.yaml --log_level=info --enable_console_log
Traceback (most recent call last):
  File "/home/forseti/.local/bin/forseti_server", line 11, in <module>
    load_entry_point('forseti-security==2.25.0', 'console_scripts', 'forseti_server')()
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.25.0-py3.6.egg/google/cloud/forseti/stubs.py", line 27, in RunForsetiServer
    import google.cloud.forseti.services.server as forseti_server
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.25.0-py3.6.egg/google/cloud/forseti/services/server.py", line 26, in <module>
    from google.cloud.forseti.common.util import file_loader
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.25.0-py3.6.egg/google/cloud/forseti/common/util/file_loader.py", line 24, in <module>
    from google.cloud.forseti.common.gcp_api import storage
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.25.0-py3.6.egg/google/cloud/forseti/common/gcp_api/storage.py", line 27, in <module>
    from google.cloud.forseti.common.gcp_api import _base_repository
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.25.0-py3.6.egg/google/cloud/forseti/common/gcp_api/_base_repository.py", line 57, in <module>
    SUPPORT_DISCOVERY_CACHE = (googleapiclient.__version__ >= '1.4.2')
AttributeError: module 'googleapiclient' has no attribute '__version__'
```

**Note:** We are trying to use version **2.25.1** as we are encountering another error in our current version **2.18.0**, which is mentioned in issue #3750

Let us know how we can resolve the issue or if we are missing anything.

Thank you,
Abhishek

**Comment by blueandgold** [comment]
This problem with `__version__` was fixed here in #3743 `_base_repository.py`.  If this is happening in 2.25.1, then perhaps we need to patch it in.  @hshin-g

**Comment by hshin-g** [comment]
@abhishekupadhyaya We don't support using Docker to run Forseti, but you can try pulling the latest image which should have the changes from master that Henry referenced above which should address this error.

**Comment by abhishekupadhyaya** [comment]
We applied patch in `_base_repository.py` for `__version__` issue. Now, we are getting this error:

`ModuleNotFoundError: No module named 'MySQLdb'`

Just wondering, since we are getting these import errors in **v2.25.1**, do you recommend using some other more stable release?

**Comment by hshin-g** [comment]
Can you try using the master/latest images that have been pushed out? This is what we are using to run our integration tests which are working. E.g. GCR: gcr.io/forseti-containers/forseti

**Comment by abhishekupadhyaya** [comment]
We were able to resolve that issue by installing `mysqlclient`. However, now we are facing another issue, where completion of model doesn't inform the client that the task was done. Client keeps waiting.

`inventory create --import_as model_adhoc`

Here are the last log statements from forseti server:

```
DEBUG google.cloud.forseti.services.model.importer.importer(run): Finished running importer.
DEBUG google.cloud.forseti.services.model.service(CreateModel): Model <Model(name=model_adhoc, handle=a295ba9bd38cf113dda400be3d0b73a6 state=PARTIAL_SUCCESS)> created at: 21 May 2020 - 21:37:47
```

**Comment by abhishekupadhyaya** [comment]
Closing this issue, will create a new issue for model use
