### ISSUE TITLE
Forseti client stuck after model create completion on server

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3753]
Hi,

We are using version **2.25.1**.

We are able to create a model, however forseti client is unable to get response back from server after successful model creation and hence doesn't make `model use` call.

Due to this, rest of the process (`scanner run`, `notifier run`) doesn't execute.

Here is our command execution:

```
   run_forseti_cmd inventory list
   run_forseti_cmd model list

   # Purge inventory older than 0 days (all)
   run_forseti_cmd inventory purge 0

   # Remove the previous “model_adhoc” if it exists
   run_forseti_cmd model delete model_adhoc

   # Create new inventory and load into new ad hoc model
   # Model name can be anything, randomly using “model_adhoc” here
   run_forseti_cmd inventory create --import_as model_adhoc

   # Use the model for subsequent violations scan
   run_forseti_cmd model use model_adhoc
   run_forseti_cmd scanner run

   # Notify violation results (to GCS bucket, CSCC and/or via email etc)
   run_forseti_cmd notifier run
```

We are running it on production, and have been trying to get this working for almost a week now. Any help is greatly appreciated.

Thank you,
Abhishek

**Comment by gkowalski-google** [comment]
This issue has happening while Forseti is running as a Docker container on AWS, which is not a supported scenario. Will leave the issue open if any contributors would like to troubleshoot and provide a fix.

**Comment by abhishekupadhyaya** [comment]
Closing it.
