### ISSUE TITLE
Cloud Asset Inventory API v1beta1 will be shut down

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3756]
## Story
Cloud Asset Inventory API v1beta1 will be shut down as of September 28, 2020. Start using the new GA API version 1 immediately.

## Investigation
Forseti is using [v1 of the API ](https://github.com/forseti-security/forseti-security/tree/master/google/cloud/asset/v1) already and the server SA is using the [Cloud Asset Viewer role](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server_iam/main.tf#L35). It appears that this will not affect Forseti, however we should triple check that there won't be any issues.

**Comment by hshin-g** [comment]
Have verified that Forseti uses v1 of CAI API and v1beta1 is not used.
