### ISSUE TITLE
Config Validator violations produce duplicate findings for CSCC

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3769]
## Story
Forseti uses a violation hash to use as the finding id in CSCC. Config Validator violation data typically just contains the resource name, so if a resource has multiple violations, only one of those violations will make it into CSCC.

## Proposed Solution
Add an option to include the constraint name in the violation data. By making it an option that is disabled by default, it would not affect any current users.

**Comment by morgante** [comment]
Why not simply use the constraint name + resource name as the violation hash?

**Comment by gkowalski-google** [comment]
I meant to include the constraint name in the [violation hash](https://github.com/forseti-security/forseti-security/blob/master/google/cloud/forseti/services/scanner/dao.py#L366), which is then used as the finding id. I think it's better to have this as optional behavior because some users can have many findings in CSCC right now, and if the finding id changes for all findings, then it can take a while for Forseti to deactivate the existing findings and create new ones.
