### ISSUE TITLE
Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3770]
Hi,

We use release-2.25.1. We are getting the following error:

`sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`forseti`.`some_bindings`, CONSTRAINT `some_bindings_ibfk_2` FOREIGN KEY (`role_name`) REFERENCES `some_role)') [SQL: 'INSERT INTO `some_bindings` (resource_type_name, role_name) VALUES (%s, %s)'] [parameters: ('dataset/<dataset_id>', 'roles/bigquery.dataEditor')] (Background on this error at: http://sqlalche.me/e/gkpj)`

Could you please help us fix this issue?

Thank you,
Abhishek

**Comment by abhishekupadhyaya** [comment]
Following up on this: the issue is still occurring on our production environment. Since the inventory creation for IAM services is failing, `iam_policy_violations` rule ends up with no results. This is causing incomplete audit on our side and impacting downstream security monitoring.

**Comment by cgobb** [comment]
We have the same issue, fresh database and forseti-security v2.25.1.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya Can you tell me where Forseti is running, just want to confirm it's running on GCP?

@cgobb Can you please provide some more information? Are you using GCE or GKE?

**Comment by gkowalski-google** [comment]
Hi @abhishekupadhyaya and @cgobb I believe I am able to repro the issue. I am looking into it more, will provide an update as soon as I can determine what is the root cause here.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya @cgobb  More info on this issue: https://github.com/forseti-security/forseti-security/issues/3774. I have a fix that will make available ASAP (possibly next week).

**Comment by cgobb** [comment]
@gkowalski-google Great news, thanks.

**Comment by PeterYou** [comment]
@gkowalski-google, Awesome

**Comment by gkowalski-google** [comment]
@cgobb @PeterYou @abhishekupadhyaya The fix has been merged into the master branch. You can deploy this version with Terraform by setting `forseti_version = "master"'. It is recommended to use the master branch version of the Forseti Terraform module as well, which can be done by using the module sourced from GitHub `source = "git::https://github.com/forseti-security/terraform-google-forseti.git"`.

I am working on a patch release that will be out next week. If you do test the new version, please let me know if it resolves the issue for you.

**Comment by PeterYou** [comment]
Hi @gkowalski-google , That is great,
May you provide us the commits you made, As I can not use the public repo.

**Comment by gkowalski-google** [comment]
@PeterYou Here is the PR: https://github.com/forseti-security/forseti-security/pull/3775.

**Comment by cgobb** [comment]
Confirmed, the issue is resolved for us.

**Comment by gkowalski-google** [comment]
@cgobb Thanks for testing and letting me know! Patch release will be out shortly.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya @PeterYou @cgobb The latest Forseti release is out to fix the model creation issue. Please upgrade at your convenience and let me know if your issues are resolved. You can upgrade with Terraform by setting the Forseti module version to `5.2.2` or `~> 5.2.0`.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya Have you been able to upgrade?

**Comment by gkowalski-google** [comment]
Closing this out, please re-open if you are still having an issue.

**Comment by PeterYou** [comment]
@gkowalski-google After using version 2.25.2, the problem has been fixed, but it returned to appear again:

"sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (forseti_security.f1979da376f73778f9ce6e965da01666_resources, CONSTRAINT f1979da776f73778f9ce6e965da01666_resources_ibfk_1 FOREIGN KEY (parent_type_name) REFERENCES `f1979da376f7377)') [SQL: 'INSERT INTO f1979da376f73778f9ce6e965da01666_resources (cai_resource_name, cai_resource_type, full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%(cai_resource_name)s, %(cai_resource_type)s, %(full_name)s, %(type_name)s, %(parent_type_name)s, %(name)s, %(type)s, %(policy_update_counter)s, %(display_name)s, %(email)s, %(data)s)'] [parameters: ({'cai_resource_name': '//storage.googleapis.com/google-project2', 'cai_resource_type': 'storage.googleapis.com/Bucket"

Could you please help me to know why it appeared again?

Thanks so much

**Comment by PeterYou** [comment]
Hi @abhishekupadhyaya, @cgobb 
Are you getting this error again?
Because after it was fixed it appeared again with me
