### ISSUE TITLE
Forseti inventory scan slowness

### ISSUE THREAD

**Issue by lgudimella** [forseti-security/forseti-security#3771]
Forseti is taking a long time to run it's inventory (12+ hours). We are using the latest build on a n1-standard-8 GCE instance. 
Our `main.tf` contains the following:

provider "google" {
  version = "~> 3.7"
}

provider "google-beta" {
  version = "~> 3.7"
}

provider "local" {
  version = "~> 1.4"
}

provider "null" {
  version = "~> 2.1"
}

provider "template" {
  version = "~> 2.1"
}

provider "random" {
  version = "~> 2.2"
}

module "forseti" {
  source                   = "../../"
  project_id               = var.project_id
  client_region            = var.region
  bucket_cai_location      = var.region
  server_region            = var.region
  storage_bucket_location  = var.region
  cloudsql_region          = var.region
  composite_root_resources = [
    "organizations/${var.org_id}",
  ]
  network                  = var.network
  subnetwork               = var.subnetwork
  network_project          = var.network_project
  org_id                   = var.org_id
  domain                   = var.domain
  client_instance_metadata = var.instance_metadata
  server_instance_metadata = var.instance_metadata
  client_private           = "true"
  server_private           = "true"
  forseti_version          = var.forseti_version
  cscc_violations_enabled = var.cscc_violations_enabled
  cscc_source_id = var.cscc_source_id

**Comment by lgudimella** [comment]
Sorry for the delayed responses, this is the first time we were trying to run forseti inventory scan. The inventory scan is taking a really long time and eventually times out.

**Comment by gkowalski-google** [comment]
Can you let me know how big is the CAI resources export file? You can find this in the `forseti-cai-export-xxxxxxxx` bucket. It looks like you are also scanning G Suite, do you know how many users/groups are in your domain? Depending on the size of the CAI export and G Suite domain, it can take a long time to run the inventory.

Can you check for any errors in the Server VM console/stackdriver logs? Curious if you see something similar to "too many open files" in the console logs.

A couple of things to try:

- increase the server machine type from `n1-standard-8` to `n1-standard-32`
- update the ulimit to `65536`. this can be found within the server's startup script in the console. after updating machine type, then edit the startup script and search for ulimit and update to that new value.

**Comment by gkowalski-google** [comment]
Hi @lgudimella, did you have any luck with the suggestions above? FYI there is an issue affecting Forseti right now that we will be providing a new patch release for next week. This will break the model that Forseti uses for scanning. It would not contribute to the performance problem, but will prevent Forseti from being able to successfully scan.

**Comment by gkowalski-google** [comment]
@lgudimella  The latest Forseti release is out to fix the model creation issue. Please upgrade at your convenience and let me know if the inventory is able to complete; please also see the other suggestions above. You can upgrade with Terraform by setting the Forseti module version to `5.2.2` or `~> 5.2.0`.

**Comment by gkowalski-google** [comment]
Hi @lgudimella Please let me know if you are still having an issue.

**Comment by gkowalski-google** [comment]
@lgudimella Closing this issue as we have not heard back from you. If you are having inventory errors after upgrading to the latest release, please re-open.
