### ISSUE TITLE
Duplicated permissions listed in some IAM roles break Forseti model

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3774]
## Story
Multiple users have reported that Forseti is unable to create a model: 

- #3767
- #3766 
- #3770 

Recently some IAM roles started to provide duplicate permissions. For example, the `roles/compute.networkAdmin` role now includes `networkservices.httpfilters.create` and `networkservices.httpFilters.create`. During the model creation, a dictionary is used to cache the permissions that have been collected; however the duplicate permission names (ignoring case) break [this code](https://github.com/forseti-security/forseti-security/blob/master/google/cloud/forseti/services/model/importer/importer.py#L1189). Sample error message:

```
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'networkservices.httpfilters.create' for key 'PRIMARY'") [SQL: 'INSERT INTO `{{ MODEL }}_permissions` (name) VALUES (%(name)s)'] [parameters: ({'name': 'accessapproval.requests.approve'}, {'name': 'accessapproval.requests.dismiss'}, {'name': 'accessapproval.requests.get'}, {'name': 'accessapproval.requests.list'}, {'name': 'accessapproval.settings.get'}, {'name': 'resourcemanager.projects.get'}, {'name': 'resourcemanager.projects.list'}, {'name': 'accessapproval.settings.delete'}  ... displaying 10 of 3019 total bound parameter sets ...  {'name': 'resourcemanager.folders.update'}, {'name': 'resourcemanager.projects.create'})] (Background on this error at: http://sqlalche.me/e/gkpj)
```

The duplicate permission can be seen with gcloud:
```
gcloud iam roles describe roles/compute.networkAdmin | grep -i networkservices.httpFilters.create

- networkservices.httpFilters.create
- networkservices.httpfilters.create
```

## Proposed Solution
Update model creation to ignore the case of the permission.

## Acceptance Criteria
All tests pass, add unit/e2e test for some more model scenarios.

**Comment by agupta-1** [comment]
Can you give more clarity on "Update model creation to ignore the case of the permission.". How to achieve this task?

**Comment by PeterYou** [comment]
@gkowalski-google , Can you please help as fast as possible, as it'll be released 
after fixing this issue, I got the same issue again a while ago, here is part of it's logs:
"sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'bigquery_table/bq-table-667e:bq_table_edw_integrated_' for key 'PRIMARY'") [SQL: 'INSERT INTO f1979da776f73738f9cr4r965da01556_resources (cai_resource_name, cai_resource_type, full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%(cai_resource_name)s, %(cai_resource_type)s, %(full_name)s, %(type_name)s, %(parent_type_name)s, %(name)s, %(type)s, %(policy_update_counter)s, %(display_name)s, %(email)s, %(data)s)'] [parameters: ({'cai_resource_name': '//bigquery.googleapis.com/projects/google-project/datasets/bq-table-667e/tables/d_cosumer_agreement_4507338e_0c17_2313_r366_4d96ce7e"

Thanks in advance.

PS, I'm using Forseti 2.25.2

**Comment by PeterYou** [comment]
@gkowalski-google Here is the second another recurring error log:

"sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`forseti_security`.`f1979da376f73778f9ce6e965da01666_resources`, CONSTRAINT `f1979da776f73778f9ce6e965da01666_resources_ibfk_1` FOREIGN KEY (`parent_type_name`) REFERENCES `f1979da376f7377)') [SQL: 'INSERT INTO f1979da376f73778f9ce6e965da01666_resources (cai_resource_name, cai_resource_type, full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%(cai_resource_name)s, %(cai_resource_type)s, %(full_name)s, %(type_name)s, %(parent_type_name)s, %(name)s, %(type)s, %(policy_update_counter)s, %(display_name)s, %(email)s, %(data)s)'] [parameters: ({'cai_resource_name': '//storage.googleapis.com/google-project2', 'cai_resource_type': 'storage.googleapis.com/Bucket"
