### ISSUE TITLE
IAM violation rules is not working. 

### ISSUE THREAD

**Issue by sparthe123** [forseti-security/forseti-security#3776]
Hi,
 - Version: 2.25.1
 - Issue with scanner
 - Installed via Terraform

There is an issue with our IAM violation rules, we didn't make any change to iam rules config recently but it stopped finding violations and showing zero violations now. Which is not correct because we didn't remove the other domain iam users yet which listed earlier in iam violation scan. Can someone help to find why it stopped finding now

We whitelisted all our internal domain users and few other external domains, but we do have few other domain IAM users added in project which is not whitelisted in below rule. As I described above all those other domains IDs were found as violation and updated in SCC earlier. Now it is not appearing in scanner. 

IAM sample rule.
- name: Other Domain Users added to project access
    mode: whitelist
    resource:
      - type: organization
        applies_to: self_and_children
        resource_ids:
          - '*'
    inherit_from_parents: true
    bindings:
      - role: roles/*
        members:
          - domain:domain.com
          - user:*@domain.com
          - user:user@domain2.com 

Thanks!

**Comment by gkowalski-google** [comment]
Hi @sparthe123, there is an issue with Forseti that is being addressed with a new release. Can you view the Stackdriver logs for the server VM and filter for errors? Can you see if the error listed on [this bug](https://github.com/forseti-security/forseti-security/issues/3774) shows up? This issue has been fixed on the main branch.

**Comment by gkowalski-google** [comment]
I did some testing with the main branch and the IAM scanner is working for me. The default rule is working, and I also tried updating the rule to allow for users from a specific domain. This might be related to the model error; ETA for a fix is next week.

**Comment by gkowalski-google** [comment]
@sparthe123 The latest Forseti release is out to fix the model creation issue. Please upgrade at your convenience and let me know if IAM rules start working again. You can upgrade with Terraform by setting the Forseti module version to `5.2.2` or `~> 5.2.0`.

**Comment by gkowalski-google** [comment]
@sparthe123 Can you let me know if you are still having an issue?

**Comment by gkowalski-google** [comment]
@sparthe123 Closing this issue since we have not heard back, if you are still experiencing issues after upgrading please re-open.

**Comment by sparthe123** [comment]
Sorry for delay , I updated to latest version mentioned above, it is working fine now.
