### ISSUE TITLE
Forseti inventory runs taking too long (16 - 18 hrs)

### ISSUE THREAD

**Issue by jbcraig** [forseti-security/forseti-security#3815]
Version: v2.25.2
Module: Inventory
Environment: Ubuntu VM, no errors as the run completes
Deployment: Terraform to GCP VM

Identified issues:

#1 - We are a large enterprise that uses GSuite and have a rich set of google groups and over 10k users.  Iterating over our groups using the gsuite super admin adds about 4 hours of time to our normal 16-18 hr run.  The groups used to manage our cloud assets are a subset of our overall groups and have distinct naming patterns.  It would be useful to craft a regex to match the groups of interest.

#2 - App scripts have automatically created over 11k projects, all with the a projects ids like ^sys-[0-9]*$ and comprise 96% of all our projects (and growing).  It would be helpful to craft a regex to exclude these projects from introspection.

My primary experience is as a SysAdmin and so I am not really a programmer so much as a hacker.  I've started looking at the code but would love some suggestions about how/where to introduce these features into the code set.  Also, any suggestions on scaling to make the runs more timely would be appreciated.

**Comment by cgobb** [comment]
+1 for #2, this would speed-up alot the process to be able to exclude sys-* projects.

**Comment by gkowalski-google** [comment]
For excluding G Suite groups, that does sound like a good idea. Forseti does not currently have any logic to exclude certain groups. I don't think this would be too hard to add in.

Regarding excluding certain projects and resources..

There is a config variable that allows you to exclude specific resources from the inventory called `excluded_resources`. This only takes in a list of the full resource name (e.g. folders/1234). I think you could add a new variable called `excluded_resources_patterns` (or similar) that can be used to provide a list of regex patterns to exclude from inventory.

One approach would be to update the crawler to get this new variable and store it in the [client config](https://github.com/forseti-security/forseti-security/blob/be3b617df0465564d8b948703576c424ee24e3f3/google/cloud/forseti/services/inventory/crawler.py#L235), which is passed to the [crawler factory](https://github.com/forseti-security/forseti-security/blob/be3b617df0465564d8b948703576c424ee24e3f3/google/cloud/forseti/services/inventory/crawler.py#L270). When processing each resource, the [resource.accept() method](https://github.com/forseti-security/forseti-security/blob/be3b617df0465564d8b948703576c424ee24e3f3/google/cloud/forseti/services/inventory/base/resources.py#L355) is called which could be updated to also do a regex on the current resource with any patterns provided in the config.

I looked and unfortunately the CAI API does not provide any way to filter out specific resources from the CAI export which would help improve performance.
