### ISSUE TITLE
Forseti not seeing IAM users or roles

### ISSUE THREAD

**Issue by olen93** [forseti-security/forseti-security#3828]
Good day,

We are running into an issue where the IAM members and their roles are not being inventoried or not making it to the data model. When ever I run "forseti explainer list_members" it comes back as blank and when I run the command "forseti explainer list_permissions --roles roles/secretmanager.admin" it returns a blank array even through I know it exists because the inventory run output roles/secretmanager.admin as a role it saw. when ever I run forseti explainer list_resources I do see service account but not when I do list_members. not sure if service accounts should be under list_members or not.

Also when I created the IAM rule to not allow admin roles on service accounts and gave a test service account an admin role and ran the scanner against it there were no violations found.
Rule that doesn't allow service accounts to have admin roles:
![image](https://user-images.githubusercontent.com/6578992/96017225-5c411700-0e0f-11eb-93b3-e1731983350d.png)

Account that has the admin role:
![image](https://user-images.githubusercontent.com/6578992/96014094-96a8b500-0e0b-11eb-8644-6da85140ec41.png)

What notrifier says:
![image](https://user-images.githubusercontent.com/6578992/96013858-59442780-0e0b-11eb-9c61-da792b46b957.png)

We are running forseti version 2.25.0

issues seems to be with the model since scanner and explain don't show anything with roles or IAM even though I saw the roles being scanned in the output when the inventory was being created. Didn't see any users though

Deployed using Terraform to GCP

any logs that need to be uploaded I would rather send directly instead of posting here due to the potentially sensitive information that could be contained in them and don't want to post them here for the public to see

**Comment by mkkeffeler** [comment]
+1

**Comment by olen93** [comment]
Anybody have any ideas on this?

**Comment by christianlafleur** [comment]
We have same issue. Only way to get explainer work again is to redeploy from scratch. Long life to Terraform.

**Comment by olen93** [comment]
Sorry, this was fixed by upgrading to the latest version using Terraform to redeploy

**Comment by christianlafleur** [comment]
i just had the problem with v2.25.2.
