### ISSUE TITLE
Forseti not installed in VMs after quick installation

### ISSUE THREAD

**Issue by TCLacioffi** [forseti-security/forseti-security#3863]
I used the cloud shell walktrough to install Forseti and, when i log into the VMs, there are no "forseti" commands available. It's like Forseti wasn't installed at all on the VMs. Terraform didn't throw any errors and all the components (VMs, MySQL) were created successfully.

I tried using "locate" to find any files containing "forseti" but there weren't any.

Any help?

**Comment by aweberlopes** [comment]
Can you check journalctl -u google-startup-scripts.service is the startup script crashed?

**Comment by TCLacioffi** [comment]
Hi aweberlopes, thanks for the suggestion.

Yeah, there are a few errors saying: "google_metadata_script_runner[2244]: 2021/05/25 17:30:31 logging client: rpc error: code = PermissionDenied desc = The caller does not have permission"

The full output is below
[out (2).txt](https://github.com/forseti-security/forseti-security/files/6554137/out.2.txt)

**Comment by TCLacioffi** [comment]
Or maybe this is the problem:
May 25 18:30:53 forseti-client-vm-727dd8d0 GCEMetadataScripts[1469]: 2021/05/25 18:30:53 GCEMetadataScripts: startup-script: No apt package "google-cloud-sdk", but there is a snap with that name.

**Comment by aweberlopes** [comment]
The Same Error like me:
```
May 25 17:30:45 forseti-client-vm-727dd8d0 sudo[3176]:     root : TTY=unknown ; PWD=/ ; USER=root ; ENV=DEBIAN_FRONTEND=noninteractive ; COMMAND=/usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold upgrade
May 25 17:30:45 forseti-client-vm-727dd8d0 sudo[3176]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 25 17:30:45 forseti-client-vm-727dd8d0 GCEMetadataScripts[2769]: 2021/05/25 17:30:45 GCEMetadataScripts: startup-script: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
May 25 17:30:45 forseti-client-vm-727dd8d0 GCEMetadataScripts[2769]: 2021/05/25 17:30:45 GCEMetadataScripts: startup-script: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
May 25 17:30:45 forseti-client-vm-727dd8d0 sudo[3176]: pam_unix(sudo:session): session closed for user root
May 25 17:30:45 forseti-client-vm-727dd8d0 GCEMetadataScripts[2769]: 2021/05/25 17:30:45 GCEMetadataScripts: startup-script exit status 100
May 25 17:30:45 forseti-client-vm-727dd8d0 GCEMetadataScripts[2769]: 2021/05/25 17:30:45 GCEMetadataScripts: Finished running startup scripts.
```

**Comment by aweberlopes** [comment]
So please install the cloud-sdk manually and restart the VM

**Comment by TCLacioffi** [comment]
Good news! Manually installing the google-cloud-sdk package and restarting worked.
I had to follow the steps listed here - maybe they should be included in the startup script?
https://cloud.google.com/sdk/docs/install#deb

Thanks for the help!!

**Comment by onixalan** [comment]
Let me know if I should open a new issue. I'm experiencing the same is where Forseti is not installed on VMs after quick installation (i.e using the Forseti [module](https://github.com/forseti-security/terraform-google-forseti). I understand you can manually install the google-cloud-sdk package after deploying the Forseti Compute Instance, which I have done to get around this issues, but this is something that has to be done each time the server is destroyed and a new one is spun up. Ideally I want this step automated like it's meant to be.

For context, I'm using the [Google Cloud Healthcare Data Protection Suite](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite) and the Forseti module (v.5.2.1) is used.  I've upgraded to v.5.2.2 as well, but I'm getting the same error.

Below is part of the Serial port 1 (console) log where startup script that fails.

`Jun  8 18:27:06 forseti-server-vm-fa2c5f6c systemd[1]: Started Wait until snapd is fully seeded.
Jun  8 18:27:06 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:06 GCEMetadataScripts: startup-script: Processing triggers for dbus (1.12.2-1ubuntu1.2) ...
Jun  8 18:27:06 forseti-server-vm-fa2c5f6c dbus-daemon[999]: [system] Reloaded configuration
Jun  8 18:27:06 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:06 GCEMetadataScripts: startup-script: Processing triggers for mime-support (3.60ubuntu1) ...
Jun  8 18:27:06 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:06 GCEMetadataScripts: startup-script: Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Jun  8 18:27:07 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:07 GCEMetadataScripts: startup-script: Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Jun  8 18:27:07 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:07 GCEMetadataScripts: startup-script: Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease
Jun  8 18:27:07 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:07 GCEMetadataScripts: startup-script: Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease
Jun  8 18:27:07 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:07 GCEMetadataScripts: startup-script: Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: Reading package lists...
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: Reading package lists...
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: Building dependency tree...
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: Reading state information...
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script:
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: No apt package "google-cloud-sdk", but there is a snap with that name.
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: Try "snap install google-cloud-sdk"
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script:
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script: E: Unable to locate package google-cloud-sdk
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: startup-script exit status 100
Jun  8 18:27:09 forseti-server-vm-fa2c5f6c GCEMetadataScripts[2784]: 2021/06/08 18:27:09 GCEMetadataScripts: Finished running startup scripts.`
