### ISSUE TITLE
Extend IAM policy scanner to include group member expansion

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#518]
IAM policy scanner should check that policy members of "user" type are not allowed access via groups that are allowed, if those users have been listed as not allowed.

**Comment by radkomateusz** [comment]
This feature will be really helpful. 

Nevertheless, this feature could be optional for some rules:

We see some use case: 
- writing a rule which does't allow assigning IAM's to users, we only want to give IAM's for groups, so then specific user, even if belongs to allowed group is a violation - then groups resolving should be not used.

- blacklist rule for specific group - then each user which belongs to group should be a violation - then groups resolving should be used.

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.
