### ISSUE TITLE
Publish 6 Month Roadmap

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#524]
The details are tracked in a google doc.

**Comment by kapilt** [comment]
can you make that doc public and provide a link?

**Comment by hshin-g** [comment]
@ryanismert Can we prioritize this by the 2.20 release (August 19, 2019)?

**Comment by hshin-g** [comment]
Create a new page to host the roadmap.

**Comment by gkowalski-google** [comment]
Hi @ryanismert, can you share the roadmap doc with me? I will be working on putting the info on the website.

**Comment by gkowalski-google** [comment]
Roadmap has been published here: https://forsetisecurity.org/about/roadmap.html
