### ISSUE TITLE
Set MySQL root user password and provide db password in Forseti config?

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#769]
Some customers have asked that the MySQL root password be set during the Forseti setup, and that the Forseti database user have a password as well. This request was a prerequisite for them to be allowed to use Forseti in their GCP environment.

There are a few things to consider:

1. Config file has the db password in plaintext and stored in Cloud Storage. Whoever can get objects from the bucket has this password.
2. Whoever has access to modify Cloud SQL settings can easily change the root password.
3. If we create a non-root user via Deployment Manager during the setup wizard, we'd still need to generate a password and grab it to store in the config file.
4. None of these methods guarantee any more security of the Forseti data/database than locking down access to the project, forbidding outside access via authorized networks, and using the identity-based SQL proxy for accessing Cloud SQL.

A short term solution could be to have MySQL set up locally to Forseti and tweak the run_forseti.sh not to download the config file from GCS. (Also, this means that Forseti would need to recognize the db password field in the config.) Of course, whoever can ssh to the instance can probably read the config file.

**Comment by jjawad-google** [comment]
Similar to #921.

**Comment by blueandgold** [comment]
Relates to #3217

**Comment by gkowalski-google** [comment]
This has been completed by this [PR](https://github.com/forseti-security/terraform-google-forseti/pull/399).
