### ISSUE TITLE
Enable email alerts through arbitrary relaying mail servers (via hostname/port)

### ISSUE THREAD

**Issue by xsgbloom** [forseti-security/forseti-security#770]
Issue present in version: 1.1.7

It appears that Forseti Security allows email notifications only via SendGrid as of this version. I see a feature request for adding the ability to relay through G Suite for G Suite customers, however there are many GCP customers who are not G Suite customers. One of them is presently requesting the ability to relay email through their on-premise server, which is connected via a Cloud VPN. In short, the customer would like to be able to specify a hostname and port to relay the notifications through. Presumably, customers would also like the ability to ensure that these messages are communicated securely via SMTPS. It is understood that sending through port 25 via GCP may be restricted, thus the need to be able to specify a different port for the SMTP communications.

**Comment by carise** [comment]
Thanks for filing this issue! Yes, I think ideally we want to make the email sending agnostic in terms of what relay the user chooses.

(note: the issue is present in all versions of Forseti)

related: #749

**Comment by blueandgold** [comment]
On reflection, the work here should take place after the Action Engine's initial release.

**Comment by lawrenae** [comment]
Hi, After working a bit with @blueandgold, I've built a design doc for this that I'd love feedback on:

Hi --

I've looked through the code a bit and, working with Henry,
[built a design doc for this](https://docs.google.com/document/d/1d7OhWHirc1AkhDAFPo0_1pA9WxruqKFgsDm1jlxhxxw/edit?usp=sharing).

Suggestions/Approval would be most helpful.

Thanks!

**Comment by mirons-google** [comment]
Thanks @lawrenae ! I have a few broad questions that would be great to understand before proceeding.

 1. What options do we have to secure the credentials necessary to authenticate to the server?
 1. What options can we support for authentication besides username/password?
 1. In restricted network environments how does one ensure Forseti (the VM) can reach and communicate with the mailhost inside or outside of GCP?
