### ISSUE TITLE
GCStorage ACL scanner for objects in buckets. 

### ISSUE THREAD

**Issue by radkomateusz** [forseti-security/forseti-security#788]
Currently GCS buckets ACL scanner is implemented. It works only for buckets. 

Still it is possible to give accesses to unauthorised people on specific object level and scanner doesn't show any violations. 

It would be nice to have a scanner which could scan ACL for each object in bucket and notify us about violations. 

Note: As each bucket could have thousands or even more files, collecting data about each ACL to inventory could be problematic. Maybe scanner pass-through working in a background is an option.

**Comment by marcin-kolda** [comment]
This task would be much simpler if GCS would have native inventory support similar to [Amazon S3 Inventory](http://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html).

Other alternative is to scan existing objects once and subscribe to all new changes. This could be done by exporting GCS audit logs using Stackdriver to Pub/Sub. Forseti could subscribe to Pub/Sub and process only new events.

**Comment by blueandgold** [comment]
Customer feedback: the likely violations here for the objects could potentially be large and one violation per object could get out of hand.  So, we should think about consolidating these violations in a summary or digest form.

**Comment by Red-Five** [comment]
Is there a target release for this? 

I have a couple of large enterprises that want visibility into whats exposed on their buckets. 

Use case: flag a private bucket containing a public object. Perhaps just flag the violation for the bucket rather than for each object if their is concern about it getting out of hand?

**Comment by Red-Five** [comment]
@blueandgold Bumping this request.

I'm seeing bucket security as the first issue customers ask me about. Are their any updates on this?

**Comment by Red-Five** [comment]
Ref CIS Benchmark document solution.
Quote 
_"1. List All the storage buckets by calling: Get https://www.googleapis.com/storage/v1/b?project=<projectName>
2. For Every bucket, List objects inside the bucket by calling: GET https://www.googleapis.com/storage/v1/b/<buvketName>/o/
3. For Every Object, get object ACL by calling: GET https://www.googleapis.com/storage/v1/b/pp-test-storage-bucket/o/<objectName>/acl
4. In Object ACL returned check if entity "allUsers" does not exists. If it exists, object is publicly accessible."_

**Comment by blueandgold** [comment]
@Red-Five Thanks for inquiring about this.  This is something that is definitely high up on our radar.  But the difficulty is with the size of the problem, O(10M to 100M) objects to be scanned.  We have been thinking about what would be the most effective way to tackle this, but is exploring with the GCP teams to help.  There are no clear path forward yet, but if you have any ideas, we would love to chat with you about this.

**Comment by Red-Five** [comment]
There's a hole in the bucket, dear Liza, dear Liza,
There's a hole in the bucket, dear Liza, a hole.

So fix it dear Henry, dear Henry, dear Henry,
So fix it dear Henry, dear Henry, fix it.

With what should I fix it, dear Liza, dear Liza,
With what should I fix it, dear Liza, with what?

With BigTable, dear Henry, dear Henry, dear Henry,
With BigTable, dear Henry, dear Henry, with BigTable.

With what shall I baseline it, dear Liza, dear Liza,
With what shall I baseline it, dear Liza, with what.

With a crawler dear Henry, dear Henry, dear Henry,
With a crawler dear Henry, dear Henry, crawl it

With what should I update it, dear Liza, dear Liza,
With what should I update it, dear Liza, with what?

With a pub sub notification, dear Henry, dear Henry, dear Henry,
With a pub sub notification, dear Henry, pub sub.

With what should I query it, dear Liza, dear Liza,
With what should I query it, dear Liza, with what?

With a view, dear Henry, dear Henry, dear Henry,
With a view, dear Henry, a view.

With what can I export it, dear Liza, dear Liza,
With what can I export it, dear Liza, with what?

With a bucket, dear Henry, dear Henry, dear Henry,
With a bucket, dear Henry, a bucket.

There's a hole in the bucket, dear Liza, dear Liza,
There's a hole in the bucket, dear Liza, a hole.
