### ISSUE TITLE
Allow existing MySQL instance in Forseti deployment scripts

### ISSUE THREAD

**Issue by Dnefedkin** [forseti-security/forseti-security#806]
As of today Deployment Manager scripts for Forseti deployment are written in a way that a new Cloud SQL instance is deployed. 
There are situations when customers need to use existing MySQL deployments instead of creating a new Cloud SQL instance, the most obvious examples: 
- external IP addresses are prohibited for security reasons (Cloud SQL requires external IP)
- Cloud SQL is not approved by customer's InfoSec team 

The proposal is to customize Deployment Manager scripts in a way that it would be possible to utilize existing MySQL instances (e.g. running on GCE or even on premises).

**Comment by mirons-google** [comment]
**Issue Review**: We think we can solve this with a guide written for forsetisecurity.org. @Dnefedkin I'll reach out and discuss how we can do this together.
