### ISSUE TITLE
Document how to restore or rebuild the Foreseti VM

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#830]
In the case that we lose the VM, or the customer has a requirement to run an up-to-date instance every N weeks.

**Comment by mirons-google** [comment]
**Issue Review**: Documentation issue.

**Comment by blueandgold** [comment]
This will also need to include how to handle and manage the gsuite_reader service account key, which is currently not saved somewhere shared: i.e. currently only saved on the vm, and the original installer's cloud shell.

It would be nice, if we have a tool that can handle this automatically.

**Comment by carise** [comment]
The key is only stored on the VM. It gets deleted from the cloud shell.

**Comment by blueandgold** [comment]
Linking issue #856

**Comment by blueandgold** [comment]
Per andrew: an instance template with an instance manager may help with a new VM built every N days automatically.

**Comment by blueandgold** [comment]
Per Carise: Could break this out into different installer modules.
