### ISSUE TITLE
Documentation: create a reference of Forseti configuration properties per version

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#853]
See http://www.squid-cache.org/Doc/config/ for a very detailed example. We don't have to do that per se, but we should make it easy for users to look up what configuration properties are relevant and where.

**Comment by blueandgold** [comment]
Per andrew: think about the upgrade strategy first, and then build the documentation around it.

**Comment by blueandgold** [comment]
On reflection, the work here should take place after 2.0's initial release.
