### ISSUE TITLE
Support Other Email Services

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#859]
This includes non-sendmail, or SMTP-based (important for not sending sensitive security data to 3rd parties).

**Comment by blueandgold** [comment]
On reflection, the work here should take place after the Action Engine's initial release.

**Comment by kapilt** [comment]
the notifier seems pretty hard-wired to sendgrid at the moment, would be nice to support smtp as a standard baseline.

**Comment by blueandgold** [comment]
Andy Lawrence has an initial design doc here.
https://groups.google.com/a/forsetisecurity.org/d/msg/discuss/YGmop4TuPck/0gG5g7IrBwAJ
