### ISSUE TITLE
Support Pub/Sub as a Notification

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#862]

**Comment by arbeit** [comment]
Hello! I'd be interested in implementing this. Can we have a brief chat how to best go about it?

**Comment by blueandgold** [comment]
Absolutely!  This will be quite a big chunk of work, that will affect all the forseti sub-components.  IIRC the last status, pubsub is still a bit far off for us, as we are still intending to invoke the components as a library.  Nonetheless, I will put you in touch with @mwwolters and @joecheuk if your help here would expedite things.
