### ISSUE TITLE
Create MySQL user "forseti_user" via setup wizard for consistency in docs

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#921]
Setup wizard defaults to using the "root" mysql user. Likely changes would be:

* Create the new user via deployment manager
* Update the generated Forseti config to use forseti_user

requested by @Tabrarian

**Comment by joecheuk** [comment]
Due to the limitation of the way deployment manager handle requests (#1493), it's best to change the db user to root to avoid potential deployment problems.

**Comment by joecheuk** [comment]
This is now resolved in the terraform module.
